SELECT *
FROM Customers;

SELECT *
FROM Orders;

SELECT *
FROM Products;


-- 1. Show all customers from 'Mumbai'.

SELECT *
FROM Customers
WHERE City = 'Mumbai';


-- 2. Show all products with price greater than 30000. 

SELECT *
FROM Products
WHERE Price > 30000;


-- 3. Show customer names and the total number of orders they placed. 

SELECT Customers.Customer_ID, 
	   Customers.Customer_Name,
       COUNT(Orders.Order_ID) AS No_of_Orders
FROM Customers
INNER JOIN Orders
	ON Customers.Customer_ID = Orders.Customer_ID
GROUP BY Customers.Customer_ID, Customers.Customer_Name;


-- 4. Find the cheapest product. 

SELECT *
FROM Products
WHERE Price = (
	SELECT MIN(Price)
    FROM Products
    );

-- OR

SELECT *
FROM Products
ORDER BY Price ASC
LIMIT 1;


-- 5. Show customers who have never ordered anything.

SELECT *
FROM Customers
LEFT JOIN Orders
	ON Customers.Customer_ID = Orders.Customer_ID
WHERE Orders.Order_ID IS NULL;


-- 6. Show total revenue generated by each product.

SELECT Products.Product_ID,
	   Products.Product_Name,
       SUM(Orders.Quantity * Products.Price) AS Total_Revenue
FROM Orders
INNER JOIN Products
	ON Orders.Product_ID = Products.Product_ID
    GROUP BY Products.Product_ID, Products.Product_Name;


-- 7. Find the product that generated the highest revenue. 

SELECT Products.Product_ID,
	   Products.Product_Name,
       SUM(Orders.Quantity * Products.Price) AS Total_Revenue
FROM Orders
INNER JOIN Products
	ON Orders.Product_ID = Products.Product_ID
GROUP BY Products.Product_ID, Products.Product_Name
ORDER BY Total_Revenue DESC
LIMIT 1;

-- OR

SELECT Products.Product_ID,
	   Products.Product_Name,
       SUM(Orders.Quantity * Products.Price) AS Total_Revenue
FROM Orders
INNER JOIN Products
	ON Orders.Product_ID = Products.Product_ID
GROUP BY Products.Product_ID, Products.Product_Name
HAVING Total_Revenue = (
	SELECT MAX(Total_Revenue)
    FROM (
		SELECT Products.Product_ID,
		Products.Product_Name,
		SUM(Orders.Quantity * Products.Price) AS Total_Revenue
		FROM Orders
		INNER JOIN Products
			ON Orders.Product_ID = Products.Product_ID
		GROUP BY Products.Product_ID, Products.Product_Name
        ) M
);


-- 8. Show customers who ordered more than 2 total items. 

SELECT Customers.Customer_ID,
	   Customers.Customer_Name,
       SUM(Orders.Quantity) AS Total
FROM Customers
INNER JOIN Orders
	ON Customers.Customer_ID = Orders.Customer_ID
GROUP BY Customers.Customer_ID, Customers.Customer_Name
HAVING Total > 2;


-- 9. Show orders where the product price is above the average product price. 

SELECT Orders.Order_ID,
       Orders.Customer_ID,
       Products.Product_Name,
       Orders.Quantity,
       Products.Price
FROM Orders
INNER JOIN Products
    ON Orders.Product_ID = Products.Product_ID
WHERE Products.Price > (
    SELECT AVG(Price)
    FROM Products
);


-- 10. Find the city with the highest total revenue.

SELECT Customers.City,
	   SUM(Orders.Quantity * Products.Price) AS Total_Revenue
FROM Customers
INNER JOIN Orders
	ON Customers.Customer_ID = Orders.Customer_ID
INNER JOIN Products
	ON Orders.Product_ID = Products.Product_ID
GROUP BY Customers.City
ORDER BY Total_Revenue DESC
LIMIT 1;

-- OR 

SELECT Customers.City,
	   SUM(Orders.Quantity * Products.Price) AS Total_Revenue
FROM Customers
INNER JOIN Orders
	ON Customers.Customer_ID = Orders.Customer_ID
INNER JOIN Products
	ON Orders.Product_ID = Products.Product_ID
GROUP BY Customers.City
HAVING Total_Revenue = (
	SELECT MAX(Total_Revenue)
    FROM (
		SELECT Customers.City,
			   SUM(Orders.Quantity * Products.Price) AS Total_Revenue
		FROM Customers
		INNER JOIN Orders
			ON Customers.Customer_ID = Orders.Customer_ID
		INNER JOIN Products
			ON Orders.Product_ID = Products.Product_ID
		GROUP BY Customers.City
        ) T
);
		



