USE Daily_SQL;

-- DATASET

CREATE TABLE Subscription_Activity (
    Activity_ID INT,
    User_ID INT,
    User_Name VARCHAR(50),
    Activity_Date DATE,
    Plan_Name VARCHAR(30),
    Amount_Paid INT,
    Activity_Type VARCHAR(20)
);

INSERT INTO Subscription_Activity 
VALUES	(1,101,'Alice','2024-01-01','Basic',500,'Subscribe'),
		(2,101,'Alice','2024-01-02','Basic',500,'Renew'),
		(3,101,'Alice','2024-01-03','Premium',1000,'Upgrade'),
		(4,101,'Alice','2024-01-08','Premium',1000,'Renew'),

		(5,102,'Bob','2024-01-01','Basic',500,'Subscribe'),
		(6,102,'Bob','2024-01-05','Basic',500,'Renew'),
		(7,102,'Bob','2024-01-06','Premium',1000,'Upgrade'),

		(8,103,'Charlie','2024-01-02','Premium',1000,'Subscribe'),
		(9,103,'Charlie','2024-01-03','Premium',1000,'Renew'),
		(10,103,'Charlie','2024-01-04','Premium',1000,'Renew'),
		(11,103,'Charlie','2024-01-05','Premium',1000,'Renew'),

		(12,104,'David','2024-01-01','Basic',500,'Subscribe'),
		(13,104,'David','2024-01-08','Basic',500,'Renew'),

		(14,105,'Emma','2024-01-03','Premium',1000,'Subscribe'),
		(15,105,'Emma','2024-01-04','Premium',1000,'Renew'),
		(16,105,'Emma','2024-01-05','Premium',1000,'Renew');
        

SELECT *
FROM Subscription_Activity;

-- Q1
-- Show each user's total activity records,
-- total amount paid, and average amount paid.
--
-- Return:
-- User_ID
-- User_Name
-- Total_Activity_Records
-- Total_Amount_Paid
-- Average_Amount_Paid

SELECT User_ID, User_Name,
	   COUNT(Activity_ID) AS Total_Activity_Records,
       SUM(Amount_Paid) AS Total_Amount_Paid,
       ROUND(AVG(Amount_Paid), 2) AS Average_Amount_Paid
FROM Subscription_Activity
GROUP BY User_ID, User_Name;


-- Q2
-- Show each plan's total activity records
-- and total revenue.
--
-- Return:
-- Plan_Name
-- Total_Activity_Records
-- Total_Revenue

SELECT Plan_Name,
	   COUNT(Activity_ID) AS Total_Activity_Records,
       SUM(Amount_Paid) AS Total_Revenue
FROM Subscription_Activity
GROUP BY Plan_Name;


-- Q3
-- Find the top 3 users by total amount paid.
--
-- Return:
-- User_ID
-- User_Name
-- Total_Amount_Paid

WITH CTE AS (
	SELECT User_ID, User_Name,
		   SUM(Amount_Paid) AS Total_Amount_Paid
	FROM Subscription_Activity
	GROUP BY User_ID, User_Name
),
CTE2 AS (
	SELECT *,
		   DENSE_RANK() OVER(ORDER BY Total_Amount_Paid DESC) AS D_Rank
	FROM CTE
)
SELECT User_ID, User_Name, Total_Amount_Paid
FROM CTE2
WHERE D_Rank <= 3;


-- Q4
-- Find users who performed an activity within 2 days
-- of their previous activity.
--
-- Return:
-- User_ID
-- User_Name

WITH CTE AS (
	SELECT User_ID, User_Name, Activity_Date,
		   LAG(Activity_Date) OVER(PARTITION BY User_ID
           ORDER BY Activity_Date, Activity_ID) AS Previous
	FROM Subscription_Activity
)
SELECT DISTINCT User_ID, User_Name
FROM CTE
WHERE Previous IS NOT NULL
AND DATEDIFF(Activity_Date, Previous) <= 2;


-- Q5 (COHORT ANALYSIS)
-- For each signup month, find:
-- total users who subscribed in that month
-- and total revenue generated by those users.
--
-- Definition:
-- A user's cohort month is the month of their
-- first activity date.
--
-- Return:
-- Cohort_Month
-- Total_Users
-- Total_Revenue

WITH CTE AS (
	SELECT User_ID,
		   MIN(Activity_Date) AS First_Activity_Date
	FROM Subscription_Activity
    GROUP BY User_ID
),
CTE2 AS (
	SELECT *,
           DATE_FORMAT(First_Activity_Date, '%Y-%m') AS Cohort_Month
	FROM CTE
)
SELECT Cohort_Month,
	   COUNT(DISTINCT S.User_ID) AS Total_Users,
       SUM(Amount_Paid) AS Total_Revenue
FROM CTE2 C
INNER JOIN Subscription_Activity S
	ON S.User_ID = C.User_ID
GROUP BY Cohort_Month;


-- BONUS (GAP & ISLAND)
-- Find the start date and end date of each user's
-- longest activity streak.
--
-- Return:
-- User_ID
-- User_Name
-- Longest_Streak
-- Start_Date
-- End_Date
--
-- Note:
-- Ignore duplicate activity dates if a user
-- has multiple activities on the same day.

WITH CTE AS (
	SELECT DISTINCT User_ID, User_Name, Activity_Date
    FROM Subscription_Activity
),
CTE2 AS (
	SELECT *,
		   ROW_NUMBER() OVER(PARTITION BY User_ID
           ORDER BY Activity_Date) AS RN
	FROM CTE
),
CTE3 AS (
	SELECT *,
		   DATE_SUB(Activity_Date, INTERVAL RN DAY) AS GK
	FROM CTE2
),
CTE4 AS (
	SELECT User_ID, User_Name,
		   COUNT(*) AS Streak,
           MIN(Activity_Date) AS Start_Date,
           MAX(Activity_Date) AS End_Date
	FROM CTE3
    GROUP BY User_ID, User_Name, GK
),
CTE5 AS (
	SELECT *,
		   ROW_NUMBER() OVER(PARTITION BY User_ID
           ORDER BY Streak DESC, End_Date DESC) AS Row_Num
	FROM CTE4
)		   
SELECT User_ID, User_Name, Streak AS Longest_Streak,
	   Start_Date, End_Date
FROM CTE5
WHERE Row_Num = 1;
       