USE Daily_SQL;

-- DATASET

CREATE TABLE Food_Delivery_Orders (
    Order_ID INT,
    Customer_ID INT,
    Customer_Name VARCHAR(50),
    Order_Date DATE,
    Restaurant_Name VARCHAR(50),
    Order_Amount INT
);

INSERT INTO Food_Delivery_Orders 
VALUES	(1,101,'Alice','2024-01-01','Pizza Hub',450),
		(2,101,'Alice','2024-01-02','Pizza Hub',300),
		(3,101,'Alice','2024-01-03','Burger Town',250),
		(4,101,'Alice','2024-01-08','Burger Town',500),

		(5,102,'Bob','2024-01-01','Pizza Hub',350),
		(6,102,'Bob','2024-01-05','Taco House',400),
		(7,102,'Bob','2024-01-06','Pizza Hub',300),

		(8,103,'Charlie','2024-01-02','Taco House',600),
		(9,103,'Charlie','2024-01-03','Taco House',450),
		(10,103,'Charlie','2024-01-04','Pizza Hub',700),
		(11,103,'Charlie','2024-01-05','Burger Town',350),

		(12,104,'David','2024-01-01','Burger Town',300),
		(13,104,'David','2024-01-08','Burger Town',450),

		(14,105,'Emma','2024-01-03','Pizza Hub',800),
		(15,105,'Emma','2024-01-04','Pizza Hub',900),
		(16,105,'Emma','2024-01-05','Taco House',500);
        

SELECT *
FROM Food_Delivery_Orders;


-- Q1
-- Show each customer's total orders,
-- total amount spent, and average order amount.
--
-- Return:
-- Customer_ID
-- Customer_Name
-- Total_Orders
-- Total_Amount_Spent
-- Average_Order_Amount

SELECT Customer_ID, Customer_Name,
	   COUNT(Order_ID) AS Total_Orders,
       SUM(Order_Amount) AS Total_Amount_Spent,
       ROUND(AVG(Order_Amount), 2) AS Average_Order_Amount
FROM Food_Delivery_Orders
GROUP BY Customer_ID, Customer_Name;


-- Q2
-- Show each restaurant's total orders
-- and total revenue.
--
-- Return:
-- Restaurant_Name
-- Total_Orders
-- Total_Revenue

SELECT Restaurant_Name,
	   COUNT(Order_ID) AS Total_Orders,
       SUM(Order_Amount) AS Total_Revenue
FROM Food_Delivery_Orders
GROUP BY Restaurant_Name;


-- Q3
-- Find the top 3 customers by total amount spent.
--
-- Return:
-- Customer_ID
-- Customer_Name
-- Total_Amount_Spent

WITH CTE AS (
	SELECT Customer_ID, Customer_Name,
		   SUM(Order_Amount) AS Total_Amount_Spent
	FROM Food_Delivery_Orders
	GROUP BY Customer_ID, Customer_Name
),
CTE2 AS (
	SELECT *,
		   DENSE_RANK() OVER(ORDER BY Total_Amount_Spent DESC) AS D_Rank
	FROM CTE
)
SELECT Customer_ID, Customer_Name, Total_Amount_Spent
FROM CTE2
WHERE D_Rank <= 3;


-- Q4
-- Find customers who placed an order within 2 days
-- of their previous order.
--
-- Return:
-- Customer_ID
-- Customer_Name

WITH CTE AS (
	SELECT Customer_ID, Customer_Name, Order_Date,
		   LAG(Order_Date) OVER(PARTITION BY Customer_ID
           ORDER BY Order_Date, Order_ID) AS Previous
	FROM Food_Delivery_Orders
)
SELECT DISTINCT Customer_ID, Customer_Name
FROM CTE
WHERE Previous IS NOT NULL
AND DATEDIFF(Order_Date, Previous) <= 2;


-- Q5 (COHORT ANALYSIS)
-- For each cohort month, find:
-- total customers
-- and total revenue generated by those customers.
--
-- Definition:
-- A customer's cohort month is the month of
-- their first order date.
--
-- Return:
-- Cohort_Month
-- Total_Customers
-- Total_Revenue

WITH CTE AS (
	SELECT Customer_ID,
		   MIN(Order_Date) AS First_Order_Date
	FROM Food_Delivery_Orders
    GROUP BY Customer_ID
),
CTE2 AS (
	SELECT *,
		   DATE_FORMAT(First_Order_Date, '%Y-%m') AS Cohort_Month
	FROM CTE
)
SELECT Cohort_Month,
	   COUNT(DISTINCT O.Customer_ID) AS Total_Customers,
       SUM(O.Order_Amount) AS Total_Revenue
FROM CTE2 C
INNER JOIN Food_Delivery_Orders O
	ON C.Customer_ID = O.Customer_ID
GROUP BY Cohort_Month;


-- BONUS (GAP & ISLAND)
-- Find the start date and end date of each customer's
-- current order streak.
--
-- Return:
-- Customer_ID
-- Customer_Name
-- Current_Streak
-- Start_Date
-- End_Date
--
-- Definition:
-- Current streak = streak containing the customer's
-- most recent order date.
--
-- Note:
-- Ignore duplicate order dates if a customer
-- has multiple orders on the same day.

WITH CTE AS (
	SELECT DISTINCT Customer_ID, Customer_Name, Order_Date
    FROM Food_Delivery_Orders
),
CTE2 AS (
	SELECT *,
		   ROW_NUMBER() OVER(PARTITION BY Customer_ID
           ORDER BY Order_Date) AS RN
	FROM CTE
),
CTE3 AS (
	SELECT *,
		   DATE_SUB(Order_Date, INTERVAL RN DAY) AS GK
	FROM CTE2
),
CTE4 AS (
	SELECT Customer_ID, Customer_Name,
		   COUNT(*) AS Streak,
           MIN(Order_Date) AS Start_Date,
           MAX(Order_Date) AS End_Date
	FROM CTE3
    GROUP BY Customer_ID, Customer_Name, GK
),
CTE5 AS (
	SELECT *,
		   ROW_NUMBER() OVER(PARTITION BY Customer_ID
           ORDER BY End_Date DESC) AS Row_Num
	FROM CTE4
)		   
SELECT Customer_ID, Customer_Name, Streak AS Current_Streak,
	   Start_Date, End_Date
FROM CTE5
WHERE Row_Num = 1;