USE Daily_SQL;

-- DATASET

CREATE TABLE Ride_Sharing_Trips (
    Trip_ID INT,
    Rider_ID INT,
    Rider_Name VARCHAR(50),
    Trip_Date DATE,
    City VARCHAR(50),
    Fare_Amount INT
);

INSERT INTO Ride_Sharing_Trips 
VALUES	(1,101,'Alice','2024-01-01','Chennai',250),
		(2,101,'Alice','2024-01-02','Chennai',300),
		(3,101,'Alice','2024-01-03','Bangalore',450),
		(4,101,'Alice','2024-01-08','Chennai',350),

		(5,102,'Bob','2024-01-01','Mumbai',500),
		(6,102,'Bob','2024-01-05','Mumbai',250),
		(7,102,'Bob','2024-01-06','Delhi',400),

		(8,103,'Charlie','2024-01-02','Delhi',600),
		(9,103,'Charlie','2024-01-03','Delhi',350),
		(10,103,'Charlie','2024-01-04','Mumbai',700),
		(11,103,'Charlie','2024-01-05','Chennai',450),

		(12,104,'David','2024-01-01','Bangalore',300),
		(13,104,'David','2024-01-08','Bangalore',550),

		(14,105,'Emma','2024-01-03','Chennai',800),
		(15,105,'Emma','2024-01-04','Chennai',900),
		(16,105,'Emma','2024-01-05','Mumbai',500);
        

SELECT *
FROM Ride_Sharing_Trips;
        

-- Q1
-- Show each rider's total trips,
-- total fare amount, and average fare amount.
--
-- Return:
-- Rider_ID
-- Rider_Name
-- Total_Trips
-- Total_Fare_Amount
-- Average_Fare_Amount

SELECT Rider_ID, Rider_Name,
	   COUNT(Trip_ID) AS Total_Trips,
       SUM(Fare_Amount) AS Total_Fare_Amount,
       ROUND(AVG(Fare_Amount), 2) AS Average_Fare_Amount
FROM Ride_Sharing_Trips
GROUP BY Rider_ID, Rider_Name;


-- Q2
-- Show each city's total trips
-- and total fare revenue.
--
-- Return:
-- City
-- Total_Trips
-- Total_Fare_Revenue

SELECT City,
	   COUNT(Trip_ID) AS Total_Trips,
       SUM(Fare_Amount) AS Total_Fare_Revenue
FROM Ride_Sharing_Trips
GROUP BY City;


-- Q3
-- Find the top 3 riders by total fare amount.
--
-- Return:
-- Rider_ID
-- Rider_Name
-- Total_Fare_Amount

WITH CTE AS (
	SELECT Rider_ID, Rider_Name,
		   SUM(Fare_Amount) AS Total_Fare_Amount
	FROM Ride_Sharing_Trips
    GROUP BY Rider_ID, Rider_Name
),
CTE2 AS (
	SELECT *,
		   RANK() OVER(ORDER BY Total_Fare_Amount DESC) AS Rnk
	FROM CTE
)
SELECT Rider_ID, Rider_Name, Total_Fare_Amount
FROM CTE2
WHERE Rnk <= 3;


-- Q4
-- Find riders who took a trip within 2 days
-- of their previous trip.
--
-- Return:
-- Rider_ID
-- Rider_Name

WITH CTE AS (
	SELECT Rider_ID, Rider_Name, Trip_Date,
		   LAG(Trip_Date) OVER(PARTITION BY Rider_ID
           ORDER BY Trip_Date, Trip_ID) AS Previous
	FROM Ride_Sharing_Trips
)
SELECT DISTINCT Rider_ID, Rider_Name
FROM CTE
WHERE Previous IS NOT NULL AND
DATEDIFF(Trip_Date, Previous) <= 2;


-- Q5 (COHORT ANALYSIS)
-- For each cohort month, find:
-- total riders
-- and total fare revenue generated by those riders.
--
-- Definition:
-- A rider's cohort month is the month of
-- their first trip date.
--
-- Return:
-- Cohort_Month
-- Total_Riders
-- Total_Fare_Revenue

WITH CTE AS (
	SELECT Rider_ID,
		   MIN(Trip_Date) AS First_Ride_Date
	FROM Ride_Sharing_Trips
    GROUP BY Rider_ID
),
CTE2 AS (
	SELECT *,
		   DATE_FORMAT(First_Ride_Date, '%Y-%m') AS Cohort_Month
	FROM CTE
)
SELECT Cohort_Month,
	   COUNT(DISTINCT R.Rider_ID) AS Total_Riders,
       SUM(R.Fare_Amount) AS Total_Fare_Revenue
FROM CTE2 C
INNER JOIN Ride_Sharing_Trips R
	ON C.Rider_ID = R.Rider_ID
GROUP BY Cohort_Month;


-- BONUS (GAP & ISLAND)
-- Find the start date and end date of each rider's
-- longest trip streak.
--
-- Return:
-- Rider_ID
-- Rider_Name
-- Longest_Streak
-- Start_Date
-- End_Date
--
-- Note:
-- Ignore duplicate trip dates if a rider
-- has multiple trips on the same day.
--
-- If multiple streaks have the same length,
-- return the most recent streak.

WITH CTE AS (
	SELECT DISTINCT Rider_ID, Rider_Name, Trip_Date
    FROM Ride_Sharing_Trips
),
CTE2 AS (
	SELECT *,
		   ROW_NUMBER() OVER(PARTITION BY Rider_ID
           ORDER BY Trip_Date) AS RN
	FROM CTE
),
CTE3 AS (
	SELECT *,
		   DATE_SUB(Trip_Date, INTERVAL RN DAY) AS GK
	FROM CTE2
),
CTE4 AS (
	SELECT Rider_ID, Rider_Name,
		   COUNT(*) AS Streak,
           MIN(Trip_Date) AS Start_Date,
           MAX(Trip_Date) AS End_Date
	FROM CTE3
    GROUP BY Rider_ID, Rider_Name, GK
),
CTE5 AS (
	SELECT *,
		   ROW_NUMBER() OVER(PARTITION BY Rider_ID
           ORDER BY Streak DESC, End_Date DESC) AS Row_Num
	FROM CTE4
)
SELECT Rider_ID, Rider_Name, Streak AS Longest_Streak,
	   Start_Date, End_Date
FROM CTE5
WHERE Row_Num = 1;
