USE Daily_SQL;


-- DATASET

CREATE TABLE Banking_Transactions (
    Transaction_ID INT,
    Customer_ID INT,
    Customer_Name VARCHAR(50),
    Transaction_Date DATE,
    Transaction_Type VARCHAR(20),
    Amount INT
);

INSERT INTO Banking_Transactions 
VALUES	(1,101,'Alice','2024-01-01','Deposit',5000),
		(2,101,'Alice','2024-01-02','Withdrawal',2000),
		(3,101,'Alice','2024-01-03','Deposit',3000),
		(4,101,'Alice','2024-01-08','Deposit',4000),

		(5,102,'Bob','2024-01-01','Deposit',6000),
		(6,102,'Bob','2024-01-05','Withdrawal',1500),
		(7,102,'Bob','2024-01-06','Deposit',2500),

		(8,103,'Charlie','2024-01-02','Deposit',7000),
		(9,103,'Charlie','2024-01-03','Deposit',3500),
		(10,103,'Charlie','2024-01-04','Withdrawal',2000),
		(11,103,'Charlie','2024-01-05','Deposit',4500),

		(12,104,'David','2024-01-01','Deposit',3000),
		(13,104,'David','2024-01-08','Withdrawal',1000),

		(14,105,'Emma','2024-01-03','Deposit',8000),
		(15,105,'Emma','2024-01-04','Deposit',9000),
		(16,105,'Emma','2024-01-05','Withdrawal',2500);
        

SELECT *
FROM Banking_Transactions;


-- Q1
-- Show each customer's total transactions,
-- total transaction amount, and average transaction amount.
--
-- Return:
-- Customer_ID
-- Customer_Name
-- Total_Transactions
-- Total_Transaction_Amount
-- Average_Transaction_Amount

SELECT Customer_ID, Customer_Name,
	   COUNT(Transaction_ID) AS Total_Transactions,
       SUM(Amount) AS Total_Transaction_Amount,
       ROUND(AVG(Amount), 2) AS Average_Transaction_Amount
FROM Banking_Transactions
GROUP BY Customer_ID, Customer_Name;


-- Q2
-- Show each transaction type's total transactions
-- and total amount.
--
-- Return:
-- Transaction_Type
-- Total_Transactions
-- Total_Amount

SELECT Transaction_Type,
	   COUNT(Transaction_ID) AS Total_Transactions,
       SUM(Amount) AS Total_Amount
FROM Banking_Transactions
GROUP BY Transaction_Type;



-- Q3
-- Find the top 3 customers by total transaction amount.
--
-- Return:
-- Customer_ID
-- Customer_Name
-- Total_Transaction_Amount

WITH CTE AS (
	SELECT Customer_ID, Customer_Name,
		   SUM(Amount) AS Total_Transaction_Amount
	FROM Banking_Transactions
    GROUP BY Customer_ID, Customer_Name
),
CTE2 AS (
	SELECT *,
		   RANK() OVER(ORDER BY Total_Transaction_Amount DESC) AS Rnk
	FROM CTE
)
SELECT Customer_ID, Customer_Name, Total_Transaction_Amount
FROM CTE2
WHERE Rnk <= 3;


-- Q4
-- Find customers who made a transaction within 2 days
-- of their previous transaction.
--
-- Return:
-- Customer_ID
-- Customer_Name

WITH CTE AS (
	SELECT Customer_ID, Customer_Name, Transaction_Date,
		   LAG(Transaction_Date) OVER(PARTITION BY Customer_ID
           ORDER BY Transaction_Date, Customer_ID) AS Previous
	FROM Banking_Transactions
)
SELECT DISTINCT Customer_ID, Customer_Name
FROM CTE
WHERE Previous IS NOT NULL AND
DATEDIFF(Transaction_Date, Previous) <= 2;


-- Q5 (COHORT ANALYSIS)
-- For each cohort month, find:
-- total customers
-- and total transaction amount generated by those customers.
--
-- Definition:
-- A customer's cohort month is the month of
-- their first transaction date.
--
-- Return:
-- Cohort_Month
-- Total_Customers
-- Total_Transaction_Amount

WITH CTE AS (
	SELECT Customer_ID,
		   MIN(Transaction_Date) AS First_Transaction_Date
	FROM Banking_Transactions
    GROUP BY Customer_ID
),
CTE2 AS (
	SELECT *,
		   DATE_FORMAT(First_Transaction_Date, '%Y-%m') AS Cohort_Month
	FROM CTE
)
SELECT Cohort_Month,
	   COUNT(DISTINCT C.Customer_ID) AS Total_Customers,
	   SUM(B.Amount) AS Total_Transaction_Amount
FROM CTE2 C
INNER JOIN Banking_Transactions B
	ON C.Customer_ID = B.Customer_ID
GROUP BY Cohort_Month;


-- BONUS (GAP & ISLAND)
-- Find all customers whose longest transaction streak
-- is at least 4 days.
--
-- Return:
-- Customer_ID
-- Customer_Name
-- Longest_Streak
--
-- Note:
-- Ignore duplicate transaction dates if a customer
-- has multiple transactions on the same day.
--
-- If multiple streaks exist,
-- consider only the longest streak.

WITH CTE AS (
	SELECT DISTINCT Customer_ID, Customer_Name, Transaction_Date
    FROM Banking_Transactions
),
CTE2 AS (
	SELECT *,
		   ROW_NUMBER() OVER(PARTITION BY Customer_ID
           ORDER BY Transaction_Date) AS RN
	FROM CTE
),
CTE3 AS (
	SELECT *,
		   DATE_SUB(Transaction_Date, INTERVAL RN DAY) AS GK
	FROM CTE2
),
CTE4 AS (
	SELECT Customer_ID, Customer_Name,
		   COUNT(*) AS Streak
	FROM CTE3
    GROUP BY Customer_ID, Customer_Name, GK
)
SELECT Customer_ID, Customer_Name,
	   MAX(Streak) AS Longest_Streak
FROM CTE4
GROUP BY Customer_ID, Customer_Name
HAVING MAX(Streak) >= 4;