USE Daily_SQL;

-- DATASET

CREATE TABLE Hotel_Bookings (
    Booking_ID INT,
    Customer_ID INT,
    Customer_Name VARCHAR(50),
    Booking_Date DATE,
    Hotel_City VARCHAR(50),
    Booking_Amount INT
);

INSERT INTO Hotel_Bookings 
VALUES	(1,101,'Alice','2024-01-01','Chennai',5000),
		(2,101,'Alice','2024-01-02','Chennai',3000),
		(3,101,'Alice','2024-01-03','Bangalore',4500),
		(4,101,'Alice','2024-01-08','Mumbai',6000),

		(5,102,'Bob','2024-01-01','Delhi',7000),
		(6,102,'Bob','2024-01-05','Delhi',2500),
		(7,102,'Bob','2024-01-06','Mumbai',3500),

		(8,103,'Charlie','2024-01-02','Chennai',8000),
		(9,103,'Charlie','2024-01-03','Bangalore',2000),
		(10,103,'Charlie','2024-01-04','Bangalore',3000),
		(11,103,'Charlie','2024-01-05','Mumbai',4000),

		(12,104,'David','2024-01-01','Delhi',4500),
		(13,104,'David','2024-01-08','Delhi',1500),

		(14,105,'Emma','2024-01-03','Mumbai',9000),
		(15,105,'Emma','2024-01-04','Mumbai',5000),
		(16,105,'Emma','2024-01-05','Chennai',3500);
        
SELECT *
FROM Hotel_Bookings;


-- Q1
-- Show each customer's total bookings,
-- total booking amount, and average booking amount.
--
-- Return:
-- Customer_ID
-- Customer_Name
-- Total_Bookings
-- Total_Booking_Amount
-- Average_Booking_Amount

SELECT Customer_ID, Customer_Name,
	   COUNT(Booking_ID) AS Total_Bookings,
       SUM(Booking_Amount) AS Total_Booking_Amount,
       ROUND(AVG(Booking_Amount), 2) AS Average_Booking_Amount
FROM Hotel_Bookings
GROUP BY Customer_ID, Customer_Name;


-- Q2
-- Show each hotel city's total bookings
-- and total booking revenue.
--
-- Return:
-- Hotel_City
-- Total_Bookings
-- Total_Booking_Revenue

SELECT Hotel_City,
	   COUNT(Booking_ID) AS Total_Bookings,
       SUM(Booking_Amount) AS Total_Booking_Revenue
FROM Hotel_Bookings
GROUP BY Hotel_City;


-- Q3
-- Find the top 3 customers by total booking amount.
--
-- Return:
-- Customer_ID
-- Customer_Name
-- Total_Booking_Amount

WITH CTE AS (
	SELECT Customer_ID, Customer_Name,
		   SUM(Booking_Amount) AS Total_Booking_Amount
	FROM Hotel_Bookings
    GROUP BY Customer_ID, Customer_Name
),
CTE2 AS (
	SELECT *,
		   RANK() OVER(ORDER BY Total_Booking_Amount DESC) AS Rnk
	FROM CTE
)
SELECT Customer_ID, Customer_Name, Total_Booking_Amount
FROM CTE2
WHERE Rnk <= 3;


-- Q4
-- Find customers who made a booking within 2 days
-- of their previous booking.
--
-- Return:
-- Customer_ID
-- Customer_Name

WITH CTE AS (
	SELECT Customer_ID, Customer_Name, Booking_Date,
		   LAG(Booking_Date) OVER(PARTITION BY Customer_ID
           ORDER BY Booking_Date, Booking_ID) AS Previous
	FROM Hotel_Bookings
)
SELECT DISTINCT Customer_ID, Customer_Name
FROM CTE
WHERE Previous IS NOT NULL AND
DATEDIFF(Booking_Date, Previous) <= 2;


-- Q5 (COHORT ANALYSIS)
-- For each cohort month, find:
-- total customers
-- and total booking revenue generated by those customers.
--
-- Definition:
-- A customer's cohort month is the month of
-- their first booking date.
--
-- Return:
-- Cohort_Month
-- Total_Customers
-- Total_Booking_Revenue

WITH CTE AS (
	SELECT Customer_ID,
		   MIN(Booking_Date) AS First_Booking_Date
	FROM Hotel_Bookings
    GROUP BY Customer_ID
),
CTE2 AS (
	SELECT *,
		   DATE_FORMAT(First_Booking_Date, '%Y-%m') AS Cohort_Month
	FROM CTE
)
SELECT Cohort_Month,
	   COUNT(DISTINCT C.Customer_ID) AS Total_Customers,
	   SUM(H.Booking_Amount) AS Total_Booking_Revenue
FROM CTE2 C
INNER JOIN Hotel_Bookings H
	ON C.Customer_ID = H.Customer_ID
GROUP BY Cohort_Month;


-- BONUS (GAP & ISLAND)
-- Find the start date and end date of each customer's
-- longest booking streak.
--
-- Return:
-- Customer_ID
-- Customer_Name
-- Longest_Streak
-- Start_Date
-- End_Date
--
-- Note:
-- Ignore duplicate booking dates if a customer
-- has multiple bookings on the same day.
--
-- If multiple streaks have the same length,
-- return the most recent streak.


WITH CTE AS (
	SELECT DISTINCT Customer_ID, Customer_Name, Booking_Date
    FROM Hotel_Bookings
),
CTE2 AS (
	SELECT *,
		   ROW_NUMBER() OVER(PARTITION BY Customer_ID
           ORDER BY Booking_Date) AS RN
	FROM CTE
),
CTE3 AS (
	SELECT *,
		   DATE_SUB(Booking_Date, INTERVAL RN DAY) AS GK
	FROM CTE2
),
CTE4 AS (
	SELECT Customer_ID, Customer_Name,
		   COUNT(*) AS Streak,
           MIN(Booking_Date) AS Start_Date,
           MAX(Booking_Date) AS End_Date
	FROM CTE3
    GROUP BY Customer_ID, Customer_Name, GK
),
CTE5 AS (
	SELECT *,
		   ROW_NUMBER() OVER(PARTITION BY Customer_ID
           ORDER BY Streak DESC, End_Date DESC) AS Row_Num
	FROM CTE4
)
SELECT Customer_ID, Customer_Name, Streak AS Longest_Streak,
	   Start_Date, End_Date
FROM CTE5
WHERE Row_Num = 1;