USE Daily_SQL;

-- DATASET

CREATE TABLE Course_Enrollments (
    Enrollment_ID INT,
    Student_ID INT,
    Student_Name VARCHAR(50),
    Enrollment_Date DATE,
    Course_Category VARCHAR(50),
    Fee_Amount INT
);

INSERT INTO Course_Enrollments 
VALUES	(1,101,'Alice','2024-01-01','SQL',5000),
		(2,101,'Alice','2024-01-02','Python',4000),
		(3,101,'Alice','2024-01-03','SQL',3000),
		(4,101,'Alice','2024-01-08','Power BI',6000),

		(5,102,'Bob','2024-01-01','Python',7000),
		(6,102,'Bob','2024-01-05','SQL',2500),
		(7,102,'Bob','2024-01-06','Excel',3500),

		(8,103,'Charlie','2024-01-02','SQL',8000),
		(9,103,'Charlie','2024-01-03','Python',2000),
		(10,103,'Charlie','2024-01-04','Power BI',3000),
		(11,103,'Charlie','2024-01-05','SQL',4000),

		(12,104,'David','2024-01-01','Excel',4500),
		(13,104,'David','2024-01-08','Excel',1500),

		(14,105,'Emma','2024-01-03','Power BI',9000),
		(15,105,'Emma','2024-01-04','SQL',5000),
		(16,105,'Emma','2024-01-05','Python',3500);
        

SELECT *
FROM Course_Enrollments;


-- Q1
-- Show each student's total enrollments,
-- total fees paid, and average fee amount.
--
-- Return:
-- Student_ID
-- Student_Name
-- Total_Enrollments
-- Total_Fees_Paid
-- Average_Fee_Amount

SELECT Student_ID, Student_Name,
	   COUNT(Enrollment_ID) AS Total_Enrollments,
       SUM(Fee_Amount) AS Total_Fees_Paid,
       ROUND(AVG(Fee_Amount), 2) AS Average_Fee_Amount
FROM Course_Enrollments
GROUP BY Student_ID, Student_Name;


-- Q2
-- Show each course category's total enrollments
-- and total fee revenue.
--
-- Return:
-- Course_Category
-- Total_Enrollments
-- Total_Fee_Revenue

SELECT Course_Category,
	   COUNT(Enrollment_ID) AS Total_Enrollments,
       SUM(Fee_Amount) AS Total_Fees_Paid
FROM Course_Enrollments
GROUP BY Course_Category;


-- Q3
-- Find the top 3 students by total fees paid.
--
-- Return:
-- Student_ID
-- Student_Name
-- Total_Fees_Paid

WITH CTE AS (
	SELECT Student_ID, Student_Name,
		   SUM(Fee_Amount) AS Total_Fees_Paid
	FROM Course_Enrollments
	GROUP BY Student_ID, Student_Name
),
CTE2 AS (
	SELECT *,
		   DENSE_RANK() OVER(ORDER BY Total_Fees_Paid DESC) AS D_Rank
	FROM CTE
)
SELECT Student_ID, Student_Name, Total_Fees_Paid
FROM CTE2
WHERE D_Rank <= 3;


-- Q4
-- Find students who enrolled within 2 days
-- of their previous enrollment.
--
-- Return:
-- Student_ID
-- Student_Name

WITH CTE AS (
	SELECT Student_ID, Student_Name, Enrollment_Date,
		   LAG(Enrollment_Date) OVER(PARTITION BY Student_ID
           ORDER BY Enrollment_Date, Enrollment_ID) AS Previous
	FROM Course_Enrollments
)
SELECT DISTINCT Student_ID, Student_Name
FROM CTE
WHERE Previous IS NOT NULL
AND DATEDIFF(Enrollment_Date, Previous) <= 2;


-- Q5 (COHORT ANALYSIS)
-- For each cohort month, find:
-- total students
-- and total fee revenue generated by those students.
--
-- Definition:
-- A student's cohort month is the month of
-- their first enrollment date.
--
-- Return:
-- Cohort_Month
-- Total_Students
-- Total_Fee_Revenue

WITH CTE AS (
	SELECT Student_ID,
		   MIN(Enrollment_Date) AS First_Enrollment_Date
    FROM Course_Enrollments
    GROUP BY Student_ID
),
CTE2 AS (
	SELECT *,
		   DATE_FORMAT(First_Enrollment_Date, '%Y-%m') AS Cohort_Month
	FROM CTE
)
SELECT Cohort_Month,
	   COUNT(DISTINCT E.Student_ID) AS Total_Students,
	   SUM(E.Fee_Amount) AS Total_Fee_Revenue
FROM CTE2 C
INNER JOIN Course_Enrollments E
	ON C.Student_ID = E.Student_ID
GROUP BY Cohort_Month;


-- BONUS (GAP & ISLAND)
-- Find students whose current enrollment streak
-- is at least 3 days.
--
-- Return:
-- Student_ID
-- Student_Name
-- Current_Streak
-- Start_Date
-- End_Date
--
-- Definition:
-- Current streak = streak containing the student's
-- most recent enrollment date.
--
-- Note:
-- Ignore duplicate enrollment dates if a student
-- has multiple enrollments on the same day.

WITH CTE AS (
	SELECT DISTINCT Student_ID, Student_Name, Enrollment_Date
    FROM Course_Enrollments
),
CTE2 AS (
	SELECT *,
		   ROW_NUMBER() OVER(PARTITION BY Student_ID
           ORDER BY Enrollment_Date) AS RN
	FROM CTE
),
CTE3 AS (
	SELECT *,
		   DATE_SUB(Enrollment_Date, INTERVAL RN DAY) AS GK
	FROM CTE2
),
CTE4 AS (
	SELECT Student_ID, Student_Name,
		   COUNT(*) AS Streak,
           MIN(Enrollment_Date) AS Start_Date,
           MAX(Enrollment_Date) AS End_Date
	FROM CTE3
    GROUP BY Student_ID, Student_Name, GK
),
CTE5 AS (
	SELECT *,
		   DENSE_RANK() OVER(PARTITION BY Student_ID
           ORDER BY End_Date DESC) AS D_Rank
	FROM CTE4
)
SELECT Student_ID, Student_Name, Streak AS Current_Streak,
	   Start_Date, End_Date
FROM CTE5
WHERE D_Rank = 1
AND Streak >= 3;