USE Daily_SQL;

-- TOPIC: Online Grocery Orders

CREATE TABLE Grocery_Orders (
    Order_ID INT,
    Customer_ID INT,
    Customer_Name VARCHAR(50),
    Product_Category VARCHAR(50),
    Order_Date DATE,
    Order_Amount DECIMAL(10,2)
);

INSERT INTO Grocery_Orders 
VALUES	(1, 101, 'Alice',   'Fruits',      '2025-01-01', 120),
		(2, 101, 'Alice',   'Vegetables',  '2025-01-02', 80),
		(3, 101, 'Alice',   'Dairy',       '2025-01-03', 150),
		(4, 101, 'Alice',   'Snacks',      '2025-01-10', 200),

		(5, 102, 'Bob',     'Fruits',      '2025-01-05', 90),
		(6, 102, 'Bob',     'Beverages',   '2025-01-06', 110),
		(7, 102, 'Bob',     'Snacks',      '2025-01-08', 130),
		(8, 102, 'Bob',     'Dairy',       '2025-01-09', 170),

		(9, 103, 'Charlie', 'Vegetables',  '2025-02-01', 100),
		(10,103, 'Charlie', 'Vegetables',  '2025-02-02', 140),
		(11,103, 'Charlie', 'Fruits',      '2025-02-03', 180),
		(12,103, 'Charlie', 'Snacks',      '2025-02-04', 220),

		(13,104, 'David',   'Dairy',       '2025-02-10', 160),
		(14,104, 'David',   'Dairy',       '2025-02-10', 90),
		(15,104, 'David',   'Beverages',   '2025-02-11', 120),
		(16,104, 'David',   'Snacks',      '2025-02-15', 250),

		(17,105, 'Emma',    'Fruits',      '2025-03-01', 130),
		(18,105, 'Emma',    'Vegetables',  '2025-03-02', 170),
		(19,105, 'Emma',    'Dairy',       '2025-03-03', 200),
		(20,105, 'Emma',    'Snacks',      '2025-03-04', 150),

		(21,106, 'Frank',   'Beverages',   '2025-03-10', 300),
		(22,106, 'Frank',   'Snacks',      '2025-03-11', 100),
		(23,106, 'Frank',   'Fruits',      '2025-03-12', 180),
		(24,106, 'Frank',   'Vegetables',  '2025-03-20', 220),

		(25,107, 'Grace',   'Dairy',       '2025-04-01', 140),
		(26,107, 'Grace',   'Beverages',   '2025-04-02', 160),
		(27,107, 'Grace',   'Snacks',      '2025-04-03', 190),
		(28,107, 'Grace',   'Snacks',      '2025-04-03', 210),

		(29,108, 'Henry',   'Fruits',      '2025-04-15', 110),
		(30,108, 'Henry',   'Vegetables',  '2025-04-16', 130),
		(31,108, 'Henry',   'Dairy',       '2025-04-17', 170),
		(32,108, 'Henry',   'Beverages',   '2025-04-18', 190);


SELECT *
FROM Grocery_Orders;

-- Q1
-- Show each customer's total orders,
-- total amount spent, and average order amount.
--
-- Return:
-- Customer_ID
-- Customer_Name
-- Total_Orders
-- Total_Amount_Spent
-- Average_Order_Amount

SELECT Customer_ID, Customer_Name,
	   COUNT(Order_ID) AS Total_Orders,
       SUM(Order_Amount) AS Total_Amount_Spent,
       ROUND(AVG(Order_Amount), 2) AS Average_Order_Amount
FROM Grocery_Orders
GROUP BY Customer_ID, Customer_Name;


-- Q2
-- Show each product category's total orders
-- and total revenue.
--
-- Return:
-- Product_Category
-- Total_Orders
-- Total_Revenue

SELECT Product_Category,
	   COUNT(Order_ID) AS Total_Orders,
       SUM(Order_Amount) AS Total_Revenue
FROM Grocery_Orders
GROUP BY Product_Category;


-- Q3
-- Find the top 3 customers by total amount spent.
--
-- Return:
-- Customer_ID
-- Customer_Name
-- Total_Amount_Spent

WITH CTE AS (
	SELECT Customer_ID, Customer_Name,
		   SUM(Order_Amount) AS Total_Amount_Spent
	FROM Grocery_Orders
	GROUP BY Customer_ID, Customer_Name
),
CTE2 AS (
	SELECT *,
		   DENSE_RANK() OVER(ORDER BY Total_Amount_Spent DESC) AS D_Rank
	FROM CTE
)
SELECT Customer_ID, Customer_Name, Total_Amount_Spent
FROM CTE2
WHERE D_Rank <= 3;


-- Q4
-- Find customers who placed an order within 2 days
-- of their previous order.
--
-- Return:
-- Customer_ID
-- Customer_Name

WITH CTE AS (
	SELECT Customer_ID, Customer_Name, Order_Date,
		   LAG(Order_Date) OVER(PARTITION BY Customer_ID
           ORDER BY Order_Date, Order_ID) AS Previous
	FROM Grocery_Orders
)
SELECT DISTINCT Customer_ID, Customer_Name
FROM CTE
WHERE Previous IS NOT NULL
AND DATEDIFF(Order_Date, Previous) <= 2;


-- Q5 (COHORT ANALYSIS)
-- For each cohort month, find:
-- total customers
-- and total revenue generated by those customers.
--
-- Definition:
-- A customer's cohort month is the month of
-- their first order date.
--
-- Return:
-- Cohort_Month
-- Total_Customers
-- Total_Revenue

WITH CTE AS (
	SELECT Customer_ID,
		   MIN(Order_Date) AS First_Order_Date
	FROM Grocery_Orders
    GROUP BY Customer_ID
),
CTE2 AS (
	SELECT *,
		   DATE_FORMAT(First_Order_Date, '%Y-%m') AS Cohort_Month
	FROM CTE
)
SELECT Cohort_Month,
	   COUNT(DISTINCT G.Customer_ID) AS Total_Customers,
       SUM(G.Order_Amount) AS Total_Revenue
FROM CTE2 C
INNER JOIN Grocery_Orders G
	ON C.Customer_ID = G.Customer_ID
GROUP BY Cohort_Month;


-- BONUS (GAP & ISLAND)
-- Find the start date and end date of each customer's
-- longest order streak.
--
-- Return:
-- Customer_ID
-- Customer_Name
-- Longest_Streak
-- Start_Date
-- End_Date
--
-- Note:
-- Ignore duplicate order dates if a customer
-- has multiple orders on the same day.
--
-- If multiple streaks have the same length,
-- return the most recent streak.

WITH CTE AS (
	SELECT DISTINCT Customer_ID, Customer_Name, Order_Date
    FROM Grocery_Orders
),
CTE2 AS (
	SELECT *,
		   ROW_NUMBER() OVER(PARTITION BY Customer_ID
           ORDER BY Order_Date) AS RN
	FROM CTE
),
CTE3 AS (
	SELECT *,
		   DATE_SUB(Order_Date, INTERVAL RN DAY) AS GK
	FROM CTE2
),
CTE4 AS (
	SELECT Customer_ID, Customer_Name,
		   COUNT(*) AS Streak,
           MIN(Order_Date) AS Start_Date,
           MAX(Order_Date) AS End_Date
	FROM CTE3
    GROUP BY Customer_ID, Customer_Name, GK
),
CTE5 AS (
	SELECT *,
		   ROW_NUMBER() OVER(PARTITION BY Customer_ID
           ORDER BY Streak DESC, End_Date DESC) AS Row_Num
	FROM CTE4
)
SELECT Customer_ID, Customer_Name, Streak AS Longest_Streak,
	   Start_Date, End_Date
FROM CTE5
WHERE Row_Num = 1;