USE Daily_SQL;

-- TOPIC: Movie Ticket Bookings


CREATE TABLE Movie_Ticket_Bookings (
    Booking_ID INT,
    Customer_ID INT,
    Customer_Name VARCHAR(50),
    Movie_Genre VARCHAR(30),
    Booking_Date DATE,
    Ticket_Amount DECIMAL(10,2)
);

INSERT INTO Movie_Ticket_Bookings 
VALUES	(1,101,'Alice','Action','2025-01-01',250),
		(2,101,'Alice','Comedy','2025-01-02',300),
		(3,101,'Alice','Drama','2025-01-03',280),
		(4,101,'Alice','Action','2025-01-10',400),

		(5,102,'Bob','Comedy','2025-01-05',220),
		(6,102,'Bob','Comedy','2025-01-06',180),
		(7,102,'Bob','Action','2025-01-08',350),
		(8,102,'Bob','Drama','2025-01-09',250),

		(9,103,'Charlie','Drama','2025-02-01',320),
		(10,103,'Charlie','Action','2025-02-02',280),
		(11,103,'Charlie','Comedy','2025-02-03',300),
		(12,103,'Charlie','Action','2025-02-04',450),

		(13,104,'David','Drama','2025-02-10',200),
		(14,104,'David','Drama','2025-02-10',180),
		(15,104,'David','Comedy','2025-02-11',240),
		(16,104,'David','Action','2025-02-15',500),

		(17,105,'Emma','Action','2025-03-01',350),
		(18,105,'Emma','Comedy','2025-03-02',250),
		(19,105,'Emma','Drama','2025-03-03',300),
		(20,105,'Emma','Action','2025-03-04',400),

		(21,106,'Frank','Comedy','2025-03-10',600),
		(22,106,'Frank','Action','2025-03-11',350),
		(23,106,'Frank','Drama','2025-03-12',300),
		(24,106,'Frank','Comedy','2025-03-20',450),

		(25,107,'Grace','Drama','2025-04-01',280),
		(26,107,'Grace','Action','2025-04-02',320),
		(27,107,'Grace','Comedy','2025-04-03',350),
		(28,107,'Grace','Comedy','2025-04-03',220),

		(29,108,'Henry','Action','2025-04-15',270),
		(30,108,'Henry','Drama','2025-04-16',310),
		(31,108,'Henry','Comedy','2025-04-17',290),
		(32,108,'Henry','Action','2025-04-18',330);
        
SELECT *
FROM Movie_Ticket_Bookings;


-- Q1
-- Show each customer's total bookings,
-- total ticket amount, and average ticket amount.
--
-- Return:
-- Customer_ID
-- Customer_Name
-- Total_Bookings
-- Total_Ticket_Amount
-- Average_Ticket_Amount

SELECT Customer_ID, Customer_Name,
	   COUNT(Booking_ID) AS Total_Bookings,
       SUM(Ticket_Amount) AS Total_Ticket_Amount,
       ROUND(AVG(Ticket_Amount), 2) AS Average_Ticket_Amount
FROM Movie_Ticket_Bookings
GROUP BY Customer_ID, Customer_Name;


-- Q2
-- Show each movie genre's total bookings
-- and total ticket revenue.
--
-- Return:
-- Movie_Genre
-- Total_Bookings
-- Total_Ticket_Revenue

SELECT Movie_Genre,
	   COUNT(Booking_ID) AS Total_Bookings,
       SUM(Ticket_Amount) AS Total_Ticket_Revenue
FROM Movie_Ticket_Bookings
GROUP BY Movie_Genre;


-- Q3
-- Find the top 3 customers by total ticket amount.
--
-- Return:
-- Customer_ID
-- Customer_Name
-- Total_Ticket_Amount

WITH CTE AS (
	SELECT Customer_ID, Customer_Name,
       SUM(Ticket_Amount) AS Total_Ticket_Amount
	FROM Movie_Ticket_Bookings
    GROUP BY Customer_ID, Customer_Name
),
CTE2 AS (
	SELECT *,
		   DENSE_RANK() OVER(ORDER BY Total_Ticket_Amount DESC) AS D_Rank
	FROM CTE
)
SELECT Customer_ID, Customer_Name, Total_Ticket_Amount
FROM CTE2
WHERE D_Rank <= 3;


-- Q4
-- Find customers who made a booking within 2 days
-- of their previous booking.
--
-- Return:
-- Customer_ID
-- Customer_Name

WITH CTE AS (
	SELECT Customer_ID, Customer_Name, Booking_Date,
		   LAG(Booking_Date) OVER(PARTITION BY Customer_ID
		   ORDER BY Booking_Date, Booking_ID) AS Previous
	FROM Movie_Ticket_Bookings
)
SELECT DISTINCT Customer_ID, Customer_Name
FROM CTE
WHERE Previous IS NOT NULL
AND DATEDIFF(Booking_Date, Previous) <= 2;


-- Q5 (COHORT ANALYSIS)
-- For each cohort month, find:
-- total customers
-- and total ticket revenue generated by those customers.
--
-- Definition:
-- A customer's cohort month is the month of
-- their first booking date.
--
-- Return:
-- Cohort_Month
-- Total_Customers
-- Total_Ticket_Revenue

WITH CTE AS (
	SELECT Customer_ID,
		   MIN(Booking_Date) AS First_Booking_Date
	FROM Movie_Ticket_Bookings
    GROUP BY Customer_ID
),
CTE2 AS (
	SELECT *,
		   DATE_FORMAT(First_Booking_Date, '%Y-%m') AS Cohort_Month
	FROM CTE
)
SELECT Cohort_Month,
	   COUNT(DISTINCT M.Customer_ID) AS Total_Customers,
       SUM(M.Ticket_Amount) AS Total_Ticket_Revenue
FROM CTE2 C
INNER JOIN Movie_Ticket_Bookings M
	ON C.Customer_ID = M.Customer_ID
GROUP BY Cohort_Month;


-- BONUS (GAP & ISLAND)
-- Find customers whose current booking streak
-- is at least 3 days.
--
-- Return:
-- Customer_ID
-- Customer_Name
-- Current_Streak
-- Start_Date
-- End_Date
--
-- Definition:
-- Current streak = streak containing the customer's
-- most recent booking date.
--
-- Note:
-- Ignore duplicate booking dates if a customer
-- has multiple bookings on the same day.

WITH CTE AS (
	SELECT DISTINCT Customer_ID, Customer_Name, Booking_Date
    FROM Movie_Ticket_Bookings
),
CTE2 AS (
	SELECT *,
		   ROW_NUMBER() OVER(PARTITION BY Customer_ID
           ORDER BY Booking_Date) AS RN
	FROM CTE
),
CTE3 AS (
	SELECT *,
		   DATE_SUB(Booking_Date, INTERVAL RN DAY) AS GK
	FROM CTE2
),
CTE4 AS (
	SELECT Customer_ID, Customer_Name,
		   COUNT(*) AS Streak,
           MIN(Booking_Date) AS Start_Date,
           MAX(Booking_Date) AS End_Date
	FROM CTE3
    GROUP BY Customer_ID, Customer_Name, GK
),
CTE5 AS (
	SELECT *,
		   ROW_NUMBER() OVER(PARTITION BY Customer_ID
           ORDER BY End_Date DESC) AS Row_Num
	FROM CTE4
)
SELECT Customer_ID, Customer_Name, Streak AS Current_Streak,
	   Start_Date, End_Date
FROM CTE5
WHERE Row_Num = 1
AND Streak >= 3;