USE Daily_SQL;


-- TOPIC: Pharmacy Sales


CREATE TABLE Pharmacy_Sales (
    Sale_ID INT,
    Customer_ID INT,
    Customer_Name VARCHAR(50),
    Medicine_Category VARCHAR(30),
    Sale_Date DATE,
    Sale_Amount DECIMAL(10,2)
);

INSERT INTO Pharmacy_Sales 
VALUES	(1,101,'Alice','Pain Relief','2025-01-01',250),
		(2,101,'Alice','Vitamins','2025-01-02',300),
		(3,101,'Alice','Pain Relief','2025-01-03',280),
		(4,101,'Alice','Antibiotics','2025-01-10',400),

		(5,102,'Bob','Vitamins','2025-01-05',220),
		(6,102,'Bob','Pain Relief','2025-01-06',180),
		(7,102,'Bob','Antibiotics','2025-01-08',350),
		(8,102,'Bob','Pain Relief','2025-01-09',250),

		(9,103,'Charlie','Antibiotics','2025-02-01',320),
		(10,103,'Charlie','Pain Relief','2025-02-02',280),
		(11,103,'Charlie','Vitamins','2025-02-03',300),
		(12,103,'Charlie','Pain Relief','2025-02-04',450),

		(13,104,'David','Antibiotics','2025-02-10',200),
		(14,104,'David','Antibiotics','2025-02-10',180),
		(15,104,'David','Vitamins','2025-02-11',240),
		(16,104,'David','Pain Relief','2025-02-15',500),

		(17,105,'Emma','Pain Relief','2025-03-01',350),
		(18,105,'Emma','Vitamins','2025-03-02',250),
		(19,105,'Emma','Antibiotics','2025-03-03',300),
		(20,105,'Emma','Pain Relief','2025-03-04',400),

		(21,106,'Frank','Vitamins','2025-03-10',600),
		(22,106,'Frank','Pain Relief','2025-03-11',350),
		(23,106,'Frank','Antibiotics','2025-03-12',300),
		(24,106,'Frank','Vitamins','2025-03-20',450),

		(25,107,'Grace','Antibiotics','2025-04-01',280),
		(26,107,'Grace','Pain Relief','2025-04-02',320),
		(27,107,'Grace','Vitamins','2025-04-03',350),
		(28,107,'Grace','Vitamins','2025-04-03',220),

		(29,108,'Henry','Pain Relief','2025-04-15',270),
		(30,108,'Henry','Antibiotics','2025-04-16',310),
		(31,108,'Henry','Vitamins','2025-04-17',290),
		(32,108,'Henry','Pain Relief','2025-04-18',330);
        
SELECT *
FROM Pharmacy_Sales;

-- Q1
-- Show each customer's total sales records,
-- total sale amount, and average sale amount.
--
-- Return:
-- Customer_ID
-- Customer_Name
-- Total_Sales_Records
-- Total_Sale_Amount
-- Average_Sale_Amount

SELECT Customer_ID, Customer_Name,
	   COUNT(Sale_ID) AS Total_Sales_Records,
       SUM(Sale_Amount) AS Total_Sale_Amount,
       ROUND(AVG(Sale_Amount), 2) AS Average_Sale_Amount
FROM Pharmacy_Sales
GROUP BY Customer_ID, Customer_Name;


-- Q2
-- Show each medicine category's total sales records
-- and total revenue.
--
-- Return:
-- Medicine_Category
-- Total_Sales_Records
-- Total_Revenue

SELECT Medicine_Category,
	   COUNT(Sale_ID) AS Total_Sales_Records,
       SUM(Sale_Amount) AS Total_Revenue
FROM Pharmacy_Sales
GROUP BY Medicine_Category;


-- Q3
-- Find the top 3 customers by total sale amount.
--
-- Return:
-- Customer_ID
-- Customer_Name
-- Total_Sale_Amount

WITH CTE AS (
	SELECT Customer_ID, Customer_Name,
		   SUM(Sale_Amount) AS Total_Sale_Amount
	FROM Pharmacy_Sales
	GROUP BY Customer_ID, Customer_Name
),
CTE2 AS (
	SELECT *,
		   DENSE_RANK() OVER(ORDER BY Total_Sale_Amount DESC) AS D_Rank
	FROM CTE
)
SELECT Customer_ID, Customer_Name, Total_Sale_Amount
FROM CTE2
WHERE D_Rank <= 3;


-- Q4
-- Find customers who made a purchase within 2 days
-- of their previous purchase.
--
-- Return:
-- Customer_ID
-- Customer_Name

WITH CTE AS (
	SELECT Customer_ID, Customer_Name, Sale_Date,
		   LAG(Sale_Date) OVER(PARTITION BY Customer_ID
           ORDER BY Sale_Date, Sale_ID) AS Previous
	FROM Pharmacy_Sales
),
CTE2 AS (
	SELECT *,
		   DATEDIFF(Sale_Date, Previous) AS Days_Gap
	FROM CTE
)
SELECT DISTINCT Customer_ID, Customer_Name
FROM CTE2
WHERE Days_Gap <= 2;


-- Q5 (COHORT ANALYSIS)
-- For each cohort month, find:
-- total customers
-- and total revenue generated by those customers.
--
-- Definition:
-- A customer's cohort month is the month of
-- their first purchase date.
--
-- Return:
-- Cohort_Month
-- Total_Customers
-- Total_Revenue

WITH CTE AS (
	SELECT Customer_ID,
		   MIN(Sale_Date) AS First_Purchase_Date
	FROM Pharmacy_Sales
    GROUP BY Customer_ID
),
CTE2 AS (
	SELECT *,
		   DATE_FORMAT(First_Purchase_Date, '%Y-%m') AS Cohort_Month
	FROM CTE
)
SELECT Cohort_Month,
	   COUNT(DISTINCT P.Customer_ID) AS Total_Customers,
       SUM(P.Sale_Amount) AS Total_Revenue
FROM CTE2 C
INNER JOIN Pharmacy_Sales P
	ON P.Customer_ID = C.Customer_ID
GROUP BY Cohort_Month;


-- BONUS (GAP & ISLAND)
-- Find customers whose longest purchase streak
-- is at least 4 days.
--
-- Return:
-- Customer_ID
-- Customer_Name
-- Longest_Streak
--
-- Note:
-- Ignore duplicate purchase dates if a customer
-- has multiple purchases on the same day.
--
-- If multiple streaks exist,
-- consider only the longest streak.

WITH CTE AS (
	SELECT DISTINCT Customer_ID, Customer_Name, Sale_Date
    FROM Pharmacy_Sales
),
CTE2 AS (
	SELECT *,
		   ROW_NUMBER() OVER(PARTITION BY Customer_ID
           ORDER BY Sale_Date) AS RN
	FROM CTE
),
CTE3 AS (
	SELECT *,
		   DATE_SUB(Sale_Date, INTERVAL RN DAY) AS GK
	FROM CTE2
),
CTE4 AS (
	SELECT Customer_ID, Customer_Name,
		   COUNT(*) AS Streak
	FROM CTE3
    GROUP BY Customer_ID, Customer_Name, GK
)
SELECT Customer_ID, Customer_Name,
	   MAX(Streak) AS Longest_Streak
FROM CTE4
GROUP BY Customer_ID, Customer_Name
HAVING MAX(Streak) >= 4;