USE Daily_SQL;


-- TOPIC: Car Rental Bookings


CREATE TABLE Car_Rental_Bookings (
    Booking_ID INT,
    Customer_ID INT,
    Customer_Name VARCHAR(50),
    Car_Type VARCHAR(30),
    Booking_Date DATE,
    Rental_Amount DECIMAL(10,2)
);

INSERT INTO Car_Rental_Bookings 
VALUES	(1,101,'Alice','SUV','2025-01-01',1200),
		(2,101,'Alice','Sedan','2025-01-02',900),
		(3,101,'Alice','SUV','2025-01-03',1100),
		(4,101,'Alice','Luxury','2025-01-10',2500),

		(5,102,'Bob','Sedan','2025-01-05',800),
		(6,102,'Bob','SUV','2025-01-06',1300),
		(7,102,'Bob','Luxury','2025-01-08',2200),
		(8,102,'Bob','SUV','2025-01-09',1400),

		(9,103,'Charlie','Luxury','2025-02-01',3000),
		(10,103,'Charlie','SUV','2025-02-02',1500),
		(11,103,'Charlie','Sedan','2025-02-03',1000),
		(12,103,'Charlie','SUV','2025-02-04',1700),

		(13,104,'David','Sedan','2025-02-10',700),
		(14,104,'David','Sedan','2025-02-10',600),
		(15,104,'David','SUV','2025-02-11',1200),
		(16,104,'David','Luxury','2025-02-15',2600),

		(17,105,'Emma','SUV','2025-03-01',1400),
		(18,105,'Emma','Sedan','2025-03-02',900),
		(19,105,'Emma','Luxury','2025-03-03',2800),
		(20,105,'Emma','SUV','2025-03-04',1600),

		(21,106,'Frank','Luxury','2025-03-10',3200),
		(22,106,'Frank','SUV','2025-03-11',1500),
		(23,106,'Frank','Sedan','2025-03-12',1000),
		(24,106,'Frank','Luxury','2025-03-20',3500),

		(25,107,'Grace','SUV','2025-04-01',1300),
		(26,107,'Grace','Luxury','2025-04-02',2700),
		(27,107,'Grace','Sedan','2025-04-03',800),
		(28,107,'Grace','Sedan','2025-04-03',900),

		(29,108,'Henry','SUV','2025-04-15',1400),
		(30,108,'Henry','Luxury','2025-04-16',2900),
		(31,108,'Henry','Sedan','2025-04-17',1000),
		(32,108,'Henry','SUV','2025-04-18',1500);

SELECT *
FROM Car_Rental_Bookings;

-- Q1
-- Show each customer's total bookings,
-- total rental amount, and average rental amount.
--
-- Return:
-- Customer_ID
-- Customer_Name
-- Total_Bookings
-- Total_Rental_Amount
-- Average_Rental_Amount

SELECT Customer_ID, Customer_Name,
	   COUNT(Booking_ID) AS Total_Bookings,
       SUM(Rental_Amount) AS Total_Rental_Amount,
       ROUND(AVG(Rental_Amount), 2) AS Average_Rental_Amount
FROM Car_Rental_Bookings
GROUP BY Customer_ID, Customer_Name;


-- Q2
-- Show each car type's total bookings
-- and total rental revenue.
--
-- Return:
-- Car_Type
-- Total_Bookings
-- Total_Rental_Revenue

SELECT Car_Type,
	   COUNT(Booking_ID) AS Total_Bookings,
       SUM(Rental_Amount) AS Total_Rental_Revenue
FROM Car_Rental_Bookings
GROUP BY Car_Type;


-- Q3
-- Find the top 3 customers by total rental amount.
--
-- Return:
-- Customer_ID
-- Customer_Name
-- Total_Rental_Amount

WITH CTE AS (
	SELECT Customer_ID, Customer_Name,
		   SUM(Rental_Amount) AS Total_Rental_Amount
	FROM Car_Rental_Bookings
	GROUP BY Customer_ID, Customer_Name
),
CTE2 AS (
	SELECT *,
		   DENSE_RANK() OVER(ORDER BY Total_Rental_Amount DESC) AS D_Rank
	FROM CTE
)
SELECT Customer_ID, Customer_Name, Total_Rental_Amount
FROM CTE2
WHERE D_Rank <= 3;


-- Q4
-- Find customers who made a booking within 2 days
-- of their previous booking.
--
-- Return:
-- Customer_ID
-- Customer_Name

WITH CTE AS (
	SELECT Customer_ID, Customer_Name, Booking_Date,
		   LAG(Booking_Date) OVER(PARTITION BY Customer_ID
           ORDER BY Booking_Date, Booking_ID) AS Previous
	FROM Car_Rental_Bookings
),
CTE2 AS (
	SELECT *,
		   DATEDIFF(Booking_Date, Previous) AS Days_Gap
	FROM CTE
)
SELECT DISTINCT Customer_ID, Customer_Name
FROM CTE2
WHERE Days_Gap <= 2;


-- Q5 (COHORT ANALYSIS)
-- For each cohort month, find:
-- total customers
-- and total rental revenue generated by those customers.
--
-- Definition:
-- A customer's cohort month is the month of
-- their first booking date.
--
-- Return:
-- Cohort_Month
-- Total_Customers
-- Total_Rental_Revenue

WITH CTE AS (
	SELECT Customer_ID,
		   MIN(Booking_Date) AS First_Booking_Date
	FROM Car_Rental_Bookings
    GROUP BY Customer_ID
),
CTE2 AS (
	SELECT *,
		   DATE_FORMAT(First_Booking_Date, '%Y-%m') AS Cohort_Month
	FROM CTE
)
SELECT Cohort_Month,
	   COUNT(DISTINCT R.Customer_ID) AS Total_Customers,
       SUM(R.Rental_Amount) AS Total_Rental_Revenue
FROM CTE2 C
INNER JOIN Car_Rental_Bookings R
	ON R.Customer_ID = C.Customer_ID
GROUP BY Cohort_Month;


-- BONUS (GAP & ISLAND)
-- Find the start date and end date of each customer's
-- current booking streak.
--
-- Return:
-- Customer_ID
-- Customer_Name
-- Current_Streak
-- Start_Date
-- End_Date
--
-- Definition:
-- Current streak = streak containing the customer's
-- most recent booking date.
--
-- Note:
-- Ignore duplicate booking dates if a customer
-- has multiple bookings on the same day.
--
-- Return only customers whose Current_Streak >= 3.

WITH CTE AS (
	SELECT DISTINCT Customer_ID, Customer_Name, Booking_Date
    FROM Car_Rental_Bookings
),
CTE2 AS (
	SELECT *,
		   ROW_NUMBER() OVER(PARTITION BY Customer_ID
           ORDER BY Booking_Date) AS RN
	FROM CTE
),
CTE3 AS (
	SELECT *,
		   DATE_SUB(Booking_Date, INTERVAL RN DAY) AS GK
	FROM CTE2
),
CTE4 AS (
	SELECT Customer_ID, Customer_Name,
		   COUNT(*) AS Streak,
           MIN(Booking_Date) AS Start_Date,
           MAX(Booking_Date) AS End_Date
	FROM CTE3
    GROUP BY Customer_ID, Customer_Name, GK
),
CTE5 AS (
	SELECT *,
		   ROW_NUMBER() OVER(PARTITION BY Customer_ID
           ORDER BY End_Date DESC) AS Row_Num
	FROM CTE4
)
SELECT Customer_ID, Customer_Name, Streak AS Current_Streak,
	   Start_Date, End_Date
FROM CTE5
WHERE Row_Num = 1
AND Streak >= 3;