USE Daily_SQL;

-- TOPIC: Airline Flight Bookings


CREATE TABLE Airline_Flight_Bookings (
    Booking_ID INT,
    Customer_ID INT,
    Customer_Name VARCHAR(50),
    Flight_Class VARCHAR(20),
    Booking_Date DATE,
    Ticket_Amount DECIMAL(10,2)
);

INSERT INTO Airline_Flight_Bookings 
VALUES	(1,101,'Alice','Economy','2025-01-01',4500),
		(2,101,'Alice','Business','2025-01-02',12000),
		(3,101,'Alice','Economy','2025-01-03',4800),
		(4,101,'Alice','First Class','2025-01-10',22000),

		(5,102,'Bob','Economy','2025-01-05',4200),
		(6,102,'Bob','Economy','2025-01-06',4300),
		(7,102,'Bob','Business','2025-01-08',12500),
		(8,102,'Bob','Economy','2025-01-09',4600),

		(9,103,'Charlie','First Class','2025-02-01',25000),
		(10,103,'Charlie','Business','2025-02-02',13500),
		(11,103,'Charlie','Economy','2025-02-03',4700),
		(12,103,'Charlie','Economy','2025-02-04',4900),

		(13,104,'David','Economy','2025-02-10',4100),
		(14,104,'David','Economy','2025-02-10',3900),
		(15,104,'David','Business','2025-02-11',11800),
		(16,104,'David','First Class','2025-02-15',21000),

		(17,105,'Emma','Business','2025-03-01',13000),
		(18,105,'Emma','Economy','2025-03-02',4500),
		(19,105,'Emma','Business','2025-03-03',12800),
		(20,105,'Emma','Economy','2025-03-04',4700),

		(21,106,'Frank','First Class','2025-03-10',26000),
		(22,106,'Frank','Business','2025-03-11',14000),
		(23,106,'Frank','Economy','2025-03-12',5000),
		(24,106,'Frank','First Class','2025-03-20',28000),

		(25,107,'Grace','Economy','2025-04-01',4600),
		(26,107,'Grace','Business','2025-04-02',13200),
		(27,107,'Grace','Economy','2025-04-03',4500),
		(28,107,'Grace','Economy','2025-04-03',4700),

		(29,108,'Henry','Business','2025-04-15',12600),
		(30,108,'Henry','First Class','2025-04-16',23500),
		(31,108,'Henry','Economy','2025-04-17',4800),
		(32,108,'Henry','Business','2025-04-18',12900);

SELECT *
FROM Airline_Flight_Bookings;


-- Q1
-- Show each customer's total bookings,
-- total ticket amount, and average ticket amount.
--
-- Return:
-- Customer_ID
-- Customer_Name
-- Total_Bookings
-- Total_Ticket_Amount
-- Average_Ticket_Amount

SELECT Customer_ID, Customer_Name,
	   COUNT(Booking_ID) AS Total_Bookings,
	   SUM(Ticket_Amount) AS Total_Ticket_Amount,
       ROUND(AVG(Ticket_Amount), 2) AS Average_Ticket_Amount
FROM Airline_Flight_Bookings
GROUP BY Customer_ID, Customer_Name;


-- Q2
-- Show each flight class's total bookings
-- and total ticket revenue.
--
-- Return:
-- Flight_Class
-- Total_Bookings
-- Total_Ticket_Revenue

SELECT Flight_Class,
	   COUNT(Booking_ID) AS Total_Bookings,
	   SUM(Ticket_Amount) AS Total_Ticket_Revenue
FROM Airline_Flight_Bookings
GROUP BY Flight_Class;


-- Q3
-- Find the top 3 customers by total ticket amount.
--
-- Return:
-- Customer_ID
-- Customer_Name
-- Total_Ticket_Amount

WITH CTE AS (
	SELECT Customer_ID, Customer_Name,
		   SUM(Ticket_Amount) AS Total_Ticket_Amount
	FROM Airline_Flight_Bookings
	GROUP BY Customer_ID, Customer_Name
),
CTE2 AS (
	SELECT *,
		   DENSE_RANK() OVER(ORDER BY Total_Ticket_Amount DESC) AS D_Rank
	FROM CTE
)
SELECT Customer_ID, Customer_Name, Total_Ticket_Amount
FROM CTE2
WHERE D_Rank <= 3;


-- Q4
-- Find customers who made a booking within 2 days
-- of their previous booking.
--
-- Return:
-- Customer_ID
-- Customer_Name

WITH CTE AS (
	SELECT Customer_ID, Customer_Name, Booking_Date,
		   LAG(Booking_Date) OVER(PARTITION BY Customer_ID
           ORDER BY Booking_Date, Booking_ID) AS Previous
	FROM Airline_Flight_Bookings
)
SELECT DISTINCT Customer_ID, Customer_Name
FROM CTE
WHERE Previous IS NOT NULL
AND DATEDIFF(Booking_Date, Previous) <= 2;


-- Q5 (COHORT ANALYSIS)
-- For each cohort month, find:
-- total customers
-- and total ticket revenue generated by those customers.
--
-- Definition:
-- A customer's cohort month is the month of
-- their first booking date.
--
-- Return:
-- Cohort_Month
-- Total_Customers
-- Total_Ticket_Revenue

WITH CTE AS (
	SELECT Customer_ID,
		   MIN(Booking_Date) AS First_Booking_Date
	FROM Airline_Flight_Bookings
    GROUP BY Customer_ID
),
CTE2 AS (
	SELECT *,
		   DATE_FORMAT(First_Booking_Date, '%Y-%m') AS Cohort_Month
	FROM CTE
)
SELECT Cohort_Month,
	   COUNT(DISTINCT A.Customer_ID) AS Total_Customers,
       SUM(A.Ticket_Amount) AS Total_Ticket_Revenue
FROM CTE2 C
INNER JOIN Airline_Flight_Bookings A
	ON C.Customer_ID = A.Customer_ID
GROUP BY Cohort_Month;


-- BONUS (GAP & ISLAND)
-- Find the start date and end date of each customer's
-- longest booking streak.
--
-- Return:
-- Customer_ID
-- Customer_Name
-- Longest_Streak
-- Start_Date
-- End_Date
--
-- Note:
-- Ignore duplicate booking dates if a customer
-- has multiple bookings on the same day.
--
-- If multiple streaks have the same length,
-- return the most recent streak.

WITH CTE AS (
	SELECT DISTINCT Customer_ID, Customer_Name, Booking_Date
    FROM Airline_Flight_Bookings
),
CTE2 AS (
	SELECT *,
		   ROW_NUMBER() OVER(PARTITION BY Customer_ID
           ORDER BY Booking_Date) AS RN
	FROM CTE
),
CTE3 AS (
	SELECT *,
		   DATE_SUB(Booking_Date, INTERVAL RN DAY) AS GK
	FROM CTE2
),
CTE4 AS (
	SELECT Customer_ID, Customer_Name,
		   COUNT(*) AS Streak,
           MIN(Booking_Date) AS Start_Date,
           MAX(Booking_Date) AS End_Date
	FROM CTE3
	GROUP BY Customer_ID, Customer_Name, GK
),
CTE5 AS (
	SELECT *,
		   ROW_NUMBER() OVER(PARTITION BY Customer_ID
           ORDER BY Streak DESC, End_Date DESC) AS Row_Num
	FROM CTE4
)
SELECT Customer_ID, Customer_Name, Streak AS Longest_Streak,
	   Start_Date, End_Date
FROM CTE5
WHERE Row_Num = 1;