USE Daily_SQL;

-- TOPIC: Gym Membership Payments


CREATE TABLE Gym_Membership_Payments (
    Payment_ID INT,
    Member_ID INT,
    Member_Name VARCHAR(50),
    Membership_Type VARCHAR(30),
    Payment_Date DATE,
    Payment_Amount DECIMAL(10,2)
);

INSERT INTO Gym_Membership_Payments 
VALUES	(1,101,'Alice','Monthly','2025-01-01',1200),
		(2,101,'Alice','Monthly','2025-01-02',1200),
		(3,101,'Alice','Quarterly','2025-01-03',3000),
		(4,101,'Alice','Annual','2025-01-10',10000),

		(5,102,'Bob','Monthly','2025-01-05',1200),
		(6,102,'Bob','Monthly','2025-01-06',1200),
		(7,102,'Bob','Quarterly','2025-01-08',3000),
		(8,102,'Bob','Monthly','2025-01-09',1200),

		(9,103,'Charlie','Annual','2025-02-01',10000),
		(10,103,'Charlie','Quarterly','2025-02-02',3000),
		(11,103,'Charlie','Monthly','2025-02-03',1200),
		(12,103,'Charlie','Monthly','2025-02-04',1200),

		(13,104,'David','Monthly','2025-02-10',1200),
		(14,104,'David','Monthly','2025-02-10',1200),
		(15,104,'David','Quarterly','2025-02-11',3000),
		(16,104,'David','Annual','2025-02-15',10000),

		(17,105,'Emma','Quarterly','2025-03-01',3000),
		(18,105,'Emma','Monthly','2025-03-02',1200),
		(19,105,'Emma','Quarterly','2025-03-03',3000),
		(20,105,'Emma','Monthly','2025-03-04',1200),

		(21,106,'Frank','Annual','2025-03-10',10000),
		(22,106,'Frank','Quarterly','2025-03-11',3000),
		(23,106,'Frank','Monthly','2025-03-12',1200),
		(24,106,'Frank','Annual','2025-03-20',10000),

		(25,107,'Grace','Monthly','2025-04-01',1200),
		(26,107,'Grace','Quarterly','2025-04-02',3000),
		(27,107,'Grace','Monthly','2025-04-03',1200),
		(28,107,'Grace','Monthly','2025-04-03',1200),

		(29,108,'Henry','Quarterly','2025-04-15',3000),
		(30,108,'Henry','Annual','2025-04-16',10000),
		(31,108,'Henry','Monthly','2025-04-17',1200),
		(32,108,'Henry','Quarterly','2025-04-18',3000);

SELECT *
FROM Gym_Membership_Payments;


-- Q1
-- Show each member's total payment records,
-- total payment amount, and average payment amount.
--
-- Return:
-- Member_ID
-- Member_Name
-- Total_Payment_Records
-- Total_Payment_Amount
-- Average_Payment_Amount

SELECT Member_ID, Member_Name,
	   COUNT(Payment_ID) AS Total_Payment_Records,
       SUM(Payment_Amount) AS Total_Payment_Amount,
       ROUND(AVG(Payment_Amount), 2) AS Average_Payment_Amount
FROM Gym_Membership_Payments
GROUP BY Member_ID, Member_Name;


-- Q2
-- Show each membership type's total payment records
-- and total revenue.
--
-- Return:
-- Membership_Type
-- Total_Payment_Records
-- Total_Revenue

SELECT Membership_Type,
	   COUNT(Payment_ID) AS Total_Payment_Records,
       SUM(Payment_Amount) AS Total_Revenue
FROM Gym_Membership_Payments
GROUP BY Membership_Type;


-- Q3
-- Find the top 3 members by total payment amount.
--
-- Return:
-- Member_ID
-- Member_Name
-- Total_Payment_Amount

WITH CTE AS (
	SELECT Member_ID, Member_Name,
		   SUM(Payment_Amount) AS Total_Payment_Amount
	FROM Gym_Membership_Payments
	GROUP BY Member_ID, Member_Name
),
CTE2 AS (
	SELECT *,
		   DENSE_RANK() OVER(ORDER BY Total_Payment_Amount DESC) AS D_Rank
	FROM CTE
)
SELECT Member_ID, Member_Name, Total_Payment_Amount
FROM CTE2
WHERE D_Rank <= 3;


-- Q4
-- Find members who made a payment within 2 days
-- of their previous payment.
--
-- Return:
-- Member_ID
-- Member_Name

WITH CTE AS (
	SELECT Member_ID, Member_Name, Payment_Date,
		   LAG(Payment_Date) OVER(PARTITION BY Member_ID
           ORDER BY Payment_Date, Payment_ID) AS Previous
	FROM Gym_Membership_Payments
),
CTE2 AS (
	SELECT *,
		   DATEDIFF(Payment_Date, Previous) AS Days_Gap
	FROM CTE
)
SELECT DISTINCT Member_ID, Member_Name
FROM CTE2
WHERE Days_Gap <= 2;


-- Q5 (COHORT ANALYSIS)
-- For each cohort month, find:
-- total members
-- and total payment revenue generated by those members.
--
-- Definition:
-- A member's cohort month is the month of
-- their first payment date.
--
-- Return:
-- Cohort_Month
-- Total_Members
-- Total_Payment_Revenue

WITH CTE AS (
	SELECT Member_ID,
		   MIN(Payment_Date) AS First_Payment_Date
	FROM Gym_Membership_Payments
	GROUP BY Member_ID
),
CTE2 AS (
	SELECT *,
		   DATE_FORMAT(First_Payment_Date, '%Y-%m') AS Cohort_Month
	FROM CTE
)
SELECT Cohort_Month,
	   COUNT(DISTINCT G.Member_ID) AS Total_Members,
       SUM(G.Payment_Amount) AS Total_Payment_Revenue
FROM CTE2 C
INNER JOIN Gym_Membership_Payments G
	ON C.Member_ID = G.Member_ID
GROUP BY Cohort_Month;


-- BONUS (GAP & ISLAND)
-- Find members whose longest payment streak
-- is at least 4 days.
--
-- Return:
-- Member_ID
-- Member_Name
-- Longest_Streak
--
-- Note:
-- Ignore duplicate payment dates if a member
-- has multiple payments on the same day.
--
-- If multiple streaks exist,
-- consider only the longest streak.

WITH CTE AS (
	SELECT DISTINCT Member_ID, Member_Name, Payment_Date
    FROM Gym_Membership_Payments
),
CTE2 AS (
	SELECT *,
		   ROW_NUMBER() OVER(PARTITION BY Member_ID
           ORDER BY Payment_Date) AS RN
	FROM CTE
),
CTE3 AS (
	SELECT *,
		   DATE_SUB(Payment_Date, INTERVAL RN DAY) AS GK
	FROM CTE2
),
CTE4 AS (
	SELECT Member_ID, Member_Name,
		   COUNT(*) AS Streak
	FROM CTE3
    GROUP BY Member_ID, Member_Name, GK
)
SELECT Member_ID, Member_Name,
	   MAX(Streak) AS Longest_Streak
FROM CTE4
GROUP BY Member_ID, Member_Name
HAVING MAX(Streak) >= 4;