USE Daily_SQL;

-- TOPIC: Online Food Subscription Service


CREATE TABLE Meal_Subscriptions (
    Subscription_ID INT,
    Customer_ID INT,
    Customer_Name VARCHAR(50),
    Plan_Type VARCHAR(30),
    Subscription_Date DATE,
    Amount_Paid DECIMAL(10,2)
);

INSERT INTO Meal_Subscriptions 
VALUES	(1,101,'Alice','Weekly','2025-01-01',799),
		(2,101,'Alice','Weekly','2025-01-02',799),
		(3,101,'Alice','Monthly','2025-01-03',2499),
		(4,101,'Alice','Annual','2025-01-10',19999),

		(5,102,'Bob','Weekly','2025-01-05',799),
		(6,102,'Bob','Weekly','2025-01-06',799),
		(7,102,'Bob','Monthly','2025-01-08',2499),
		(8,102,'Bob','Weekly','2025-01-09',799),

		(9,103,'Charlie','Annual','2025-02-01',19999),
		(10,103,'Charlie','Monthly','2025-02-02',2499),
		(11,103,'Charlie','Weekly','2025-02-03',799),
		(12,103,'Charlie','Weekly','2025-02-04',799),

		(13,104,'David','Weekly','2025-02-10',799),
		(14,104,'David','Weekly','2025-02-10',799),
		(15,104,'David','Monthly','2025-02-11',2499),
		(16,104,'David','Annual','2025-02-15',19999),

		(17,105,'Emma','Monthly','2025-03-01',2499),
		(18,105,'Emma','Weekly','2025-03-02',799),
		(19,105,'Emma','Monthly','2025-03-03',2499),
		(20,105,'Emma','Weekly','2025-03-04',799),

		(21,106,'Frank','Annual','2025-03-10',19999),
		(22,106,'Frank','Monthly','2025-03-11',2499),
		(23,106,'Frank','Weekly','2025-03-12',799),
		(24,106,'Frank','Annual','2025-03-20',19999),

		(25,107,'Grace','Weekly','2025-04-01',799),
		(26,107,'Grace','Monthly','2025-04-02',2499),
		(27,107,'Grace','Weekly','2025-04-03',799),
		(28,107,'Grace','Weekly','2025-04-03',799),

		(29,108,'Henry','Monthly','2025-04-15',2499),
		(30,108,'Henry','Annual','2025-04-16',19999),
		(31,108,'Henry','Weekly','2025-04-17',799),
		(32,108,'Henry','Monthly','2025-04-18',2499);

SELECT *
FROM Meal_Subscriptions;


-- Q1
-- Show each customer's total subscriptions,
-- total amount paid, and average amount paid.
--
-- Return:
-- Customer_ID
-- Customer_Name
-- Total_Subscriptions
-- Total_Amount_Paid
-- Average_Amount_Paid

SELECT Customer_ID, Customer_Name,
	   COUNT(Subscription_ID) AS Total_Subscriptions,
       SUM(Amount_Paid) AS Total_Amount_Paid,
       ROUND(AVG(Amount_Paid), 2) AS Average_Amount_Paid
FROM Meal_Subscriptions
GROUP BY Customer_ID, Customer_Name;


-- Q2
-- Show each plan type's total subscriptions
-- and total revenue.
--
-- Return:
-- Plan_Type
-- Total_Subscriptions
-- Total_Revenue

SELECT Plan_Type,
	   COUNT(Subscription_ID) AS Total_Subscriptions,
       SUM(Amount_Paid) AS Total_Revenue
FROM Meal_Subscriptions
GROUP BY Plan_Type;


-- Q3
-- Find the top 3 customers by total amount paid.
--
-- Return:
-- Customer_ID
-- Customer_Name
-- Total_Amount_Paid

WITH CTE AS (
	SELECT Customer_ID, Customer_Name,
		   SUM(Amount_Paid) AS Total_Amount_Paid
	FROM Meal_Subscriptions
	GROUP BY Customer_ID, Customer_Name
),
CTE2 AS (
	SELECT *,
		   DENSE_RANK() OVER(ORDER BY Total_Amount_Paid DESC) AS D_Rank
	FROM CTE
)
SELECT Customer_ID, Customer_Name, Total_Amount_Paid
FROM CTE2
WHERE D_Rank <= 3;


-- Q4
-- Find customers who made a subscription within 2 days
-- of their previous subscription.
--
-- Return:
-- Customer_ID
-- Customer_Name

WITH CTE AS (
	SELECT Customer_ID, Customer_Name, Subscription_Date,
		   LAG(Subscription_Date) OVER(PARTITION BY Customer_ID
           ORDER BY Subscription_Date, Subscription_ID) AS Previous
	FROM Meal_Subscriptions
)
SELECT DISTINCT Customer_ID, Customer_Name
FROM CTE
WHERE Previous IS NOT NULL
AND DATEDIFF(Subscription_Date, Previous) <= 2;


-- Q5 (COHORT ANALYSIS)
-- For each cohort month, find:
-- total customers
-- and total revenue generated by those customers.
--
-- Definition:
-- A customer's cohort month is the month of
-- their first subscription date.
--
-- Return:
-- Cohort_Month
-- Total_Customers
-- Total_Revenue

WITH CTE AS (
	SELECT Customer_ID,
		   MIN(Subscription_Date) AS First_Subscription_Date
	FROM Meal_Subscriptions
    GROUP BY Customer_ID
),
CTE2 AS (
	SELECT *,
		   DATE_FORMAT(First_Subscription_Date, '%Y-%m') AS Cohort_Month
	FROM CTE
)
SELECT Cohort_Month,
	   COUNT(DISTINCT M.Customer_ID) AS Total_Customers,
       SUM(M.Amount_Paid) AS Total_Revenue
FROM CTE2 C
INNER JOIN Meal_Subscriptions M
	ON C.Customer_ID = M.Customer_ID
GROUP BY Cohort_Month;


-- BONUS (GAP & ISLAND)
-- Find the start date and end date of each customer's
-- current subscription streak.
--
-- Return:
-- Customer_ID
-- Customer_Name
-- Current_Streak
-- Start_Date
-- End_Date
--
-- Definition:
-- Current streak = streak containing the customer's
-- most recent subscription date.
--
-- Note:
-- Ignore duplicate subscription dates if a customer
-- has multiple subscriptions on the same day.
--
-- Return only customers whose Current_Streak >= 3.

WITH CTE AS (
	SELECT DISTINCT Customer_ID, Customer_Name, Subscription_Date
    FROM Meal_Subscriptions
),
CTE2 AS (
	SELECT *,
		   ROW_NUMBER() OVER(PARTITION BY Customer_ID
           ORDER BY Subscription_Date) AS RN
	FROM CTE
),
CTE3 AS (
	SELECT *,
		   DATE_SUB(Subscription_Date, INTERVAL RN DAY) AS GK
	FROM CTE2
),
CTE4 AS (
	SELECT Customer_ID, Customer_Name,
		   COUNT(*) AS Streak,
           MIN(Subscription_Date) AS Start_Date,
           MAX(Subscription_Date) AS End_Date
	FROM CTE3
    GROUP BY Customer_ID, Customer_Name, GK
),
CTE5 AS (
	SELECT *,
		   ROW_NUMBER() OVER(PARTITION BY Customer_ID
           ORDER BY End_Date DESC) AS Row_Num
	FROM CTE4
)
SELECT Customer_ID, Customer_Name, Streak AS Current_Streak,
	   Start_Date, End_Date
FROM CTE5
WHERE Row_Num = 1
AND Streak >= 3;