USE Daily_SQL;

-- TOPIC: Online Pharmacy Orders


CREATE TABLE Online_Pharmacy_Orders (
    Order_ID INT,
    Customer_ID INT,
    Customer_Name VARCHAR(50),
    Medicine_Category VARCHAR(30),
    Order_Date DATE,
    Order_Amount DECIMAL(10,2)
);

INSERT INTO Online_Pharmacy_Orders 
VALUES	(1,101,'Alice','Pain Relief','2025-01-01',450),
		(2,101,'Alice','Pain Relief','2025-01-02',380),
		(3,101,'Alice','Vitamins','2025-01-03',920),
		(4,101,'Alice','Diabetes','2025-01-10',1650),

		(5,102,'Bob','Pain Relief','2025-01-05',510),
		(6,102,'Bob','Pain Relief','2025-01-06',420),
		(7,102,'Bob','Personal Care','2025-01-08',980),
		(8,102,'Bob','Pain Relief','2025-01-09',450),

		(9,103,'Charlie','Diabetes','2025-02-01',1800),
		(10,103,'Charlie','Vitamins','2025-02-02',950),
		(11,103,'Charlie','Pain Relief','2025-02-03',430),
		(12,103,'Charlie','Pain Relief','2025-02-04',410),

		(13,104,'David','Pain Relief','2025-02-10',500),
		(14,104,'David','Pain Relief','2025-02-10',520),
		(15,104,'David','Personal Care','2025-02-11',870),
		(16,104,'David','Diabetes','2025-02-15',1720),

		(17,105,'Emma','Vitamins','2025-03-01',910),
		(18,105,'Emma','Pain Relief','2025-03-02',390),
		(19,105,'Emma','Vitamins','2025-03-03',980),
		(20,105,'Emma','Pain Relief','2025-03-04',420),

		(21,106,'Frank','Diabetes','2025-03-10',1850),
		(22,106,'Frank','Personal Care','2025-03-11',990),
		(23,106,'Frank','Pain Relief','2025-03-12',460),
		(24,106,'Frank','Diabetes','2025-03-20',1920),

		(25,107,'Grace','Pain Relief','2025-04-01',470),
		(26,107,'Grace','Vitamins','2025-04-02',960),
		(27,107,'Grace','Pain Relief','2025-04-03',450),
		(28,107,'Grace','Pain Relief','2025-04-03',480),

		(29,108,'Henry','Personal Care','2025-04-15',890),
		(30,108,'Henry','Diabetes','2025-04-16',1780),
		(31,108,'Henry','Pain Relief','2025-04-17',440),
		(32,108,'Henry','Vitamins','2025-04-18',930);

SELECT *
FROM Online_Pharmacy_Orders;


-- Q1
-- Show each customer's total orders,
-- total order amount, and average order amount.
--
-- Return:
-- Customer_ID
-- Customer_Name
-- Total_Orders
-- Total_Order_Amount
-- Average_Order_Amount

SELECT Customer_ID, Customer_Name,
	   COUNT(Order_ID) AS Total_Orders,
       SUM(Order_Amount) AS Total_Order_Amount,
       ROUND(AVG(Order_Amount), 2) AS Average_Order_Amount
FROM Online_Pharmacy_Orders
GROUP BY Customer_ID, Customer_Name;


-- Q2
-- Show each medicine category's total orders
-- and total revenue.
--
-- Return:
-- Medicine_Category
-- Total_Orders
-- Total_Revenue

SELECT Medicine_Category,
	   COUNT(Order_ID) AS Total_Orders,
       SUM(Order_Amount) AS Total_Revenue
FROM Online_Pharmacy_Orders
GROUP BY Medicine_Category;


-- Q3
-- Find the top 3 customers by total order amount.
--
-- Return:
-- Customer_ID
-- Customer_Name
-- Total_Order_Amount

WITH CTE AS (
	SELECT Customer_ID, Customer_Name,
		   SUM(Order_Amount) AS Total_Order_Amount
	FROM Online_Pharmacy_Orders
	GROUP BY Customer_ID, Customer_Name
),
CTE2 AS (
	SELECT *,
		   DENSE_RANK() OVER(ORDER BY Total_Order_Amount DESC) AS D_Rank
	FROM CTE
)
SELECT Customer_ID, Customer_Name, Total_Order_Amount
FROM CTE2
WHERE D_Rank <= 3;


-- Q4
-- Find customers who placed an order within 2 days
-- of their previous order.
--
-- Return:
-- Customer_ID
-- Customer_Name

WITH CTE AS (
	SELECT Customer_ID, Customer_Name, Order_Date,
		   LAG(Order_Date) OVER(PARTITION BY Customer_ID
           ORDER BY Order_Date, Order_ID) AS Previous
	FROM Online_Pharmacy_Orders
)
SELECT DISTINCT Customer_ID, Customer_Name
FROM CTE
WHERE Previous IS NOT NULL
AND DATEDIFF(Order_Date, Previous) <= 2;


-- Q5 (COHORT ANALYSIS)
-- For each cohort month, find:
-- total customers
-- and total order revenue generated by those customers.
--
-- Definition:
-- A customer's cohort month is the month of
-- their first order date.
--
-- Return:
-- Cohort_Month
-- Total_Customers
-- Total_Order_Revenue

WITH CTE AS (
	SELECT Customer_ID,
		   MIN(Order_Date) AS First_Order_Date
	FROM Online_Pharmacy_Orders
    GROUP BY Customer_ID
),
CTE2 AS (
	SELECT *,
		   DATE_FORMAT(First_Order_Date, '%Y-%m') AS Cohort_Month
	FROM CTE
)
SELECT Cohort_Month,
	   COUNT(DISTINCT P.Customer_ID) AS Total_Customers,
       SUM(P.Order_Amount) AS Total_Order_Revenue
FROM CTE2 C
INNER JOIN Online_Pharmacy_Orders P
	ON C.Customer_ID = P.Customer_ID
GROUP BY Cohort_Month;


-- BONUS (GAP & ISLAND)
-- Find the start date and end date of each customer's
-- longest order streak.
--
-- Return:
-- Customer_ID
-- Customer_Name
-- Longest_Streak
-- Start_Date
-- End_Date
--
-- Note:
-- Ignore duplicate order dates if a customer
-- has multiple orders on the same day.
--
-- If multiple streaks have the same length,
-- return the most recent streak.

WITH CTE AS (
	SELECT DISTINCT Customer_ID, Customer_Name, Order_Date
    FROM Online_Pharmacy_Orders
),
CTE2 AS (
	SELECT *,
		   ROW_NUMBER() OVER(PARTITION BY Customer_ID
           ORDER BY Order_Date) AS RN
	FROM CTE
),
CTE3 AS (
	SELECT *,
		   DATE_SUB(Order_Date, INTERVAL RN DAY) AS GK
	FROM CTE2
),
CTE4 AS (
	SELECT Customer_ID, Customer_Name,
		   COUNT(*) AS Streak,
           MIN(Order_Date) AS Start_Date,
           MAX(Order_Date) AS End_Date
	FROM CTE3
    GROUP BY Customer_ID, Customer_Name, GK
),
CTE5 AS (
	SELECT *,
		   ROW_NUMBER() OVER(PARTITION BY Customer_ID
           ORDER BY Streak DESC, End_Date DESC) AS Row_Num
	FROM  CTE4
)
SELECT Customer_ID, Customer_Name, Streak AS Longest_Streak,
	   Start_Date, End_Date
FROM CTE5
WHERE Row_Num = 1;