USE Daily_SQL;

-- Topic: Insurance Claims

CREATE TABLE Insurance_Claims (
    Claim_ID INT PRIMARY KEY,
    Customer_ID INT,
    Customer_Name VARCHAR(50),
    Policy_Type VARCHAR(30),
    Claim_Date DATE,
    Claim_Amount DECIMAL(10,2)
);

INSERT INTO Insurance_Claims
VALUES	(101, 1, 'Alice',   'Health',   '2025-01-02', 1200.00),
		(102, 1, 'Alice',   'Health',   '2025-01-03', 800.00),
		(103, 1, 'Alice',   'Vehicle',  '2025-01-04', 1500.00),
		(104, 1, 'Alice',   'Health',   '2025-02-10', 950.00),

		(105, 2, 'Bob',     'Vehicle',  '2025-01-05', 2500.00),
		(106, 2, 'Bob',     'Vehicle',  '2025-01-08', 1800.00),
		(107, 2, 'Bob',     'Home',     '2025-03-01', 3200.00),

		(108, 3, 'Charlie', 'Health',   '2025-02-01', 700.00),
		(109, 3, 'Charlie', 'Health',   '2025-02-02', 900.00),
		(110, 3, 'Charlie', 'Health',   '2025-02-03', 1000.00),
		(111, 3, 'Charlie', 'Vehicle',  '2025-04-10', 2200.00),

		(112, 4, 'David',   'Home',     '2025-03-05', 4500.00),
		(113, 4, 'David',   'Home',     '2025-03-06', 2000.00),
		(114, 4, 'David',   'Health',   '2025-03-20', 1100.00),

		(115, 5, 'Eva',     'Vehicle',  '2025-01-15', 1700.00),
		(116, 5, 'Eva',     'Vehicle',  '2025-01-16', 1600.00),
		(117, 5, 'Eva',     'Vehicle',  '2025-01-17', 1800.00),
		(118, 5, 'Eva',     'Home',     '2025-02-20', 2800.00),

		(119, 6, 'Frank',   'Health',   '2025-04-01', 900.00),
		(120, 6, 'Frank',   'Health',   '2025-04-05', 1000.00);
        
SELECT *
FROM Insurance_Claims;

-- Q1
-- Show each customer's total claims,
-- total claim amount, and average claim amount.
--
-- Return:
-- Customer_ID
-- Customer_Name
-- Total_Claims
-- Total_Claim_Amount
-- Average_Claim_Amount

SELECT Customer_ID, Customer_Name,
	   COUNT(Claim_ID) AS Total_Claims,
       SUM(Claim_Amount) AS Total_Claim_Amount,
       ROUND(AVG(Claim_Amount), 2) AS Average_Claim_Amount
FROM Insurance_Claims
GROUP BY Customer_ID, Customer_Name;


-- Q2
-- Show each policy type's total claims
-- and total claim amount.
--
-- Return:
-- Policy_Type
-- Total_Claims
-- Total_Claim_Amount

SELECT Policy_Type,
	   COUNT(Claim_ID) AS Total_Claims,
       SUM(Claim_Amount) AS Total_Claim_Amount
FROM Insurance_Claims
GROUP BY Policy_Type;


-- Q3
-- Find the top 3 customers by total claim amount.
--
-- Return:
-- Customer_ID
-- Customer_Name
-- Total_Claim_Amount

WITH CTE AS (
	SELECT Customer_ID, Customer_Name,
		   SUM(Claim_Amount) AS Total_Claim_Amount
	FROM Insurance_Claims
	GROUP BY Customer_ID, Customer_Name
),
CTE2 AS (
	SELECT *,
		   DENSE_RANK() OVER(ORDER BY Total_Claim_Amount DESC) AS D_Rank
	FROM CTE
)
SELECT Customer_ID, Customer_Name, Total_Claim_Amount
FROM CTE2
WHERE D_Rank <= 3;


-- Q4
-- Find customers who submitted a claim within 2 days
-- of their previous claim.
--
-- Return:
-- Customer_ID
-- Customer_Name

WITH CTE AS (
	SELECT Customer_ID, Customer_Name, Claim_Date,
		   LAG(Claim_Date) OVER(PARTITION BY Customer_ID
           ORDER BY Claim_Date, Claim_ID) AS Previous
	FROM Insurance_Claims
)
SELECT DISTINCT Customer_ID, Customer_Name
FROM CTE
WHERE Previous IS NOT NULL
AND DATEDIFF(Claim_Date, Previous) <= 2;


-- Q5 (COHORT ANALYSIS)
-- For each cohort month, find:
-- total customers
-- and total claim amount generated by those customers.
--
-- Definition:
-- A customer's cohort month is the month of
-- their first claim date.
--
-- Return:
-- Cohort_Month
-- Total_Customers
-- Total_Claim_Amount

WITH CTE AS (
	SELECT Customer_ID,
		   MIN(Claim_Date) AS First_Claim_Date
	FROM Insurance_Claims
    GROUP BY Customer_ID
),
CTE2 AS (
	SELECT *,
		   DATE_FORMAT(First_Claim_Date, '%Y-%m') AS Cohort_Month
	FROM CTE
)
SELECT Cohort_Month,
	   COUNT(DISTINCT I.Customer_ID) AS Total_Customers,
       SUM(I.Claim_Amount) AS Total_Claim_Amount
FROM CTE2 C
INNER JOIN Insurance_Claims I
	ON C.Customer_ID = I.Customer_ID
GROUP BY Cohort_Month;


-- BONUS (GAP & ISLAND)
-- Find the start date and end date of each customer's
-- current claim streak.
--
-- Return:
-- Customer_ID
-- Customer_Name
-- Current_Streak
-- Start_Date
-- End_Date
--
-- Definition:
-- Current streak = streak containing the customer's
-- most recent claim date.
--
-- Note:
-- Ignore duplicate claim dates if a customer
-- has multiple claims on the same day.
--
-- Return only customers whose Current_Streak >= 3.

WITH CTE AS (
	SELECT DISTINCT Customer_ID, Customer_Name, Claim_Date
    FROM Insurance_Claims
),
CTE2 AS (
	SELECT *,
		   ROW_NUMBER() OVER(PARTITION BY Customer_ID
           ORDER BY Claim_Date) AS RN
	FROM CTE
),
CTE3 AS (
	SELECT *,
		   DATE_SUB(Claim_Date, INTERVAL RN DAY) AS GK
	FROM CTE2
),
CTE4 AS (
	SELECT Customer_ID, Customer_Name,
		   COUNT(*) AS Streak,
           MIN(Claim_Date) AS Start_Date,
           MAX(Claim_Date) AS End_Date
	FROM CTE3
    GROUP BY Customer_ID, Customer_Name, GK
),
CTE5 AS (
	SELECT *,
		   ROW_NUMBER() OVER(PARTITION BY Customer_ID
           ORDER BY End_Date DESC) AS Row_Num
	FROM CTE4
)
SELECT Customer_ID, Customer_Name, Streak AS Current_Streak,
	   Start_Date, End_Date
FROM CTE5
WHERE Row_Num = 1
AND Streak >= 3;