USE Daily_SQL;

-- Topic: Library Book Borrowings

CREATE TABLE Library_Book_Borrowings (
    Borrowing_ID INT PRIMARY KEY,
    Customer_ID INT,
    Customer_Name VARCHAR(50),
    Book_ID INT,
    Book_Title VARCHAR(100),
    Genre VARCHAR(30),
    Borrow_Date DATE,
    Return_Date DATE,
    Fine_Amount DECIMAL(10,2)
);

INSERT INTO Library_Book_Borrowings 
VALUES	(1,101,'Alice',201,'The Silent Forest','Fiction','2025-01-02','2025-01-08',0),
		(2,101,'Alice',202,'Deep Space','Sci-Fi','2025-01-03','2025-01-09',20),
		(3,101,'Alice',203,'SQL Basics','Education','2025-01-04','2025-01-10',0),
		(4,101,'Alice',204,'Mystery Lake','Mystery','2025-02-15','2025-02-20',10),

		(5,102,'Bob',205,'AI Revolution','Technology','2025-01-10','2025-01-18',50),
		(6,102,'Bob',206,'Ocean World','Science','2025-01-11','2025-01-17',0),
		(7,102,'Bob',207,'Galaxy Wars','Sci-Fi','2025-03-01','2025-03-06',0),

		(8,103,'Charlie',208,'Hidden Truth','Mystery','2025-02-01','2025-02-07',15),
		(9,103,'Charlie',209,'Python Guide','Education','2025-02-02','2025-02-08',0),
		(10,103,'Charlie',210,'World Atlas','Reference','2025-02-03','2025-02-10',25),
		(11,103,'Charlie',211,'History of Rome','History','2025-02-04','2025-02-12',0),

		(12,104,'David',212,'Modern Physics','Science','2025-01-20','2025-01-27',0),
		(13,104,'David',213,'Machine Learning','Technology','2025-03-05','2025-03-12',30),

		(14,105,'Eva',214,'Cooking 101','Lifestyle','2025-03-10','2025-03-15',0),
		(15,105,'Eva',215,'Healthy Living','Lifestyle','2025-03-11','2025-03-17',0),
		(16,105,'Eva',216,'Fitness Pro','Health','2025-03-12','2025-03-18',15),

		(17,106,'Frank',217,'Ancient Egypt','History','2025-01-05','2025-01-10',0),
		(18,106,'Frank',218,'The Lost City','Fiction','2025-01-06','2025-01-12',0),
		(19,106,'Frank',219,'Wild Nature','Science','2025-01-07','2025-01-14',10),
		(20,106,'Frank',220,'Space Mission','Sci-Fi','2025-01-08','2025-01-15',0);
        
SELECT *
FROM Library_Book_Borrowings;

-- Q1
-- Show each customer's total borrowings,
-- total fine amount, and average fine amount.
--
-- Return:
-- Customer_ID
-- Customer_Name
-- Total_Borrowings
-- Total_Fine_Amount
-- Average_Fine_Amount

SELECT Customer_ID, Customer_Name,
	   COUNT(Borrowing_ID) AS Total_Borrowings,
       SUM(Fine_Amount) AS Total_Fine_Amount,
       ROUND(AVG(Fine_Amount), 2) AS Average_Fine_Amount
FROM Library_Book_Borrowings
GROUP BY Customer_ID, Customer_Name;


-- Q2
-- Show each genre's total borrowings
-- and total fine collected.
--
-- Return:
-- Genre
-- Total_Borrowings
-- Total_Fine_Collected

SELECT Genre,
	   COUNT(Borrowing_ID) AS Total_Borrowings,
       SUM(Fine_Amount) AS Total_Fine_Collected
FROM Library_Book_Borrowings
GROUP BY Genre;


-- Q3
-- Find the top 3 customers by total fine amount.
--
-- Return:
-- Customer_ID
-- Customer_Name
-- Total_Fine_Amount

WITH CTE AS (
	SELECT Customer_ID, Customer_Name,
		   SUM(Fine_Amount) AS Total_Fine_Amount
	FROM Library_Book_Borrowings
	GROUP BY Customer_ID, Customer_Name
),
CTE2 AS (
	SELECT *,
		   DENSE_RANK() OVER(ORDER BY Total_Fine_Amount DESC) AS D_Rank
	FROM CTE
)
SELECT Customer_ID, Customer_Name, Total_Fine_Amount
FROM CTE2
WHERE D_Rank <= 3;


-- Q4
-- Find customers who borrowed a book within 2 days
-- of their previous borrowing.
--
-- Return:
-- Customer_ID
-- Customer_Name

WITH CTE AS (
	SELECT Customer_ID, Customer_Name, Borrow_Date,
		   LAG(Borrow_Date) OVER(PARTITION BY Customer_ID
           ORDER BY Borrow_Date, Borrowing_ID) AS Previous
	FROM Library_Book_Borrowings
)
SELECT DISTINCT Customer_ID, Customer_Name
FROM CTE
WHERE Previous IS NOT NULL
AND DATEDIFF(Borrow_Date, Previous) <= 2;


-- Q5 (COHORT ANALYSIS)
-- For each cohort month, find:
-- total customers
-- and total fine amount generated by those customers.
--
-- Definition:
-- A customer's cohort month is the month of
-- their first borrow date.
--
-- Return:
-- Cohort_Month
-- Total_Customers
-- Total_Fine_Amount

WITH CTE AS (
	SELECT Customer_ID,
		   MIN(Borrow_Date) AS First_Borrow_Date
	FROM Library_Book_Borrowings
    GROUP BY Customer_ID
),
CTE2 AS (
	SELECT *,
		   DATE_FORMAT(First_Borrow_Date, '%Y-%m') AS Cohort_Month
	FROM CTE
)
SELECT Cohort_Month,
	   COUNT(DISTINCT L.Customer_ID) AS Total_Customers,
       SUM(L.Fine_Amount) AS Total_Fine_Amount
FROM CTE2 C
INNER JOIN Library_Book_Borrowings L
	ON C.Customer_ID = L.Customer_ID
GROUP BY Cohort_Month;


-- BONUS (GAP & ISLAND)
-- Find the start date and end date of each customer's
-- longest borrowing streak.
--
-- Return:
-- Customer_ID
-- Customer_Name
-- Longest_Streak
-- Start_Date
-- End_Date
--
-- Note:
-- Ignore duplicate borrow dates if a customer
-- has multiple borrowings on the same day.
--
-- If multiple streaks have the same length,
-- return the most recent streak.

WITH CTE AS (
	SELECT DISTINCT Customer_ID, Customer_Name, Borrow_Date
    FROM Library_Book_Borrowings
),
CTE2 AS (
	SELECT *,
		   ROW_NUMBER() OVER(PARTITION BY Customer_ID
           ORDER BY Borrow_Date) AS RN
	FROM CTE
),
CTE3 AS (
	SELECT *,
		   DATE_SUB(Borrow_Date, INTERVAL RN DAY) AS GK
	FROM CTE2
),
CTE4 AS (
	SELECT Customer_ID, Customer_Name,
		   COUNT(*) AS Streak,
		   MIN(Borrow_Date) AS Start_Date,
           MAX(Borrow_Date) AS End_Date
	FROM CTE3
    GROUP BY Customer_ID, Customer_Name, GK
),
CTE5 AS (
	SELECT *,
		   ROW_NUMBER() OVER(PARTITION BY Customer_ID
           ORDER BY Streak DESC, End_Date DESC) AS Row_Num
	FROM CTE4
)
SELECT Customer_ID, Customer_Name, Streak AS Longest_Streak,
	   Start_Date, End_Date
FROM CTE5
WHERE Row_Num = 1;