USE Daily_SQL;

-- Topic : Streaming Service Activity

CREATE TABLE Streaming_Service_Activity (
    Activity_ID INT PRIMARY KEY,
    User_ID INT,
    User_Name VARCHAR(50),
    Subscription_Plan VARCHAR(20),
    Content_Genre VARCHAR(30),
    Watch_Date DATE,
    Watch_Minutes INT
);

INSERT INTO Streaming_Service_Activity
VALUES	(1,101,'Alice','Premium','Action','2026-01-01',120),
		(2,101,'Alice','Premium','Comedy','2026-01-02',90),
		(3,101,'Alice','Premium','Drama','2026-01-03',80),
		(4,101,'Alice','Premium','Action','2026-01-06',110),

		(5,102,'Bob','Basic','Comedy','2026-01-02',60),
		(6,102,'Bob','Basic','Comedy','2026-01-05',70),
		(7,102,'Bob','Basic','Action','2026-01-06',100),
		(8,102,'Bob','Basic','Drama','2026-01-07',95),

		(9,103,'Charlie','Standard','Drama','2026-01-03',130),
		(10,103,'Charlie','Standard','Drama','2026-01-04',125),
		(11,103,'Charlie','Standard','Comedy','2026-01-05',100),

		(12,104,'David','Premium','Sci-Fi','2026-01-01',140),
		(13,104,'David','Premium','Sci-Fi','2026-01-04',135),
		(14,104,'David','Premium','Action','2026-01-05',110),

		(15,105,'Eva','Basic','Comedy','2026-01-02',50),
		(16,105,'Eva','Basic','Comedy','2026-01-03',60),
		(17,105,'Eva','Basic','Comedy','2026-01-04',65),
		(18,105,'Eva','Basic','Action','2026-01-08',120),

		(19,106,'Frank','Standard','Drama','2026-01-05',90),
		(20,106,'Frank','Standard','Action','2026-01-06',100),
		(21,106,'Frank','Standard','Action','2026-01-07',105),
		(22,106,'Frank','Standard','Comedy','2026-01-08',80),

		(23,107,'Grace','Premium','Drama','2026-01-01',100),
		(24,107,'Grace','Premium','Drama','2026-01-02',110),
		(25,107,'Grace','Premium','Drama','2026-01-03',120),
		(26,107,'Grace','Premium','Drama','2026-01-04',130),

		(27,108,'Henry','Basic','Action','2026-01-03',70),
		(28,108,'Henry','Basic','Comedy','2026-01-06',75),
		(29,108,'Henry','Basic','Comedy','2026-01-07',85),
		(30,108,'Henry','Basic','Drama','2026-01-08',95);
        
SELECT *
FROM Streaming_Service_Activity;


-- Q1
-- Show each user's total watch records,
-- total watch minutes, and average watch minutes.
--
-- Return:
-- User_ID
-- User_Name
-- Total_Watch_Records
-- Total_Watch_Minutes
-- Average_Watch_Minutes

SELECT User_ID, User_Name,
	   COUNT(Activity_ID) AS Total_Watch_Records,
       SUM(Watch_Minutes) AS Total_Watch_Minutes,
       ROUND(AVG(Watch_Minutes), 2) AS Average_Watch_Minutes
FROM Streaming_Service_Activity
GROUP BY User_ID, User_Name;


-- Q2
-- Show each content genre's total watch records
-- and total watch minutes.
--
-- Return:
-- Content_Genre
-- Total_Watch_Records
-- Total_Watch_Minutes

SELECT Content_Genre,
	   COUNT(Activity_ID) AS Total_Watch_Records,
       SUM(Watch_Minutes) AS Total_Watch_Minutes
FROM Streaming_Service_Activity
GROUP BY Content_Genre;


-- Q3
-- Find the top 3 users by total watch minutes.
--
-- Return:
-- User_ID
-- User_Name
-- Total_Watch_Minutes

WITH CTE AS (
	SELECT User_ID, User_Name,
		   SUM(Watch_Minutes) AS Total_Watch_Minutes
	FROM Streaming_Service_Activity
	GROUP BY User_ID, User_Name
),
CTE2 AS (
	SELECT *,
		   DENSE_RANK() OVER(ORDER BY Total_Watch_Minutes DESC) AS D_Rank
	FROM CTE
)
SELECT User_ID, User_Name, Total_Watch_Minutes
FROM CTE2
WHERE D_Rank <= 3;


-- Q4
-- Find users who watched content within 2 days
-- of their previous watch activity.
--
-- Return:
-- User_ID
-- User_Name

WITH CTE AS (
	SELECT User_ID, User_Name, Watch_Date,
		   LAG(Watch_Date) OVER(PARTITION BY User_ID
           ORDER BY Watch_Date, Activity_ID) AS Previous
	FROM Streaming_Service_Activity
)
SELECT DISTINCT User_ID, User_Name
FROM CTE
WHERE Previous IS NOT NULL
AND DATEDIFF(Watch_Date, Previous) <= 2;


-- Q5 (COHORT ANALYSIS)
-- For each cohort month, find:
-- total users
-- and total watch minutes generated by those users.
--
-- Definition:
-- A user's cohort month is the month of
-- their first watch date.
--
-- Return:
-- Cohort_Month
-- Total_Users
-- Total_Watch_Minutes

WITH CTE AS (
	SELECT User_ID,
		   MIN(Watch_Date) AS First_Watch_Date
	FROM Streaming_Service_Activity
    GROUP BY User_ID
),
CTE2 AS (
	SELECT *,
           DATE_FORMAT(First_Watch_Date, '%Y-%m') AS Cohort_Month
	FROM CTE
)
SELECT Cohort_Month,
	   COUNT(DISTINCT S.User_ID) AS Total_Users,
       SUM(Watch_Minutes) AS Total_Watch_Minutes
FROM CTE2 C
INNER JOIN Streaming_Service_Activity S
	ON S.User_ID = C.User_ID
GROUP BY Cohort_Month;


-- BONUS (GAP & ISLAND)
-- Find users whose current watch streak
-- is at least 3 days.
--
-- Return:
-- User_ID
-- User_Name
-- Current_Streak
-- Start_Date
-- End_Date
--
-- Definition:
-- Current streak = streak containing the user's
-- most recent watch date.
--
-- Note:
-- Ignore duplicate watch dates if a user
-- has multiple activities on the same day.

WITH CTE AS (
	SELECT DISTINCT User_ID, User_Name, Watch_Date
    FROM Streaming_Service_Activity
),
CTE2 AS (
	SELECT *,
		   ROW_NUMBER() OVER(PARTITION BY User_ID
           ORDER BY Watch_Date) AS RN
	FROM CTE
),
CTE3 AS (
	SELECT *,
		   DATE_SUB(Watch_Date, INTERVAL RN DAY) AS GK
	FROM CTE2
),
CTE4 AS (
	SELECT User_ID, User_Name,
		   COUNT(*) AS Streak,
		   MIN(Watch_Date) AS Start_Date,
           MAX(Watch_Date) AS End_Date
	FROM CTE3
	GROUP BY User_ID, User_Name, GK
),
CTE5 AS (
	SELECT *,
		   DENSE_RANK() OVER(PARTITION BY User_ID
           ORDER BY End_Date DESC) AS D_Rank
	FROM CTE4
)
SELECT User_ID, User_Name, Streak AS Current_Streak, 
	   Start_Date, End_Date
FROM CTE5
WHERE D_Rank = 1
AND Streak >= 3;