USE Daily_SQL;

-- Domain: Online Food Delivery Reviews

CREATE TABLE Food_Delivery_Reviews (
    Review_ID INT PRIMARY KEY,
    Customer_ID INT,
    Customer_Name VARCHAR(50),
    Restaurant_Name VARCHAR(50),
    Cuisine_Type VARCHAR(30),
    Rating INT,
    Review_Date DATE
);

INSERT INTO Food_Delivery_Reviews
VALUES	(1,101,'Alice','Spicy Hub','Indian',5,'2025-01-01'),
		(2,101,'Alice','Spicy Hub','Indian',4,'2025-01-02'),
		(3,101,'Alice','Pizza Town','Italian',5,'2025-01-03'),
		(4,101,'Alice','Burger House','Fast Food',3,'2025-01-06'),

		(5,102,'Bob','Pizza Town','Italian',5,'2025-01-04'),
		(6,102,'Bob','Pizza Town','Italian',4,'2025-01-05'),
		(7,102,'Bob','Pizza Town','Italian',5,'2025-01-06'),
		(8,102,'Bob','Spicy Hub','Indian',4,'2025-01-08'),

		(9,103,'Charlie','Burger House','Fast Food',3,'2025-02-01'),
		(10,103,'Charlie','Burger House','Fast Food',5,'2025-02-02'),
		(11,103,'Charlie','Burger House','Fast Food',4,'2025-02-05'),

		(12,104,'David','Sushi World','Japanese',5,'2025-03-01'),
		(13,104,'David','Sushi World','Japanese',5,'2025-03-02'),
		(14,104,'David','Sushi World','Japanese',4,'2025-03-03'),
		(15,104,'David','Pizza Town','Italian',5,'2025-03-05'),

		(16,105,'Eva','Spicy Hub','Indian',2,'2025-03-10'),
		(17,105,'Eva','Burger House','Fast Food',3,'2025-03-12'),
		(18,105,'Eva','Burger House','Fast Food',4,'2025-03-13'),
		(19,105,'Eva','Burger House','Fast Food',5,'2025-03-14'),

		(20,106,'Frank','Pizza Town','Italian',5,'2025-04-01'),
		(21,106,'Frank','Pizza Town','Italian',5,'2025-04-02'),
		(22,106,'Frank','Pizza Town','Italian',5,'2025-04-03'),
		(23,106,'Frank','Pizza Town','Italian',5,'2025-04-04');
        
SELECT *
FROM Food_Delivery_Reviews;

-- Q1
-- Show each customer's total reviews,
-- total rating points, and average rating.
--
-- Return:
-- Customer_ID
-- Customer_Name
-- Total_Reviews
-- Total_Rating_Points
-- Average_Rating

SELECT Customer_ID, Customer_Name,
	   COUNT(Review_ID) AS Total_Reviews,
       SUM(Rating) AS Total_Rating_Points,
       ROUND(AVG(Rating), 2) AS Average_Rating
FROM Food_Delivery_Reviews
GROUP BY Customer_ID, Customer_Name;


-- Q2
-- Show each cuisine type's total reviews
-- and total rating points.
--
-- Return:
-- Cuisine_Type
-- Total_Reviews
-- Total_Rating_Points

SELECT Cuisine_Type,
	   COUNT(Review_ID) AS Total_Reviews,
       SUM(Rating) AS Total_Rating_Points
FROM Food_Delivery_Reviews
GROUP BY Cuisine_Type;


-- Q3
-- Find the top 3 customers by total rating points.
--
-- Return:
-- Customer_ID
-- Customer_Name
-- Total_Rating_Points

WITH CTE AS (
	SELECT Customer_ID, Customer_Name,
		   SUM(Rating) AS Total_Rating_Points
	FROM Food_Delivery_Reviews
	GROUP BY Customer_ID, Customer_Name
),
CTE2 AS (
	SELECT *,
		   DENSE_RANK() OVER(ORDER BY Total_Rating_Points DESC) AS D_Rank
	FROM CTE
)
SELECT Customer_ID, Customer_Name, Total_Rating_Points
FROM CTE2
WHERE D_Rank <= 3;


-- Q4
-- Find customers who submitted a review within 2 days
-- of their previous review.
--
-- Return:
-- Customer_ID
-- Customer_Name

WITH CTE AS (
	SELECT Customer_ID, Customer_Name, Review_Date,
		   LAG(Review_Date) OVER(PARTITION BY Customer_ID
           ORDER BY Review_Date, Review_ID) AS Previous
	FROM Food_Delivery_Reviews
),
CTE2 AS (
	SELECT *,
		   DATEDIFF(Review_Date, Previous) AS Days_Gap
	FROM CTE
)
SELECT DISTINCT Customer_ID, Customer_Name
FROM CTE2
WHERE Days_Gap <= 2;


-- Q5 (COHORT ANALYSIS)
-- For each cohort month, find:
-- total customers
-- and total rating points generated by those customers.
--
-- Definition:
-- A customer's cohort month is the month of
-- their first review date.
--
-- Return:
-- Cohort_Month
-- Total_Customers
-- Total_Rating_Points

WITH CTE AS (
	SELECT Customer_ID,
		   MIN(Review_Date) AS First_Review_Date
	FROM Food_Delivery_Reviews
    GROUP BY Customer_ID
),
CTE2 AS (
	SELECT *,
		   DATE_FORMAT(First_Review_Date, '%Y-%m') AS Cohort_Month
	FROM CTE
)
SELECT Cohort_Month,
	   COUNT(DISTINCT F.Customer_ID) AS Total_Customers,
       SUM(F.Rating) AS Total_Rating_Points
FROM CTE2 C
INNER JOIN Food_Delivery_Reviews F
	ON C.Customer_ID = F.Customer_ID
GROUP BY Cohort_Month;


-- BONUS (GAP & ISLAND)
-- Find the start date and end date of each customer's
-- longest review streak.
--
-- Return:
-- Customer_ID
-- Customer_Name
-- Longest_Streak
-- Start_Date
-- End_Date
--
-- Note:
-- Ignore duplicate review dates if a customer
-- has multiple reviews on the same day.
--
-- If multiple streaks have the same length,
-- return the most recent streak.

WITH CTE AS (
	SELECT DISTINCT Customer_ID, Customer_Name, Review_Date
    FROM Food_Delivery_Reviews
),
CTE2 AS (
	SELECT *,
		   ROW_NUMBER() OVER(PARTITION BY Customer_ID
           ORDER BY Review_Date) AS RN
	FROM CTE
),
CTE3 AS (
	SELECT *,
		   DATE_SUB(Review_Date, INTERVAL RN DAY) AS GK
	FROM CTE2
),
CTE4 AS (
	SELECT Customer_ID, Customer_Name,
		   COUNT(*) AS Streak,
           MIN(Review_Date) AS Start_Date,
           MAX(Review_Date) AS End_Date
	FROM CTE3
    GROUP BY Customer_ID, Customer_Name, GK
),
CTE5 AS (
	SELECT *,
		   DENSE_RANK() OVER(PARTITION BY Customer_ID
           ORDER BY Streak DESC, End_Date DESC) AS D_Rank
	FROM CTE4
)
SELECT Customer_ID, Customer_Name, Streak AS Longest_Streak,
	   Start_Date, End_Date
FROM CTE5
WHERE D_Rank = 1;