USE Daily_SQL;

-- Topic: E-Commerce Orders

-- DATASET: ECommerce_Orders

CREATE TABLE ECommerce_Orders (
    Order_ID INT PRIMARY KEY,
    Customer_ID INT,
    Customer_Name VARCHAR(50),
    Product_Category VARCHAR(30),
    Order_Date DATE,
    Order_Amount DECIMAL(10,2)
);

INSERT INTO ECommerce_Orders 
VALUES	(1,101,'Alice','Electronics','2025-01-01',1200),
		(2,101,'Alice','Electronics','2025-01-02',800),
		(3,101,'Alice','Books','2025-01-03',350),
		(4,101,'Alice','Books','2025-01-07',500),

		(5,102,'Bob','Fashion','2025-01-02',700),
		(6,102,'Bob','Fashion','2025-01-05',900),
		(7,102,'Bob','Electronics','2025-01-06',1300),
		(8,102,'Bob','Books','2025-01-07',450),

		(9,103,'Charlie','Home','2025-01-03',600),
		(10,103,'Charlie','Home','2025-01-04',900),
		(11,103,'Charlie','Home','2025-01-05',750),
		(12,103,'Charlie','Fashion','2025-01-08',1000),

		(13,104,'David','Books','2025-01-01',250),
		(14,104,'David','Books','2025-01-04',400),
		(15,104,'David','Books','2025-01-05',300),
		(16,104,'David','Electronics','2025-01-06',2200),

		(17,105,'Eva','Fashion','2025-01-05',950),
		(18,105,'Eva','Fashion','2025-01-06',1050),
		(19,105,'Eva','Fashion','2025-01-07',1100),
		(20,105,'Eva','Electronics','2025-01-10',2500);
        
SELECT *
FROM ECommerce_Orders;

-- Q1
-- Show each customer's total orders,
-- total order amount, and average order amount.
--
-- Return:
-- Customer_ID
-- Customer_Name
-- Total_Orders
-- Total_Order_Amount
-- Average_Order_Amount

SELECT Customer_ID, Customer_Name,
	   COUNT(Order_ID) AS Total_Orders,
       SUM(Order_Amount) AS Total_Order_Amount,
       ROUND(AVG(Order_Amount), 2) AS Average_Order_Amount
FROM ECommerce_Orders
GROUP BY Customer_ID, Customer_Name;


-- Q2
-- Show each product category's total orders
-- and total revenue.
--
-- Return:
-- Product_Category
-- Total_Orders
-- Total_Revenue

SELECT Product_Category,
	   COUNT(Order_ID) AS Total_Orders,
       SUM(Order_Amount) AS Total_Revenue
FROM ECommerce_Orders
GROUP BY Product_Category;


-- Q3
-- Find the top 3 customers by total order amount.
--
-- Return:
-- Customer_ID
-- Customer_Name
-- Total_Order_Amount

WITH CTE AS (
	SELECT Customer_ID, Customer_Name,
		   SUM(Order_Amount) AS Total_Order_Amount
	FROM ECommerce_Orders
    GROUP BY Customer_ID, Customer_Name
),
CTE2 AS (
	SELECT *,
		   DENSE_RANK() OVER(ORDER BY Total_Order_Amount DESC) AS D_Rank
	FROM CTE
)
SELECT Customer_ID, Customer_Name, Total_Order_Amount
FROM CTE2
WHERE D_Rank <= 3;

-- OR

WITH CTE AS (
	SELECT Customer_ID, Customer_Name,
		   SUM(Order_Amount) AS Total_Order_Amount
	FROM ECommerce_Orders
    GROUP BY Customer_ID, Customer_Name
)
SELECT *
FROM CTE
ORDER BY Total_Order_Amount DESC
LIMIT 3;


-- Q4
-- Find customers who placed an order within 2 days
-- of their previous order.
--
-- Return:
-- Customer_ID
-- Customer_Name

WITH CTE AS (
	SELECT Customer_ID, Customer_Name, Order_Date,
		   LAG(Order_Date) OVER(PARTITION BY Customer_ID
		   ORDER BY Order_Date, Order_ID) AS Previous
	FROM ECommerce_Orders
)
SELECT DISTINCT Customer_ID, Customer_Name
FROM CTE
WHERE Previous IS NOT NULL
AND DATEDIFF(Order_Date, Previous) <= 2;


-- Q5 (COHORT ANALYSIS)
-- For each cohort month, find:
-- total customers
-- and total revenue generated by those customers.
--
-- Definition:
-- A customer's cohort month is the month of
-- their first order date.
--
-- Return:
-- Cohort_Month
-- Total_Customers
-- Total_Revenue

WITH CTE AS (
	SELECT Customer_ID,
		   MIN(Order_Date) AS First_Order_Date
	FROM ECommerce_Orders
    GROUP BY Customer_ID
),
CTE2 AS (
	SELECT *,
		   DATE_FORMAT(First_Order_Date, '%Y-%m') AS Cohort_Month
	FROM CTE
)
SELECT Cohort_Month,
	   COUNT(DISTINCT E.Customer_ID) AS Total_Customers,
       SUM(E.Order_Amount) AS Total_Revenue
FROM CTE2 C
INNER JOIN ECommerce_Orders E
	ON C.Customer_ID = E.Customer_ID
GROUP BY Cohort_Month;


-- BONUS (GAP & ISLAND)
-- Find customers whose longest order streak
-- is at least 3 days.
--
-- Return:
-- Customer_ID
-- Customer_Name
-- Longest_Streak
--
-- Note:
-- Ignore duplicate order dates if a customer
-- has multiple orders on the same day.
--
-- If multiple streaks exist,
-- consider only the longest streak.

WITH CTE AS (
	SELECT DISTINCT Customer_ID, Customer_Name, Order_Date
    FROM ECommerce_Orders
),
CTE2 AS (
	SELECT *,
		   ROW_NUMBER() OVER(PARTITION BY Customer_ID
           ORDER BY Order_Date) AS RN
	FROM CTE
),
CTE3 AS (
	SELECT *,
		   DATE_SUB(Order_Date, INTERVAL RN DAY) AS GK
	FROM CTE2
),
CTE4 AS (
	SELECT Customer_ID, Customer_Name,
		   COUNT(*) AS Streak
	FROM CTE3
    GROUP BY Customer_ID, Customer_Name, GK
)
SELECT Customer_ID, Customer_Name,
	   MAX(Streak) AS Longest_Streak
FROM CTE4
GROUP BY Customer_ID, Customer_Name
HAVING MAX(Streak) >= 3;