USE Daily_SQL;

-- Topic: Hospital Patient Visits

CREATE TABLE Hospital_Patient_Visits (
    Visit_ID INT PRIMARY KEY,
    Patient_ID INT,
    Patient_Name VARCHAR(50),
    Department VARCHAR(30),
    Visit_Date DATE,
    Bill_Amount DECIMAL(10,2)
);

INSERT INTO Hospital_Patient_Visits 
VALUES	(1,101,'Alice','Cardiology','2026-01-02',2500),
		(2,101,'Alice','Cardiology','2026-01-03',1800),
		(3,101,'Alice','Neurology','2026-01-04',3200),
		(4,101,'Alice','Orthopedics','2026-01-06',2100),

		(5,102,'Bob','Dermatology','2026-01-01',900),
		(6,102,'Bob','Dermatology','2026-01-05',1100),
		(7,102,'Bob','Cardiology','2026-01-06',2800),

		(8,103,'Charlie','Orthopedics','2026-01-10',1500),
		(9,103,'Charlie','Orthopedics','2026-01-11',1700),
		(10,103,'Charlie','Orthopedics','2026-01-12',1600),
		(11,103,'Charlie','Neurology','2026-01-15',3000),

		(12,104,'David','Cardiology','2026-02-01',2600),
		(13,104,'David','Cardiology','2026-02-02',2700),
		(14,104,'David','Cardiology','2026-02-03',2800),
		(15,104,'David','Cardiology','2026-02-04',2900),

		(16,105,'Eva','Pediatrics','2026-02-07',1200),
		(17,105,'Eva','Pediatrics','2026-02-09',1300),
		(18,105,'Eva','Neurology','2026-02-10',3400),

		(19,106,'Frank','Orthopedics','2026-03-01',2200),
		(20,106,'Frank','Orthopedics','2026-03-02',2100),
		(21,106,'Frank','Orthopedics','2026-03-03',2000),

		(22,107,'Grace','Dermatology','2026-03-05',800),
		(23,107,'Grace','Dermatology','2026-03-06',900),
		(24,107,'Grace','Cardiology','2026-03-08',2500),

		(25,108,'Henry','Neurology','2026-03-10',3500),
		(26,108,'Henry','Neurology','2026-03-11',3600),
		(27,108,'Henry','Neurology','2026-03-12',3700),
		(28,108,'Henry','Neurology','2026-03-13',3800),

		(29,109,'Ivy','Pediatrics','2026-03-15',1000),
		(30,109,'Ivy','Pediatrics','2026-03-18',1100);

SELECT *
FROM Hospital_Patient_Visits;

-- Q1
-- Show each patient's total visits,
-- total bill amount, and average bill amount.
--
-- Return:
-- Patient_ID
-- Patient_Name
-- Total_Visits
-- Total_Bill_Amount
-- Average_Bill_Amount

SELECT Patient_ID, Patient_Name,
	   COUNT(Visit_ID) AS Total_Visits,
       SUM(Bill_Amount) AS Total_Bill_Amount,
       ROUND(AVG(Bill_Amount), 2) AS Average_Bill_Amount
FROM Hospital_Patient_Visits
GROUP BY Patient_ID, Patient_Name;


-- Q2
-- Show each department's total visits
-- and total bill amount.
--
-- Return:
-- Department
-- Total_Visits
-- Total_Bill_Amount

SELECT Department,
	   COUNT(Visit_ID) AS Total_Visits,
       SUM(Bill_Amount) AS Total_Bill_Amount
FROM Hospital_Patient_Visits
GROUP BY Department;


-- Q3
-- Find the top 3 patients by total bill amount.
--
-- Return:
-- Patient_ID
-- Patient_Name
-- Total_Bill_Amount

WITH CTE AS (
	SELECT Patient_ID, Patient_Name,
		   SUM(Bill_Amount) AS Total_Bill_Amount
	FROM Hospital_Patient_Visits
	GROUP BY Patient_ID, Patient_Name
),
CTE2 AS (
	SELECT *,
		   DENSE_RANK() OVER(ORDER BY Total_Bill_Amount DESC) AS D_Rank
	FROM CTE
)
SELECT Patient_ID, Patient_Name, Total_Bill_Amount
FROM CTE2
WHERE D_Rank <= 3;


-- Q4
-- Find patients who visited the hospital within 2 days
-- of their previous visit.
--
-- Return:
-- Patient_ID
-- Patient_Name

WITH CTE AS (
	SELECT Patient_ID, Patient_Name, Visit_Date,
		   LAG(Visit_Date) OVER(PARTITION BY Patient_ID
           ORDER BY Visit_Date, Visit_ID) AS Previous
	FROM Hospital_Patient_Visits
)
SELECT DISTINCT Patient_ID, Patient_Name
FROM CTE
WHERE Previous IS NOT NULL
AND DATEDIFF(Visit_Date, Previous) <= 2;


-- Q5 (COHORT ANALYSIS)
-- For each cohort month, find:
-- total patients
-- and total bill amount generated by those patients.
--
-- Definition:
-- A patient's cohort month is the month of
-- their first visit date.
--
-- Return:
-- Cohort_Month
-- Total_Patients
-- Total_Bill_Amount

WITH CTE AS (
	SELECT Patient_ID,
		   MIN(Visit_Date) AS First_Visit_Date
	FROM Hospital_Patient_Visits
    GROUP BY Patient_ID
),
CTE2 AS (
	SELECT *,
		   DATE_FORMAT(First_Visit_Date, '%Y-%m') AS Cohort_Month
	FROM CTE
)
SELECT Cohort_Month,
	   COUNT(DISTINCT H.Patient_ID) AS Total_Patients,
       SUM(H.Bill_Amount) AS Total_Bill_Amount
FROM CTE2 C
INNER JOIN Hospital_Patient_Visits H
	ON C.Patient_ID = H.Patient_ID
GROUP BY Cohort_Month;


-- BONUS (GAP & ISLAND)
-- Find the start date and end date of each patient's
-- current visit streak.
--
-- Return:
-- Patient_ID
-- Patient_Name
-- Current_Streak
-- Start_Date
-- End_Date
--
-- Definition:
-- Current streak = streak containing the patient's
-- most recent visit date.
--
-- Note:
-- Ignore duplicate visit dates if a patient
-- has multiple visits on the same day.
--
-- Return only patients whose Current_Streak >= 3.

WITH CTE AS (
	SELECT DISTINCT Patient_ID, Patient_Name, Visit_Date
    FROM Hospital_Patient_Visits
),
CTE2 AS (
	SELECT *,
		   ROW_NUMBER() OVER(PARTITION BY Patient_ID
           ORDER BY Visit_Date) AS RN
	FROM CTE
),
CTE3 AS (
	SELECT *,
		   DATE_SUB(Visit_Date, INTERVAL RN DAY) AS GK
	FROM CTE2
),
CTE4 AS (
	SELECT Patient_ID, Patient_Name,
		   COUNT(*) AS Streak,
           MIN(Visit_Date) AS Start_Date,
		   MAX(Visit_Date) AS End_Date
	FROM CTE3
	GROUP BY Patient_ID, Patient_Name, GK
),
CTE5 AS (
	SELECT *,
		   DENSE_RANK() OVER(PARTITION BY Patient_ID
		   ORDER BY End_Date DESC) AS D_Rank
	FROM CTE4
)
SELECT Patient_ID, Patient_Name, Streak AS Current_Streak, Start_Date, End_Date
FROM CTE5
WHERE D_Rank = 1
AND Streak >= 3;