USE Daily_SQL;

-- Topic: Online Food Orders

CREATE TABLE Online_Food_Orders (
    Order_ID INT PRIMARY KEY,
    Customer_ID INT,
    Customer_Name VARCHAR(50),
    Restaurant_Name VARCHAR(50),
    Cuisine_Type VARCHAR(30),
    Order_Date DATE,
    Order_Amount DECIMAL(10,2)
);

INSERT INTO Online_Food_Orders 
VALUES	(1,101,'Alice','Spice Hub','Indian','2026-01-01',450),
		(2,101,'Alice','Spice Hub','Indian','2026-01-02',520),
		(3,101,'Alice','Burger Point','Fast Food','2026-01-03',310),
		(4,101,'Alice','Pizza World','Italian','2026-01-07',650),

		(5,102,'Bob','Pizza World','Italian','2026-01-05',780),
		(6,102,'Bob','Pizza World','Italian','2026-01-06',420),
		(7,102,'Bob','Sushi House','Japanese','2026-01-08',950),

		(8,103,'Charlie','Burger Point','Fast Food','2026-01-02',280),
		(9,103,'Charlie','Burger Point','Fast Food','2026-01-03',360),
		(10,103,'Charlie','Burger Point','Fast Food','2026-01-04',410),
		(11,103,'Charlie','Spice Hub','Indian','2026-01-05',590),

		(12,104,'David','Sushi House','Japanese','2026-02-01',870),
		(13,104,'David','Sushi House','Japanese','2026-02-02',640),

		(14,105,'Eva','Spice Hub','Indian','2026-02-10',500),
		(15,105,'Eva','Pizza World','Italian','2026-02-11',700),
		(16,105,'Eva','Burger Point','Fast Food','2026-02-12',320),
		(17,105,'Eva','Burger Point','Fast Food','2026-02-13',410),

		(18,106,'Frank','Pizza World','Italian','2026-03-01',760),
		(19,106,'Frank','Pizza World','Italian','2026-03-04',580),

		(20,107,'Grace','Spice Hub','Indian','2026-03-10',450),
		(21,107,'Grace','Spice Hub','Indian','2026-03-11',510),
		(22,107,'Grace','Spice Hub','Indian','2026-03-12',620),
		(23,107,'Grace','Sushi House','Japanese','2026-03-13',880),

		(24,108,'Henry','Burger Point','Fast Food','2026-03-15',340),
		(25,108,'Henry','Burger Point','Fast Food','2026-03-18',390);
        
SELECT *
FROM Online_Food_Orders;

-- Q1
-- Show each customer's total orders,
-- total order amount, and average order amount.
--
-- Return:
-- Customer_ID
-- Customer_Name
-- Total_Orders
-- Total_Order_Amount
-- Average_Order_Amount

SELECT Customer_ID, Customer_Name,
	   COUNT(Order_ID) AS Total_Orders,
       SUM(Order_Amount) AS Total_Order_Amount,
       ROUND(AVG(Order_Amount), 2) AS Average_Order_Amount
FROM Online_Food_Orders
GROUP BY Customer_ID, Customer_Name;


-- Q2
-- Show each cuisine type's total orders
-- and total revenue.
--
-- Return:
-- Cuisine_Type
-- Total_Orders
-- Total_Revenue

SELECT Cuisine_Type,
	   COUNT(Order_ID) AS Total_Orders,
       SUM(Order_Amount) AS Total_Revenue
FROM Online_Food_Orders
GROUP BY Cuisine_Type;



-- Q3
-- Find the top 3 customers by total order amount.
--
-- Return:
-- Customer_ID
-- Customer_Name
-- Total_Order_Amount

WITH CTE AS (
	SELECT Customer_ID, Customer_Name,
		   SUM(Order_Amount) AS Total_Order_Amount
	FROM Online_Food_Orders
	GROUP BY Customer_ID, Customer_Name
),
CTE2 AS (
	SELECT *,
		   DENSE_RANK() OVER(ORDER BY Total_Order_Amount DESC) AS D_Rank
	FROM CTE
)
SELECT Customer_ID, Customer_Name, Total_Order_Amount
FROM CTE2
WHERE D_Rank <= 3;


-- Q4
-- Find customers who placed an order within 2 days
-- of their previous order.
--
-- Return:
-- Customer_ID
-- Customer_Name

WITH CTE AS (
	SELECT Customer_ID, Customer_Name, Order_Date,
		   LAG(Order_Date) OVER(PARTITION BY Customer_ID
           ORDER BY Order_Date, Order_ID) AS Previous
	FROM Online_Food_Orders
)
SELECT DISTINCT Customer_ID, Customer_Name
FROM CTE
WHERE Previous IS NOT NULL
AND DATEDIFF(Order_Date, Previous) <= 2;


-- Q5 (COHORT ANALYSIS)
-- For each cohort month, find:
-- total customers
-- and total order revenue generated by those customers.
--
-- Definition:
-- A customer's cohort month is the month of
-- their first order date.
--
-- Return:
-- Cohort_Month
-- Total_Customers
-- Total_Order_Revenue

WITH CTE AS (
	SELECT Customer_ID,
		   MIN(Order_Date) AS First_Order_Date
	FROM Online_Food_Orders
    GROUP BY Customer_ID
),
CTE2 AS (
	SELECT *,
		   DATE_FORMAT(First_Order_Date, '%Y-%m') AS Cohort_Month
	FROM CTE
)
SELECT Cohort_Month,
	   COUNT(DISTINCT O.Customer_ID) AS Total_Customers,
       SUM(O.Order_Amount) AS Total_Order_Revenue
FROM CTE2 C
INNER JOIN Online_Food_Orders O
	ON C.Customer_ID = O.Customer_ID
GROUP BY Cohort_Month;


-- BONUS (GAP & ISLAND)
-- Find the start date and end date of each customer's
-- longest order streak.
--
-- Return:
-- Customer_ID
-- Customer_Name
-- Longest_Streak
-- Start_Date
-- End_Date
--
-- Note:
-- Ignore duplicate order dates if a customer
-- has multiple orders on the same day.
--
-- If multiple streaks have the same length,
-- return the most recent streak.

WITH CTE AS (
	SELECT DISTINCT Customer_ID, Customer_Name, Order_Date
    FROM Online_Food_Orders
),
CTE2 AS (
	SELECT *,
		   ROW_NUMBER() OVER(PARTITION BY Customer_ID
           ORDER BY Order_Date) AS RN
	FROM CTE
),
CTE3 AS (
	SELECT *,
		   DATE_SUB(Order_Date, INTERVAL RN DAY) AS GK
	FROM CTE2
),
CTE4 AS (
	SELECT Customer_ID, Customer_Name,
		   COUNT(*) AS Streak,
           MIN(Order_Date) AS Start_Date,
           MAX(Order_Date) AS End_Date
	FROM CTE3
    GROUP BY Customer_ID, Customer_Name, GK
),
CTE5 AS (
	SELECT *,
		   ROW_NUMBER() OVER(PARTITION BY Customer_ID
           ORDER BY Streak DESC, End_Date DESC) AS Row_Num
	FROM CTE4
)		   
SELECT Customer_ID, Customer_Name, Streak AS Longest_Streak,
	   Start_Date, End_Date
FROM CTE5
WHERE Row_Num = 1;