USE Daily_SQL;

-- Topic: Mobile App Subscriptions

CREATE TABLE Mobile_App_Subscriptions (
    Subscription_ID INT PRIMARY KEY,
    Customer_ID INT,
    Customer_Name VARCHAR(50),
    App_Category VARCHAR(30),
    Subscription_Date DATE,
    Amount_Paid DECIMAL(10,2)
);

INSERT INTO Mobile_App_Subscriptions 
VALUES	(1,101,'Alice','Music','2025-01-01',199),
		(2,101,'Alice','Music','2025-01-02',199),
		(3,101,'Alice','Fitness','2025-01-03',299),
		(4,101,'Alice','Music','2025-01-06',199),

		(5,102,'Bob','Education','2025-01-05',499),
		(6,102,'Bob','Education','2025-01-06',499),
		(7,102,'Bob','Productivity','2025-01-07',399),
		(8,102,'Bob','Music','2025-01-10',199),

		(9,103,'Charlie','Fitness','2025-02-01',299),
		(10,103,'Charlie','Fitness','2025-02-03',299),
		(11,103,'Charlie','Fitness','2025-02-04',299),

		(12,104,'David','Productivity','2025-02-10',399),
		(13,104,'David','Productivity','2025-02-11',399),
		(14,104,'David','Productivity','2025-02-12',399),
		(15,104,'David','Productivity','2025-02-13',399),

		(16,105,'Eva','Music','2025-03-01',199),
		(17,105,'Eva','Education','2025-03-02',499),
		(18,105,'Eva','Music','2025-03-05',199),

		(19,106,'Frank','Fitness','2025-03-10',299),
		(20,106,'Frank','Fitness','2025-03-11',299),
		(21,106,'Frank','Fitness','2025-03-12',299),
		(22,106,'Frank','Fitness','2025-03-14',299),

		(23,107,'Grace','Music','2025-04-01',199),
		(24,107,'Grace','Music','2025-04-02',199),
		(25,107,'Grace','Music','2025-04-03',199),
		(26,107,'Grace','Music','2025-04-04',199),

		(27,108,'Henry','Education','2025-04-15',499),
		(28,108,'Henry','Education','2025-04-16',499),
		(29,108,'Henry','Education','2025-04-18',499),
		(30,108,'Henry','Education','2025-04-19',499);
        
SELECT *
FROM Mobile_App_Subscriptions;

-- Q1
-- Show each customer's total subscriptions,
-- total amount paid, and average amount paid.
--
-- Return:
-- Customer_ID
-- Customer_Name
-- Total_Subscriptions
-- Total_Amount_Paid
-- Average_Amount_Paid

SELECT Customer_ID, Customer_Name,
	   COUNT(Subscription_ID) AS Total_Subscriptions,
       SUM(Amount_Paid) AS Total_Amount_Paid,
       ROUND(AVG(Amount_Paid), 2) AS Average_Amount_Paid
FROM Mobile_App_Subscriptions
GROUP BY Customer_ID, Customer_Name;


-- Q2
-- Show each app category's total subscriptions
-- and total revenue.
--
-- Return:
-- App_Category
-- Total_Subscriptions
-- Total_Revenue

SELECT App_Category,
	   COUNT(Subscription_ID) AS Total_Subscriptions,
       SUM(Amount_Paid) AS Total_Revenue
FROM Mobile_App_Subscriptions
GROUP BY App_Category;


-- Q3
-- Find the top 3 customers by total amount paid.
--
-- Return:
-- Customer_ID
-- Customer_Name
-- Total_Amount_Paid

WITH CTE AS (
	SELECT Customer_ID, Customer_Name,
		   SUM(Amount_Paid) AS Total_Amount_Paid
	FROM Mobile_App_Subscriptions
	GROUP BY Customer_ID, Customer_Name
),
CTE2 AS (
	SELECT *,
		   DENSE_RANK() OVER(ORDER BY Total_Amount_Paid DESC) AS D_Rank
	FROM CTE
)
SELECT Customer_ID, Customer_Name, Total_Amount_Paid
FROM CTE2
WHERE D_Rank <= 3;


-- Q4
-- Find customers who made a subscription within 2 days
-- of their previous subscription.
--
-- Return:
-- Customer_ID
-- Customer_Name

WITH CTE AS (
	SELECT Customer_ID, Customer_Name, Subscription_Date,
		   LAG(Subscription_Date) OVER(PARTITION BY Customer_ID
           ORDER BY Subscription_Date, Subscription_ID) AS Previous
	FROM Mobile_App_Subscriptions
)
SELECT DISTINCT Customer_ID, Customer_Name
FROM CTE
WHERE Previous IS NOT NULL
AND DATEDIFF(Subscription_Date, Previous) <= 2;


-- Q5 (COHORT ANALYSIS)
-- For each cohort month, find:
-- total customers
-- and total revenue generated by those customers.
--
-- Definition:
-- A customer's cohort month is the month of
-- their first subscription date.
--
-- Return:
-- Cohort_Month
-- Total_Customers
-- Total_Revenue

WITH CTE AS (
	SELECT Customer_ID,
		   MIN(Subscription_Date) AS First_Subscription_Date
	FROM Mobile_App_Subscriptions
    GROUP BY Customer_ID
),
CTE2 AS (
	SELECT *,
		   DATE_FORMAT(First_Subscription_Date, '%Y-%m') AS Cohort_Month
	FROM CTE
)
SELECT Cohort_Month,
	   COUNT(DISTINCT M.Customer_ID) AS Total_Customers,
       SUM(M.Amount_Paid) AS Total_Revenue
FROM CTE2 C
INNER JOIN Mobile_App_Subscriptions M
	ON C.Customer_ID = M.Customer_ID
GROUP BY Cohort_Month;


-- BONUS (GAP & ISLAND)
-- Find customers whose current subscription streak
-- is at least 3 days.
--
-- Return:
-- Customer_ID
-- Customer_Name
-- Current_Streak
-- Start_Date
-- End_Date
--
-- Definition:
-- Current streak = streak containing the customer's
-- most recent subscription date.
--
-- Note:
-- Ignore duplicate subscription dates if a customer
-- has multiple subscriptions on the same day.

WITH CTE AS (
	SELECT DISTINCT Customer_ID, Customer_Name, Subscription_Date
    FROM Mobile_App_Subscriptions
),
CTE2 AS (
	SELECT *,
		   ROW_NUMBER() OVER(PARTITION BY Customer_ID
           ORDER BY Subscription_Date) AS RN
	FROM CTE
),
CTE3 AS (
	SELECT *,
		   DATE_SUB(Subscription_Date, INTERVAL RN DAY) AS GK
	FROM CTE2
),
CTE4 AS (
	SELECT Customer_ID, Customer_Name,
		   COUNT(*) AS Streak,
           MIN(Subscription_Date) AS Start_Date,
           MAX(Subscription_Date) AS End_Date
	FROM CTE3
    GROUP BY Customer_ID, Customer_Name, GK
),
CTE5 AS (
	SELECT *,
		   ROW_NUMBER() OVER(PARTITION BY Customer_ID
           ORDER BY End_Date DESC) AS Row_Num
	FROM CTE4
)
SELECT Customer_ID, Customer_Name, Streak AS Current_Streak,
	   Start_Date, End_Date
FROM CTE5
WHERE Row_Num = 1
AND Streak >= 3;