USE Daily_SQL;

-- Dataset: Hotel Bookings

CREATE TABLE Hotel_Bookings (
    Booking_ID INT PRIMARY KEY,
    Customer_ID INT,
    Customer_Name VARCHAR(50),
    Hotel_Name VARCHAR(100),
    City VARCHAR(50),
    Room_Type VARCHAR(30),
    Booking_Date DATE,
    Checkin_Date DATE,
    Checkout_Date DATE,
    Booking_Amount DECIMAL(10,2)
);

INSERT INTO Hotel_Bookings 
VALUES	(1,101,'Alice','Grand Palace','Chennai','Deluxe','2026-07-01','2026-07-05','2026-07-07',5000),
		(2,101,'Alice','Grand Palace','Chennai','Suite','2026-07-02','2026-07-08','2026-07-10',8000),
		(3,101,'Alice','Sea View','Goa','Standard','2026-07-03','2026-07-15','2026-07-17',4500),
		(4,101,'Alice','Sea View','Goa','Suite','2026-07-10','2026-07-20','2026-07-22',9000),

		(5,102,'Bob','Mountain Inn','Ooty','Standard','2026-07-01','2026-07-04','2026-07-05',3000),
		(6,102,'Bob','Mountain Inn','Ooty','Deluxe','2026-07-05','2026-07-09','2026-07-11',5500),
		(7,102,'Bob','City Stay','Bangalore','Suite','2026-07-06','2026-07-15','2026-07-17',8500),

		(8,103,'Charlie','Royal Residency','Hyderabad','Deluxe','2026-07-02','2026-07-06','2026-07-08',6200),
		(9,103,'Charlie','Royal Residency','Hyderabad','Deluxe','2026-07-03','2026-07-10','2026-07-12',6100),
		(10,103,'Charlie','Royal Residency','Hyderabad','Suite','2026-07-04','2026-07-18','2026-07-20',9200),

		(11,104,'David','Sea View','Goa','Standard','2026-07-07','2026-07-12','2026-07-14',4200),
		(12,104,'David','Sea View','Goa','Standard','2026-07-08','2026-07-15','2026-07-16',4100),

		(13,105,'Eva','City Stay','Bangalore','Suite','2026-07-09','2026-07-18','2026-07-20',9500),
		(14,105,'Eva','City Stay','Bangalore','Suite','2026-07-10','2026-07-21','2026-07-23',9600),
		(15,105,'Eva','City Stay','Bangalore','Deluxe','2026-07-11','2026-07-24','2026-07-26',6800),

		(16,106,'Frank','Grand Palace','Chennai','Standard','2026-07-12','2026-07-19','2026-07-20',3500),
		(17,106,'Frank','Grand Palace','Chennai','Standard','2026-07-15','2026-07-22','2026-07-23',3600),
		(18,107,'Grace','Mountain Inn','Ooty','Suite','2026-07-14','2026-07-21','2026-07-24',8700),
		(19,108,'Henry','Sea View','Goa','Deluxe','2026-07-16','2026-07-23','2026-07-25',6400),
		(20,109,'Ivy','Royal Residency','Hyderabad','Standard','2026-07-18','2026-07-26','2026-07-28',3900);
        

SELECT *
FROM Hotel_Bookings;

-- Q1
-- Show each customer's total bookings,
-- total booking amount, and average booking amount.
--
-- Return:
-- Customer_ID
-- Customer_Name
-- Total_Bookings
-- Total_Booking_Amount
-- Average_Booking_Amount

SELECT Customer_ID, Customer_Name,
	   COUNT(Booking_ID) AS Total_Bookings,
       SUM(Booking_Amount) AS Total_Booking_Amount,
       ROUND(AVG(Booking_Amount), 2) AS Average_Booking_Amount
FROM Hotel_Bookings
GROUP BY Customer_ID, Customer_Name;


-- Q2
-- Show each room type's total bookings
-- and total booking revenue.
--
-- Return:
-- Room_Type
-- Total_Bookings
-- Total_Booking_Revenue

SELECT Room_Type,
	   COUNT(Booking_ID) AS Total_Bookings,
       SUM(Booking_Amount) AS Total_Booking_Revenue
FROM Hotel_Bookings
GROUP BY Room_Type;


-- Q3
-- Find the top 3 customers by total booking amount.
--
-- Return:
-- Customer_ID
-- Customer_Name
-- Total_Booking_Amount

WITH CTE AS (
	SELECT Customer_ID, Customer_Name,
		   SUM(Booking_Amount) AS Total_Booking_Amount
	FROM Hotel_Bookings
	GROUP BY Customer_ID, Customer_Name
),
CTE2 AS (
	SELECT *,
		   DENSE_RANK() OVER(ORDER BY Total_Booking_Amount DESC) AS D_Rank
	FROM CTE
)
SELECT Customer_ID, Customer_Name, Total_Booking_Amount
FROM CTE2
WHERE D_Rank <= 3;


-- Q4
-- Find customers who made a booking within 2 days
-- of their previous booking.
--
-- Return:
-- Customer_ID
-- Customer_Name

WITH CTE AS (
	SELECT Customer_ID, Customer_Name, Booking_Date,
		   LAG(Booking_Date) OVER(PARTITION BY Customer_ID
           ORDER BY Booking_Date, Booking_ID) AS Previous
	FROM Hotel_Bookings
)
SELECT DISTINCT Customer_ID, Customer_Name
FROM CTE
WHERE Previous IS NOT NULL
AND DATEDIFF(Booking_Date, Previous) <= 2;


-- Q5 (COHORT ANALYSIS)
-- For each cohort month, find:
-- total customers
-- and total booking revenue generated by those customers.
--
-- Definition:
-- A customer's cohort month is the month of
-- their first booking date.
--
-- Return:
-- Cohort_Month
-- Total_Customers
-- Total_Booking_Revenue

WITH CTE AS (
	SELECT Customer_ID,
		   MIN(Booking_Date) AS First_Booking_Date
	FROM Hotel_Bookings
    GROUP BY Customer_ID
),
CTE2 AS (
	SELECT *,
		   DATE_FORMAT(First_Booking_Date, '%Y-%m') AS Cohort_Month
	FROM CTE
)
SELECT Cohort_Month,
	   COUNT(DISTINCT H.Customer_ID) AS Total_Customers,
       SUM(H.Booking_Amount) AS Total_Booking_Revenue
FROM CTE2 C
INNER JOIN Hotel_Bookings H
	ON C.Customer_ID = H.Customer_ID
GROUP BY Cohort_Month;


-- BONUS (GAP & ISLAND)
-- Find the start date and end date of each customer's
-- current booking streak.
--
-- Return:
-- Customer_ID
-- Customer_Name
-- Current_Streak
-- Start_Date
-- End_Date
--
-- Definition:
-- Current streak = streak containing the customer's
-- most recent booking date.
--
-- Note:
-- Ignore duplicate booking dates if a customer
-- has multiple bookings on the same day.
--
-- Return only customers whose Current_Streak >= 3.

WITH CTE AS (
	SELECT DISTINCT Customer_ID, Customer_Name, Booking_Date
    FROM Hotel_Bookings
),
CTE2 AS (
	SELECT *,
		   ROW_NUMBER() OVER(PARTITION BY Customer_ID
           ORDER BY Booking_Date) AS RN
	FROM CTE
),
CTE3 AS (
	SELECT *,
		   DATE_SUB(Booking_Date, INTERVAL RN DAY) AS GK
	FROM CTE2
),
CTE4 AS (
	SELECT Customer_ID, Customer_Name,
		   COUNT(*) AS Streak,
           MIN(Booking_Date) AS Start_Date,
           MAX(Booking_Date) AS End_Date
	FROM CTE3
    GROUP BY Customer_ID, Customer_Name, GK
),
CTE5 AS (
	SELECT *,
		   ROW_NUMBER() OVER(PARTITION BY Customer_ID
           ORDER BY End_Date DESC) AS Row_Num
	FROM CTE4
)
SELECT Customer_ID, Customer_Name, Streak AS Current_Streak,
	   Start_Date, End_Date
FROM CTE5
WHERE Row_Num = 1
AND Streak >= 3;