USE Daily_SQL;

-- DATASET: Restaurant Reservations

CREATE TABLE Restaurant_Reservations (
    Reservation_ID INT PRIMARY KEY,
    Customer_ID INT,
    Customer_Name VARCHAR(100),
    Reservation_Date DATE,
    Cuisine_Type VARCHAR(50),
    Bill_Amount DECIMAL(10,2)
);

INSERT INTO Restaurant_Reservations 
VALUES	(1,101,'Alice','2025-01-01','Italian',1200),
		(2,101,'Alice','2025-01-02','Italian',900),
		(3,101,'Alice','2025-01-03','Chinese',1100),
		(4,101,'Alice','2025-01-10','Mexican',1500),
		(5,102,'Bob','2025-01-05','Indian',800),
		(6,102,'Bob','2025-01-07','Indian',950),
		(7,102,'Bob','2025-01-08','Chinese',1000),
		(8,103,'Charlie','2025-02-01','Italian',2000),
		(9,103,'Charlie','2025-02-02','Italian',2100),
		(10,103,'Charlie','2025-02-03','Italian',2200),
		(11,103,'Charlie','2025-02-04','Mexican',1800),
		(12,104,'David','2025-02-10','Indian',700),
		(13,104,'David','2025-02-15','Chinese',900),
		(14,105,'Eva','2025-03-01','Mexican',1600),
		(15,105,'Eva','2025-03-02','Mexican',1700),
		(16,105,'Eva','2025-03-03','Mexican',1800),
		(17,105,'Eva','2025-03-08','Italian',1400),
		(18,106,'Frank','2025-03-10','Chinese',1300),
		(19,106,'Frank','2025-03-11','Chinese',1200),
		(20,107,'Grace','2025-03-15','Indian',1000),
		(21,108,'Henry','2025-04-01','Italian',2500),
		(22,108,'Henry','2025-04-02','Italian',2600),
		(23,108,'Henry','2025-04-03','Italian',2400),
		(24,108,'Henry','2025-04-10','Chinese',1900),
		(25,109,'Isabella','2025-04-12','Mexican',1750),
		(26,109,'Isabella','2025-04-13','Mexican',1650),
		(27,110,'Jack','2025-05-01','Indian',900),
		(28,110,'Jack','2025-05-05','Chinese',1000),
		(29,110,'Jack','2025-05-06','Chinese',1100),
		(30,110,'Jack','2025-05-07','Italian',1200);
        
SELECT *
FROM Restaurant_Reservations;

-- Q1
-- Show each customer's total reservations,
-- total bill amount, and average bill amount.
--
-- Return:
-- Customer_ID
-- Customer_Name
-- Total_Reservations
-- Total_Bill_Amount
-- Average_Bill_Amount

SELECT Customer_ID, Customer_Name,
	   COUNT(Reservation_ID) AS Total_Reservations,
       SUM(Bill_Amount) AS Total_Bill_Amount,
       ROUND(AVG(Bill_Amount), 2) AS Average_Bill_Amount
FROM Restaurant_Reservations
GROUP BY Customer_ID, Customer_Name;


-- Q2
-- Show each cuisine type's total reservations
-- and total revenue.
--
-- Return:
-- Cuisine_Type
-- Total_Reservations
-- Total_Revenue

SELECT Cuisine_Type,
	   COUNT(Reservation_ID) AS Total_Reservations,
       SUM(Bill_Amount) AS Total_Revenue
FROM Restaurant_Reservations
GROUP BY Cuisine_Type;


-- Q3
-- Find the top 3 customers by total bill amount.
--
-- Return:
-- Customer_ID
-- Customer_Name
-- Total_Bill_Amount

WITH CTE AS (
	SELECT Customer_ID, Customer_Name,
		   SUM(Bill_Amount) AS Total_Bill_Amount
	FROM Restaurant_Reservations
	GROUP BY Customer_ID, Customer_Name
),
CTE2 AS (
	SELECT *,
		   DENSE_RANK() OVER(ORDER BY Total_Bill_Amount DESC) AS D_Rank
	FROM CTE
)
SELECT Customer_ID, Customer_Name, Total_Bill_Amount
FROM CTE2
WHERE D_Rank <= 3;


-- Q4
-- Find customers who made a reservation within 2 days
-- of their previous reservation.
--
-- Return:
-- Customer_ID
-- Customer_Name

WITH CTE AS (
	SELECT Customer_ID, Customer_Name, Reservation_Date,
		   LAG(Reservation_Date) OVER(PARTITION BY Customer_ID
           ORDER BY Reservation_Date, Reservation_ID) AS Previous
	FROM Restaurant_Reservations
)
SELECT DISTINCT Customer_ID, Customer_Name
FROM CTE
WHERE Previous IS NOT NULL
AND DATEDIFF(Reservation_Date, Previous) <= 2;


-- Q5 (COHORT ANALYSIS)
-- For each cohort month, find:
-- total customers
-- and total bill revenue generated by those customers.
--
-- Definition:
-- A customer's cohort month is the month of
-- their first reservation date.
--
-- Return:
-- Cohort_Month
-- Total_Customers
-- Total_Bill_Revenue

WITH CTE AS (
	SELECT Customer_ID,
		   MIN(Reservation_Date) AS First_Reservation_Date
	FROM Restaurant_Reservations
    GROUP BY Customer_ID
),
CTE2 AS (
	SELECT *,
		   DATE_FORMAT(First_Reservation_Date, '%Y-%m') AS Cohort_Month
	FROM CTE
)
SELECT Cohort_Month,
	   COUNT(DISTINCT R.Customer_ID) AS Total_Customers,
       SUM(R.Bill_Amount) AS Total_Bill_Revenue
FROM CTE2 C
INNER JOIN Restaurant_Reservations R
	ON C.Customer_ID = R.Customer_ID
GROUP BY Cohort_Month;


-- BONUS (GAP & ISLAND)
-- Find the start date and end date of each customer's
-- longest reservation streak.
--
-- Return:
-- Customer_ID
-- Customer_Name
-- Longest_Streak
-- Start_Date
-- End_Date
--
-- Note:
-- Ignore duplicate reservation dates if a customer
-- has multiple reservations on the same day.
--
-- If multiple streaks have the same length,
-- return the most recent streak.

WITH CTE AS (
	SELECT DISTINCT Customer_ID, Customer_Name, Reservation_Date
    FROM Restaurant_Reservations
),
CTE2 AS (
	SELECT *,
		   ROW_NUMBER() OVER(PARTITION BY Customer_ID
           ORDER BY Reservation_Date) AS RN
	FROM CTE
),
CTE3 AS (
	SELECT *,
		   DATE_SUB(Reservation_Date, INTERVAL RN DAY) AS GK
	FROM CTE2
),
CTE4 AS (
	SELECT Customer_ID, Customer_Name,
		   COUNT(*) AS Streak,
           MIN(Reservation_Date) AS Start_Date,
           MAX(Reservation_Date) AS End_Date
	FROM CTE3
    GROUP BY Customer_ID, Customer_Name, GK
),
CTE5 AS (
	SELECT *,
		   ROW_NUMBER() OVER(PARTITION BY Customer_ID
           ORDER BY Streak DESC, End_Date DESC) AS Row_Num
	FROM CTE4
)
SELECT Customer_ID, Customer_Name, Streak AS Longest_Streak,
	   Start_Date, End_Date
FROM CTE5
WHERE Row_Num = 1;