USE Daily_SQL;

-- DATASET: Banking Transactions

CREATE TABLE Banking_Transactions (
    Transaction_ID INT PRIMARY KEY,
    Customer_ID INT,
    Customer_Name VARCHAR(100),
    Account_Type VARCHAR(30),
    Transaction_Date DATE,
    Transaction_Amount DECIMAL(10,2)
);

INSERT INTO Banking_Transactions 
VALUES	(1,101,'Alice','Savings','2025-01-01',5000),
		(2,101,'Alice','Savings','2025-01-02',3000),
		(3,101,'Alice','Savings','2025-01-03',2000),
		(4,101,'Alice','Savings','2025-01-07',4500),
		(5,101,'Alice','Savings','2025-01-08',3500),

		(6,102,'Bob','Current','2025-02-01',7000),
		(7,102,'Bob','Current','2025-02-03',4000),
		(8,102,'Bob','Current','2025-02-04',2500),
		(9,102,'Bob','Current','2025-02-05',5000),

		(10,103,'Charlie','Savings','2025-03-01',8000),
		(11,103,'Charlie','Savings','2025-03-02',4500),
		(12,103,'Charlie','Savings','2025-03-03',5000),
		(13,103,'Charlie','Savings','2025-03-04',6000),

		(14,104,'David','Business','2025-01-15',12000),
		(15,104,'David','Business','2025-01-18',9000),
		(16,104,'David','Business','2025-01-19',8500),

		(17,105,'Eva','Savings','2025-04-10',2500),
		(18,105,'Eva','Savings','2025-04-11',2600),
		(19,105,'Eva','Savings','2025-04-12',2700),
		(20,105,'Eva','Savings','2025-04-13',2800),

		(21,106,'Frank','Current','2025-05-01',4000),
		(22,106,'Frank','Current','2025-05-05',6000),
		(23,106,'Frank','Current','2025-05-06',7000),

		(24,107,'Grace','Business','2025-06-01',10000),
		(25,107,'Grace','Business','2025-06-02',9500),
		(26,107,'Grace','Business','2025-06-03',9000),
		(27,107,'Grace','Business','2025-06-04',9200),

		(28,108,'Henry','Savings','2025-07-01',3500),
		(29,108,'Henry','Savings','2025-07-02',3600),
		(30,108,'Henry','Savings','2025-07-06',3700);
        
SELECT *
FROM Banking_Transactions;

-- Q1
-- Show each customer's total transactions,
-- total transaction amount, and average transaction amount.
--
-- Return:
-- Customer_ID
-- Customer_Name
-- Total_Transactions
-- Total_Transaction_Amount
-- Average_Transaction_Amount

SELECT Customer_ID, Customer_Name,
	   COUNT(Transaction_ID) AS Total_Transactions,
       SUM(Transaction_Amount) AS Total_Transaction_Amount,
       ROUND(AVG(Transaction_Amount), 2) AS Average_Transaction_Amount
FROM Banking_Transactions
GROUP BY Customer_ID, Customer_Name;


-- Q2
-- Show each account type's total transactions
-- and total transaction amount.
--
-- Return:
-- Account_Type
-- Total_Transactions
-- Total_Transaction_Amount

SELECT Account_Type,
	   COUNT(Transaction_ID) AS Total_Transactions,
       SUM(Transaction_Amount) AS Total_Transaction_Amount
FROM Banking_Transactions
GROUP BY Account_Type;


-- Q3
-- Find the top 3 customers by total transaction amount.
--
-- Return:
-- Customer_ID
-- Customer_Name
-- Total_Transaction_Amount

WITH CTE AS (
	SELECT Customer_ID, Customer_Name,
		   SUM(Transaction_Amount) AS Total_Transaction_Amount
	FROM Banking_Transactions
	GROUP BY Customer_ID, Customer_Name
),
CTE2 AS (
	SELECT *,
		   DENSE_RANK() OVER(ORDER BY Total_Transaction_Amount DESC) AS D_Rank
	FROM CTE
)
SELECT Customer_ID, Customer_Name, Total_Transaction_Amount
FROM CTE2
WHERE D_Rank <= 3;


-- Q4
-- Find customers who made a transaction within 2 days
-- of their previous transaction.
--
-- Return:
-- Customer_ID
-- Customer_Name

WITH CTE AS (
	SELECT Customer_ID, Customer_Name, Transaction_Date,
		   LAG(Transaction_Date) OVER(PARTITION BY Customer_ID
           ORDER BY Transaction_Date, Transaction_ID) AS Previous
	FROM Banking_Transactions
)
SELECT DISTINCT Customer_ID, Customer_Name
FROM CTE
WHERE Previous IS NOT NULL
AND DATEDIFF(Transaction_Date, Previous) <= 2;


-- Q5 (COHORT ANALYSIS)
-- For each cohort month, find:
-- total customers
-- and total transaction amount generated by those customers.
--
-- Definition:
-- A customer's cohort month is the month of
-- their first transaction date.
--
-- Return:
-- Cohort_Month
-- Total_Customers
-- Total_Transaction_Amount

WITH CTE AS (
	SELECT Customer_ID,
		   MIN(Transaction_Date) AS First_Transaction_Date
	FROM Banking_Transactions
    GROUP BY Customer_ID
),
CTE2 AS (
	SELECT *,
		   DATE_FORMAT(First_Transaction_Date, '%Y-%m') AS Cohort_Month
	FROM CTE
)
SELECT Cohort_Month,
	   COUNT(DISTINCT B.Customer_ID) AS Total_Customers,
       SUM(B.Transaction_Amount) AS Total_Transaction_Amount
FROM CTE2 C
INNER JOIN Banking_Transactions B
	ON C.Customer_ID = B.Customer_ID
GROUP BY Cohort_Month;


-- BONUS (GAP & ISLAND)
-- Find the start date and end date of each customer's
-- current transaction streak.
--
-- Return:
-- Customer_ID
-- Customer_Name
-- Current_Streak
-- Start_Date
-- End_Date
--
-- Definition:
-- Current streak = streak containing the customer's
-- most recent transaction date.
--
-- Note:
-- Ignore duplicate transaction dates if a customer
-- has multiple transactions on the same day.
--
-- Return only customers whose Current_Streak >= 3.

WITH CTE AS (
	SELECT DISTINCT Customer_ID, Customer_Name, Transaction_Date
    FROM Banking_Transactions
),
CTE2 AS (
	SELECT *,
		   ROW_NUMBER() OVER(PARTITION BY Customer_ID
           ORDER BY Transaction_Date) AS RN
	FROM CTE
),
CTE3 AS (
	SELECT *,
		   DATE_SUB(Transaction_Date, INTERVAL RN DAY) AS GK
	FROM CTE2
),
CTE4 AS (
	SELECT Customer_ID, Customer_Name,
		   COUNT(*) AS Streak,
           MIN(Transaction_Date) AS Start_Date,
           MAX(Transaction_Date) AS End_Date
	FROM CTE3
    GROUP BY Customer_ID, Customer_Name, GK
),
CTE5 AS (
	SELECT *,
		   ROW_NUMBER() OVER(PARTITION BY Customer_ID
           ORDER BY End_Date DESC) AS Row_Num
	FROM CTE4
)
SELECT Customer_ID, Customer_Name, Streak AS Current_Streak,
	   Start_Date, End_Date
FROM  CTE5
WHERE Row_Num = 1
AND Streak >= 3;