USE Daily_SQL;

-- DATASET: Movie Ticket Booking

CREATE TABLE Customers (
    Customer_ID INT PRIMARY KEY,
    Customer_Name VARCHAR(100),
    City VARCHAR(50),
    Join_Date DATE
);

CREATE TABLE Movie_Bookings (
    Booking_ID INT PRIMARY KEY,
    Customer_ID INT,
    Movie_Name VARCHAR(100),
    Genre VARCHAR(50),
    Booking_Date DATE,
    Ticket_Amount DECIMAL(10,2),
    FOREIGN KEY (Customer_ID) REFERENCES Customers(Customer_ID)
);

INSERT INTO Customers 
VALUES	(101,'Alice','Chennai','2024-01-10'),
		(102,'Bob','Bangalore','2024-01-15'),
		(103,'Charlie','Hyderabad','2024-02-01'),
		(104,'David','Mumbai','2024-02-10'),
		(105,'Eva','Delhi','2024-02-15'),
		(106,'Frank','Chennai','2024-03-01'),
		(107,'Grace','Pune','2024-03-08'),
		(108,'Henry','Kolkata','2024-03-15'),
		(109,'Ivy','Jaipur','2024-04-01'),
		(110,'Jack','Coimbatore','2024-04-10');

INSERT INTO Movie_Bookings 
VALUES	(1,101,'Leo','Action','2024-04-01',350),
		(2,101,'Leo','Action','2024-04-02',350),
		(3,101,'GOAT','Action','2024-04-03',420),
		(4,102,'Jawan','Action','2024-04-05',380),
		(5,102,'Kalki','Sci-Fi','2024-04-07',450),
		(6,103,'Kalki','Sci-Fi','2024-04-08',450),
		(7,103,'Kalki','Sci-Fi','2024-04-09',450),
		(8,104,'Animal','Drama','2024-04-10',400),
		(9,104,'Pushpa','Action','2024-04-11',380),
		(10,105,'Jawan','Action','2024-04-15',380),
		(11,106,'Premalu','Comedy','2024-04-18',250),
		(12,106,'Premalu','Comedy','2024-04-19',250),
		(13,107,'GOAT','Action','2024-04-20',420),
		(14,108,'Kalki','Sci-Fi','2024-04-22',450),
		(15,108,'Kalki','Sci-Fi','2024-04-23',450),
		(16,108,'Kalki','Sci-Fi','2024-04-24',450),
		(17,109,'Leo','Action','2024-04-26',350),
		(18,109,'GOAT','Action','2024-04-27',420),
		(19,110,'Animal','Drama','2024-04-29',400),
		(20,110,'Animal','Drama','2024-04-30',400);
        
SELECT *
FROM Customers;

SELECT *
FROM Movie_Bookings;

-- Q1
-- Show each customer's total bookings,
-- total ticket amount, and average ticket amount.
--
-- Use both tables.
--
-- Return:
-- Customer_ID
-- Customer_Name
-- Total_Bookings
-- Total_Ticket_Amount
-- Average_Ticket_Amount

SELECT C.Customer_ID, C.Customer_Name,
	   COUNT(M.Booking_ID) AS Total_Bookings,
       SUM(M.Ticket_Amount) AS Total_Ticket_Amount,
       ROUND(AVG(M.Ticket_Amount), 2) AS Average_Ticket_Amount
FROM Customers C
INNER JOIN Movie_Bookings M
	ON C.Customer_ID = M.Customer_ID
GROUP BY C.Customer_ID, C.Customer_Name;


-- Q2
-- Show each movie genre's total bookings
-- and total ticket revenue.
--
-- Use both tables.
--
-- Return:
-- Genre
-- Total_Bookings
-- Total_Ticket_Revenue

SELECT M.Genre,
	   COUNT(M.Booking_ID) AS Total_Bookings,
       SUM(M.Ticket_Amount) AS Total_Ticket_Revenue
FROM Customers C
INNER JOIN Movie_Bookings M
	ON C.Customer_ID = M.Customer_ID
GROUP BY M.Genre;


-- Q3
-- Find the top 3 customers by total ticket amount.
--
-- Use DENSE_RANK().
--
-- Return:
-- Customer_ID
-- Customer_Name
-- Total_Ticket_Amount

WITH CTE AS (
	SELECT C.Customer_ID, C.Customer_Name,
		   SUM(M.Ticket_Amount) AS Total_Ticket_Amount
	FROM Customers C
	INNER JOIN Movie_Bookings M
		ON C.Customer_ID = M.Customer_ID
	GROUP BY C.Customer_ID, C.Customer_Name
),
CTE2 AS (
	SELECT *,
		   DENSE_RANK() OVER(ORDER BY Total_Ticket_Amount DESC) AS D_Rank
	FROM CTE
)
SELECT Customer_ID, Customer_Name, Total_Ticket_Amount
FROM CTE2
WHERE D_Rank <= 3;


-- Q4
-- Find customers who booked a movie within 2 days
-- of their previous booking.
--
-- Use JOIN + LAG().
--
-- Return:
-- Customer_ID
-- Customer_Name

WITH CTE AS (
	SELECT C.Customer_ID, C.Customer_Name, M.Booking_Date,
		   LAG(M.Booking_Date) OVER(PARTITION BY C.Customer_ID
           ORDER BY M.Booking_Date, M.Booking_ID) AS Previous
	FROM Customers C
	INNER JOIN Movie_Bookings M
		ON C.Customer_ID = M.Customer_ID
)
SELECT DISTINCT Customer_ID, Customer_Name
FROM CTE
WHERE Previous IS NOT NULL
AND DATEDIFF(Booking_Date, Previous) <= 2;


-- Q5 (COHORT ANALYSIS)
-- For each cohort month, find:
-- total customers
-- and total ticket revenue generated by those customers.
--
-- Definition:
-- Cohort Month = Month in which the customer joined.
--
-- Use both tables.
--
-- Return:
-- Cohort_Month
-- Total_Customers
-- Total_Ticket_Revenue

WITH CTE AS (
	SELECT C.Customer_ID,
		   MIN(M.Booking_Date) AS First_Booking_Date
	FROM Customers C
	INNER JOIN Movie_Bookings M
		ON C.Customer_ID = M.Customer_ID
	GROUP BY C.Customer_ID
),
CTE2 AS (
	SELECT *,
		   DATE_FORMAT(First_Booking_Date, '%Y-%m') AS Cohort_Month
	FROM CTE
)
SELECT Cohort_Month,
	   COUNT(DISTINCT CT.Customer_ID) AS Total_Customers,
       SUM(B.Ticket_Amount) AS Total_Ticket_Revenue
FROM CTE2 CT
INNER JOIN Movie_Bookings B
	ON CT.Customer_ID = B.Customer_ID
GROUP BY Cohort_Month;


-- BONUS (GAP & ISLAND)
-- Find the start date and end date of each customer's
-- longest booking streak.
--
-- Return:
-- Customer_ID
-- Customer_Name
-- Longest_Streak
-- Start_Date
-- End_Date
--
-- Note:
-- Ignore duplicate booking dates if a customer
-- has multiple bookings on the same day.
--
-- If multiple streaks have the same length,
-- return the most recent streak.

WITH CTE AS (
	SELECT DISTINCT C.Customer_ID, C.Customer_Name, M.Booking_Date
    FROM Customers C
	INNER JOIN Movie_Bookings M
		ON C.Customer_ID = M.Customer_ID
),
CTE2 AS (
	SELECT *,
		   ROW_NUMBER() OVER(PARTITION BY Customer_ID
           ORDER BY Booking_Date) AS RN
	FROM CTE
),
CTE3 AS (
	SELECT *,
		   DATE_SUB(Booking_Date, INTERVAL RN DAY) AS GK
	FROM CTE2
),
CTE4 AS (
	SELECT Customer_ID, Customer_Name,
		   COUNT(*) AS Streak,
		   MIN(Booking_Date) AS Start_Date,
           MAX(Booking_Date) AS End_Date
	FROM CTE3
    GROUP BY Customer_ID, Customer_Name, GK
),
CTE5 AS (
	SELECT *,
		   ROW_NUMBER() OVER(PARTITION BY Customer_ID
           ORDER BY Streak DESC, End_Date DESC) AS Row_Num
	FROM CTE4
)
SELECT Customer_ID, Customer_Name, Streak AS Longest_Streak,
	   Start_Date, End_Date
FROM CTE5
WHERE Row_Num = 1;