USE Daily_SQL;

-- DATABASE: Online Shopping

CREATE TABLE Customers (
    Customer_ID INT PRIMARY KEY,
    Customer_Name VARCHAR(100),
    City VARCHAR(50),
    Join_Date DATE
);

CREATE TABLE Orders (
    Order_ID INT PRIMARY KEY,
    Customer_ID INT,
    Product_Category VARCHAR(50),
    Order_Date DATE,
    Order_Amount DECIMAL(10,2),
    FOREIGN KEY (Customer_ID) REFERENCES Customers(Customer_ID)
);

INSERT INTO Customers 
VALUES	(101,'Alice','Chennai','2024-01-10'),
		(102,'Bob','Bangalore','2024-01-15'),
		(103,'Charlie','Hyderabad','2024-02-01'),
		(104,'David','Mumbai','2024-02-10'),
		(105,'Eva','Delhi','2024-02-15'),
		(106,'Frank','Chennai','2024-03-01'),
		(107,'Grace','Pune','2024-03-08'),
		(108,'Henry','Kolkata','2024-03-15'),
		(109,'Ivy','Jaipur','2024-04-01'),
		(110,'Jack','Coimbatore','2024-04-10');

INSERT INTO Orders
VALUES	(1,101,'Electronics','2024-05-01',25000),
		(2,101,'Electronics','2024-05-02',18000),
		(3,101,'Accessories','2024-05-03',2000),

		(4,102,'Fashion','2024-05-05',3500),
		(5,102,'Fashion','2024-05-07',4200),

		(6,103,'Electronics','2024-05-08',30000),
		(7,103,'Electronics','2024-05-09',22000),
		(8,103,'Accessories','2024-05-10',1500),

		(9,104,'Home','2024-05-12',8000),
		(10,104,'Furniture','2024-05-13',15000),

		(11,105,'Fashion','2024-05-15',5000),

		(12,106,'Books','2024-05-18',1200),
		(13,106,'Books','2024-05-19',1800),

		(14,107,'Electronics','2024-05-20',27000),

		(15,108,'Home','2024-05-22',6500),
		(16,108,'Home','2024-05-23',7200),
		(17,108,'Home','2024-05-24',8100),

		(18,109,'Accessories','2024-05-26',2500),
		(19,109,'Fashion','2024-05-27',4500),

		(20,110,'Furniture','2024-05-29',20000);
        
SELECT *
FROM Customers;

SELECT *
FROM Orders;

-- Q1
-- Show each customer's total orders,
-- total order amount, and average order amount.
--
-- Use both tables.
--
-- Return:
-- Customer_ID
-- Customer_Name
-- Total_Orders
-- Total_Order_Amount
-- Average_Order_Amount

SELECT C.Customer_ID, C.Customer_Name,
	   COUNT(O.Order_ID) AS Total_Orders,
       SUM(O.Order_Amount) AS Total_Order_Amount,
       ROUND(AVG(O.Order_Amount), 2) AS Average_Order_Amount
FROM Customers C
INNER JOIN Orders O
	ON C.Customer_ID = O.Customer_ID
GROUP BY C.Customer_ID, C.Customer_Name;


-- Q2
-- Show each product category's total orders
-- and total revenue.
--
-- Use both tables.
--
-- Return:
-- Product_Category
-- Total_Orders
-- Total_Revenue

SELECT O.Product_Category,
	   COUNT(O.Order_ID) AS Total_Orders,
       SUM(O.Order_Amount) AS Total_Revenue
FROM Customers C
INNER JOIN Orders O
	ON C.Customer_ID = O.Customer_ID
GROUP BY O.Product_Category;


-- Q3
-- Find the top 3 customers by total order amount.
--
-- Use DENSE_RANK().
--
-- Return:
-- Customer_ID
-- Customer_Name
-- Total_Order_Amount

WITH CTE AS (
	SELECT C.Customer_ID, C.Customer_Name,
		   SUM(O.Order_Amount) AS Total_Order_Amount
	FROM Customers C
	INNER JOIN Orders O
		ON C.Customer_ID = O.Customer_ID
	GROUP BY C.Customer_ID, C.Customer_Name
),
CTE2 AS (
	SELECT *,
		   DENSE_RANK() OVER(ORDER BY Total_Order_Amount DESC) AS D_Rank
	FROM CTE
)
SELECT Customer_ID, Customer_Name, Total_Order_Amount
FROM CTE2
WHERE D_Rank <= 3;


-- Q4
-- Find customers who placed an order within 2 days
-- of their previous order.
--
-- Use JOIN + LAG().
--
-- Return:
-- Customer_ID
-- Customer_Name

WITH CTE AS (
	SELECT C.Customer_ID, C.Customer_Name, O.Order_Date,
		   LAG(O.Order_Date) OVER(PARTITION BY C.Customer_ID
           ORDER BY O.Order_Date, O.Order_ID) AS Previous
	FROM Customers C
	INNER JOIN Orders O
		ON C.Customer_ID = O.Customer_ID
)
SELECT DISTINCT Customer_ID, Customer_Name
FROM CTE
WHERE Previous IS NOT NULL
AND DATEDIFF(Order_Date, Previous) <= 2;


-- Q5 (COHORT ANALYSIS)
-- For each cohort month, find:
-- total customers
-- and total order revenue generated by those customers.
--
-- Definition:
-- Cohort Month = Month in which the customer joined.
--
-- Use both tables.
--
-- Return:
-- Cohort_Month
-- Total_Customers
-- Total_Order_Revenue

WITH CTE AS (
    SELECT Customer_ID,
           DATE_FORMAT(Join_Date, '%Y-%m') AS Cohort_Month
    FROM Customers
)
SELECT Cohort_Month,
       COUNT(DISTINCT C.Customer_ID) AS Total_Customers,
       SUM(O.Order_Amount) AS Total_Order_Revenue
FROM CTE C
INNER JOIN Orders O
    ON C.Customer_ID = O.Customer_ID
GROUP BY Cohort_Month;


-- BONUS (GAP & ISLAND)
-- Find the start date and end date of each customer's
-- current order streak.
--
-- Return:
-- Customer_ID
-- Customer_Name
-- Current_Streak
-- Start_Date
-- End_Date
--
-- Definition:
-- Current streak = streak containing the customer's
-- most recent order date.
--
-- Note:
-- Ignore duplicate order dates if a customer
-- has multiple orders on the same day.
--
-- Return only customers whose Current_Streak >= 3.

WITH CTE AS (
	SELECT DISTINCT C.Customer_ID, C.Customer_Name, O.Order_Date
	FROM Customers C
	INNER JOIN Orders O
		ON C.Customer_ID = O.Customer_ID
),
CTE2 AS (
	SELECT *,
		   ROW_NUMBER() OVER(PARTITION BY Customer_ID
           ORDER BY Order_Date) RN
	FROM CTE
),
CTE3 AS (
	SELECT *,
		   DATE_SUB(Order_Date, INTERVAL RN DAY) AS GK
	FROM CTE2
),
CTE4 AS (
	SELECT Customer_ID, Customer_Name,
		   COUNT(*) AS Streak,
           MIN(Order_Date) AS Start_Date,
           MAX(Order_Date) AS End_Date
	FROM CTE3
    GROUP BY Customer_ID, Customer_Name, GK
),
CTE5 AS (
	SELECT *,
		   ROW_NUMBER() OVER(PARTITION BY Customer_ID
           ORDER BY End_Date DESC) AS Row_Num
	FROM CTE4
)
SELECT Customer_ID, Customer_Name, Streak AS Current_Streak,
	   Start_Date, End_Date
FROM CTE5
WHERE Row_Num = 1
AND Streak >= 3;