USE Daily_SQL;

-- DATABASE: Car Rental System

CREATE TABLE Customers (
    Customer_ID INT PRIMARY KEY,
    Customer_Name VARCHAR(100),
    City VARCHAR(50),
    Join_Date DATE
);

CREATE TABLE Rentals (
    Rental_ID INT PRIMARY KEY,
    Customer_ID INT,
    Car_Type VARCHAR(50),
    Rental_Date DATE,
    Rental_Amount DECIMAL(10,2),
    FOREIGN KEY (Customer_ID) REFERENCES Customers(Customer_ID)
);

INSERT INTO Customers 
VALUES	(101,'Alice','Chennai','2024-01-05'),
		(102,'Bob','Bangalore','2024-01-18'),
		(103,'Charlie','Hyderabad','2024-02-02'),
		(104,'David','Mumbai','2024-02-12'),
		(105,'Eva','Delhi','2024-02-20'),
		(106,'Frank','Pune','2024-03-03'),
		(107,'Grace','Kolkata','2024-03-10'),
		(108,'Henry','Coimbatore','2024-03-18'),
		(109,'Ivy','Jaipur','2024-04-01'),
		(110,'Jack','Kochi','2024-04-08');

INSERT INTO Rentals
VALUES	(1,101,'SUV','2024-05-01',5000),
		(2,101,'SUV','2024-05-02',5500),
		(3,101,'Sedan','2024-05-03',3500),

		(4,102,'Hatchback','2024-05-05',2500),
		(5,102,'SUV','2024-05-08',6000),

		(6,103,'Sedan','2024-05-10',4000),
		(7,103,'Sedan','2024-05-11',4200),
		(8,103,'SUV','2024-05-12',6500),

		(9,104,'Luxury','2024-05-15',12000),
		(10,104,'Luxury','2024-05-17',15000),

		(11,105,'SUV','2024-05-18',7000),

		(12,106,'Hatchback','2024-05-20',2800),
		(13,106,'Hatchback','2024-05-21',3000),

		(14,107,'Sedan','2024-05-22',4500),

		(15,108,'SUV','2024-05-24',6200),
		(16,108,'SUV','2024-05-25',6100),
		(17,108,'SUV','2024-05-26',6400),

		(18,109,'Luxury','2024-05-28',14000),
		(19,109,'Sedan','2024-05-29',3900),

		(20,110,'Hatchback','2024-05-30',2600);
        
SELECT *
FROM Customers;

SELECT *
FROM Rentals;

-- Q1
-- Show each customer's total rentals,
-- total rental amount, and average rental amount.
--
-- Use both tables.
--
-- Return:
-- Customer_ID
-- Customer_Name
-- Total_Rentals
-- Total_Rental_Amount
-- Average_Rental_Amount

SELECT C.Customer_ID, C.Customer_Name,
	   COUNT(R.Rental_ID) AS Total_Rentals,
       SUM(R.Rental_Amount) AS Total_Rental_Amount,
       ROUND(AVG(R.Rental_Amount), 2) AS Average_Rental_Amount
FROM Customers C
INNER JOIN Rentals R
	ON C.Customer_ID = R.Customer_ID
GROUP BY C.Customer_ID, C.Customer_Name;


-- Q2
-- Show each car type's total rentals
-- and total rental revenue.
--
-- Use both tables.
--
-- Return:
-- Car_Type
-- Total_Rentals
-- Total_Rental_Revenue

SELECT R.Car_Type,
	   COUNT(R.Rental_ID) AS Total_Rentals,
       SUM(R.Rental_Amount) AS Total_Rental_Revenue
FROM Customers C
INNER JOIN Rentals R
	ON C.Customer_ID = R.Customer_ID
GROUP BY R.Car_Type;


-- Q3
-- Find the top 3 customers by total rental amount.
--
-- Use DENSE_RANK().
--
-- Return:
-- Customer_ID
-- Customer_Name
-- Total_Rental_Amount

WITH CTE AS (
	SELECT C.Customer_ID, C.Customer_Name,
		   SUM(R.Rental_Amount) AS Total_Rental_Amount
	FROM Customers C
	INNER JOIN Rentals R
		ON C.Customer_ID = R.Customer_ID
	GROUP BY C.Customer_ID, C.Customer_Name
),
CTE2 AS (
	SELECT *,
		   DENSE_RANK() OVER(ORDER BY Total_Rental_Amount DESC) AS D_Rank
	FROM CTE
)
SELECT Customer_ID, Customer_Name, Total_Rental_Amount
FROM CTE2
WHERE D_Rank <= 3;


-- Q4
-- Find customers who rented a car within 2 days
-- of their previous rental.
--
-- Use JOIN + LAG().
--
-- Return:
-- Customer_ID
-- Customer_Name

WITH CTE AS (
	SELECT C.Customer_ID, C.Customer_Name, R.Rental_Date,
		   LAG(R.Rental_Date) OVER(PARTITION BY C.Customer_ID
           ORDER BY R.Rental_Date, R.Rental_ID) AS Previous
	FROM Customers C
	INNER JOIN Rentals R
		ON C.Customer_ID = R.Customer_ID
)
SELECT DISTINCT Customer_ID, Customer_Name
FROM CTE
WHERE Previous IS NOT NULL
AND DATEDIFF(Rental_Date, Previous) <= 2;


-- Q5 (COHORT ANALYSIS)
-- For each cohort month, find:
-- total customers
-- and total rental revenue generated by those customers.
--
-- Definition:
-- Cohort Month = Month in which the customer joined.
--
-- Use both tables.
--
-- Return:
-- Cohort_Month
-- Total_Customers
-- Total_Rental_Revenue

WITH CTE AS (
	SELECT Customer_ID,
		   DATE_FORMAT(Join_Date, '%Y-%m') AS Cohort_Month
	FROM Customers
)
SELECT Cohort_Month,
	   COUNT(DISTINCT C.Customer_ID) AS Total_Customers,
       SUM(R.Rental_Amount) AS Total_Rental_Revenue
FROM CTE C
INNER JOIN Rentals R
	ON C.Customer_ID = R.Customer_ID
GROUP BY Cohort_Month;


-- BONUS (GAP & ISLAND)
-- Find the start date and end date of each customer's
-- longest rental streak.
--
-- Return:
-- Customer_ID
-- Customer_Name
-- Longest_Streak
-- Start_Date
-- End_Date
--
-- Note:
-- Ignore duplicate rental dates if a customer
-- has multiple rentals on the same day.
--
-- If multiple streaks have the same length,
-- return the most recent streak.

WITH CTE AS (
	SELECT DISTINCT C.Customer_ID, C.Customer_Name, R.Rental_Date
	FROM Customers C
	INNER JOIN Rentals R
		ON C.Customer_ID = R.Customer_ID
),
CTE2 AS (
	SELECT *,
		   ROW_NUMBER() OVER(PARTITION BY Customer_ID
           ORDER BY Rental_Date) AS RN
	FROM CTE
),
CTE3 AS (
	SELECT *,
		   DATE_SUB(Rental_Date, INTERVAL RN DAY) AS GK
	FROM CTE2
),
CTE4 AS (
	SELECT Customer_ID, Customer_Name,
		   COUNT(*) AS Streak,
           MIN(Rental_Date) AS Start_Date,
		   MAX(Rental_Date) AS End_Date
	FROM CTE3
    GROUP BY Customer_ID, Customer_Name, GK
),
CTE5 AS (
	SELECT *,
		   ROW_NUMBER() OVER(PARTITION BY Customer_ID
           ORDER BY Streak DESC, End_Date DESC) AS Row_Num
	FROM CTE4
)
SELECT Customer_ID, Customer_Name, Streak AS Longest_Streak,
	   Start_Date, End_Date
FROM CTE5
WHERE Row_Num = 1;