USE Daily_SQL;

-- DATASET: Airline Ticket Booking System

CREATE TABLE Customers (
    Customer_ID INT PRIMARY KEY,
    Customer_Name VARCHAR(100),
    City VARCHAR(50),
    Join_Date DATE
);

CREATE TABLE Bookings (
    Booking_ID INT PRIMARY KEY,
    Customer_ID INT,
    Flight_Class VARCHAR(30),
    Booking_Date DATE,
    Ticket_Amount DECIMAL(10,2),
    FOREIGN KEY (Customer_ID) REFERENCES Customers(Customer_ID)
);

INSERT INTO Customers
VALUES	(101,'Alice','Chennai','2024-01-05'),
		(102,'Bob','Bangalore','2024-01-15'),
		(103,'Charlie','Hyderabad','2024-02-01'),
		(104,'David','Mumbai','2024-02-12'),
		(105,'Eva','Delhi','2024-02-25'),
		(106,'Frank','Pune','2024-03-05'),
		(107,'Grace','Kolkata','2024-03-18'),
		(108,'Henry','Coimbatore','2024-04-01'),
		(109,'Ivy','Jaipur','2024-04-10'),
		(110,'Jack','Kochi','2024-04-20');

INSERT INTO Bookings
VALUES	(1,101,'Economy','2024-05-01',4500),
		(2,101,'Economy','2024-05-02',4700),
		(3,101,'Business','2024-05-03',12000),

		(4,102,'Economy','2024-05-05',5200),
		(5,102,'Business','2024-05-08',15000),

		(6,103,'Economy','2024-05-10',4300),
		(7,103,'Economy','2024-05-11',4400),
		(8,103,'Economy','2024-05-12',4600),

		(9,104,'First Class','2024-05-14',25000),
		(10,104,'Business','2024-05-16',18000),

		(11,105,'Economy','2024-05-18',5100),

		(12,106,'Business','2024-05-20',14000),
		(13,106,'Business','2024-05-21',14500),

		(14,107,'Economy','2024-05-23',4800),

		(15,108,'First Class','2024-05-25',26000),
		(16,108,'First Class','2024-05-26',25500),
		(17,108,'Business','2024-05-27',17000),

		(18,109,'Economy','2024-05-29',4900),
		(19,109,'Business','2024-05-30',16000),

		(20,110,'Economy','2024-05-31',5300);
        
SELECT *
FROM Customers;

SELECT *
FROM Bookings;

-- Q1
-- Show each customer's total bookings,
-- total ticket amount, and average ticket amount.
--
-- Use both tables.
--
-- Return:
-- Customer_ID
-- Customer_Name
-- Total_Bookings
-- Total_Ticket_Amount
-- Average_Ticket_Amount

SELECT C.Customer_ID, C.Customer_Name,
	   COUNT(B.Booking_ID) AS Total_Bookings,
       SUM(B.Ticket_Amount) AS Total_Ticket_Amount,
       ROUND(AVG(B.Ticket_Amount), 2) AS Average_Ticket_Amount
FROM Customers C
INNER JOIN Bookings B
	ON C.Customer_ID = B.Customer_ID
GROUP BY Customer_ID, Customer_Name;


-- Q2
-- Show each flight class's total bookings
-- and total ticket revenue.
--
-- Use both tables.
--
-- Return:
-- Flight_Class
-- Total_Bookings
-- Total_Ticket_Revenue

SELECT B.Flight_Class,
	   COUNT(B.Booking_ID) AS Total_Bookings,
       SUM(B.Ticket_Amount) AS Total_Ticket_Revenue
FROM Customers C
INNER JOIN Bookings B
	ON C.Customer_ID = B.Customer_ID
GROUP BY B.Flight_Class;


-- Q3
-- Find the top 3 customers by total ticket amount.
--
-- Use DENSE_RANK().
--
-- Return:
-- Customer_ID
-- Customer_Name
-- Total_Ticket_Amount

WITH CTE AS (
	SELECT C.Customer_ID, C.Customer_Name,
		   SUM(B.Ticket_Amount) AS Total_Ticket_Amount
	FROM Customers C
	INNER JOIN Bookings B
		ON C.Customer_ID = B.Customer_ID
	GROUP BY Customer_ID, Customer_Name
),
CTE2 AS (
	SELECT *,
		   DENSE_RANK() OVER(ORDER BY Total_Ticket_Amount DESC) AS D_Rank
	FROM CTE
)
SELECT Customer_ID, Customer_Name, Total_Ticket_Amount
FROM CTE2
WHERE D_Rank <= 3;


-- Q4
-- Find customers who booked a flight within 2 days
-- of their previous booking.
--
-- Use JOIN + LAG().
--
-- Return:
-- Customer_ID
-- Customer_Name

WITH CTE AS (
	SELECT C.Customer_ID, C.Customer_Name, B.Booking_Date,
		   LAG(B.Booking_Date) OVER(PARTITION BY C.Customer_ID
           ORDER BY B.Booking_Date, B.Booking_ID) AS Previous
	FROM Customers C
	INNER JOIN Bookings B
		ON C.Customer_ID = B.Customer_ID
),
CTE2 AS (
	SELECT *,
		   DATEDIFF(Booking_Date, Previous) AS Days_Gap
	FROM CTE
)
SELECT DISTINCT Customer_ID, Customer_Name
FROM CTE2
WHERE Days_Gap <= 2;


-- Q5 (COHORT ANALYSIS)
-- For each cohort month, find:
-- total customers
-- and total ticket revenue generated by those customers.
--
-- Definition:
-- Cohort Month = Month in which the customer joined.
--
-- Use both tables.
--
-- Return:
-- Cohort_Month
-- Total_Customers
-- Total_Ticket_Revenue

WITH CTE AS (
	SELECT Customer_ID,
		   DATE_FORMAT(Join_Date, '%Y-%m') AS Cohort_Month
	FROM Customers
)
SELECT Cohort_Month,
	   COUNT(DISTINCT C.Customer_ID) AS Total_Customers,
	   SUM(B.Ticket_Amount) AS Total_Ticket_Revenue
FROM CTE C
INNER JOIN Bookings B
	ON C.Customer_ID = B.Customer_ID
GROUP BY Cohort_Month;


-- BONUS (GAP & ISLAND)
-- Find the start date and end date of each customer's
-- current booking streak.
--
-- Return:
-- Customer_ID
-- Customer_Name
-- Current_Streak
-- Start_Date
-- End_Date
--
-- Definition:
-- Current streak = streak containing the customer's
-- most recent booking date.
--
-- Note:
-- Ignore duplicate booking dates if a customer
-- has multiple bookings on the same day.
--
-- Return only customers whose Current_Streak >= 3.

WITH CTE AS (
	SELECT DISTINCT C.Customer_ID, C.Customer_Name, B.Booking_Date
    FROM Customers C
	INNER JOIN Bookings B
		ON C.Customer_ID = B.Customer_ID
),
CTE2 AS (
	SELECT *,
		   ROW_NUMBER() OVER(PARTITION BY Customer_ID
           ORDER BY Booking_Date) AS RN
	FROM CTE
),
CTE3 AS (
	SELECT *,
		   DATE_SUB(Booking_Date, INTERVAL RN DAY) AS GK
	FROM CTE2
),
CTE4 AS (
	SELECT Customer_ID, Customer_Name,
		   COUNT(*) AS Streak,
           MIN(Booking_Date) AS Start_Date,
           MAX(Booking_Date) AS End_Date
	FROM CTE3
    GROUP BY Customer_ID, Customer_Name, GK
),
CTE5 AS (
	SELECT *,
		   ROW_NUMBER() OVER(PARTITION BY Customer_ID
           ORDER BY End_Date DESC) AS Row_Num
	FROM CTE4
)
SELECT Customer_ID, Customer_Name, Streak AS Current_Streak,
	   Start_Date, End_Date
FROM CTE5
WHERE Row_Num = 1
AND Streak >= 3;

-- BONUS+
-- Find the customer(s) who spent more than the
-- average total spending of all customers.
--
-- Return:
-- Customer_ID
-- Customer_Name
-- Total_Ticket_Amount

WITH CTE AS (
	SELECT C.Customer_ID, C.Customer_Name,
		   SUM(B.Ticket_Amount) AS Total_Ticket_Amount
	FROM Customers C
	INNER JOIN Bookings B
		ON C.Customer_ID = B.Customer_ID
	GROUP BY Customer_ID, Customer_Name
)
SELECT *
FROM CTE
WHERE Total_Ticket_Amount > (
	SELECT AVG(Total_Ticket_Amount)
    FROM CTE
);

-- INTERVIEW QUESTION
--
-- Find customers whose total ticket amount
-- is greater than the average total ticket amount
-- of customers in the same city.
--
-- Use both tables.
--
-- Return:
-- Customer_ID
-- Customer_Name
-- City
-- Total_Ticket_Amount


WITH CTE AS (
    SELECT C.Customer_ID, C.Customer_Name, C.City,
           SUM(B.Ticket_Amount) AS Total_Ticket_Amount
    FROM Customers C
    INNER JOIN Bookings B
        ON C.Customer_ID = B.Customer_ID
    GROUP BY C.Customer_ID, C.Customer_Name, C.City
)
SELECT *
FROM (
    SELECT *,
           AVG(Total_Ticket_Amount) OVER(PARTITION BY City) AS City_Avg
    FROM CTE
) T
WHERE Total_Ticket_Amount > City_Avg;
