USE Daily_SQL;

-- DATASET: Online Grocery Orders

CREATE TABLE Customers (
    Customer_ID INT PRIMARY KEY,
    Customer_Name VARCHAR(100),
    City VARCHAR(50),
    Join_Date DATE
);

CREATE TABLE Orders (
    Order_ID INT PRIMARY KEY,
    Customer_ID INT,
    Product_Category VARCHAR(50),
    Order_Date DATE,
    Order_Amount DECIMAL(10,2),
    FOREIGN KEY (Customer_ID) REFERENCES Customers(Customer_ID)
);

INSERT INTO Customers
VALUES	(101,'Alice','Chennai','2024-01-05'),
		(102,'Bob','Bangalore','2024-01-12'),
		(103,'Charlie','Hyderabad','2024-02-03'),
		(104,'David','Mumbai','2024-02-15'),
		(105,'Eva','Delhi','2024-03-01'),
		(106,'Frank','Pune','2024-03-10'),
		(107,'Grace','Chennai','2024-03-22'),
		(108,'Henry','Bangalore','2024-04-05'),
		(109,'Ivy','Hyderabad','2024-04-18'),
		(110,'Jack','Mumbai','2024-05-01');

INSERT INTO Orders
VALUES	(1,101,'Vegetables','2024-06-01',450),
		(2,101,'Fruits','2024-06-02',320),
		(3,101,'Dairy','2024-06-03',280),

		(4,102,'Snacks','2024-06-04',550),
		(5,102,'Beverages','2024-06-07',430),

		(6,103,'Vegetables','2024-06-08',620),
		(7,103,'Vegetables','2024-06-09',510),
		(8,103,'Fruits','2024-06-10',390),

		(9,104,'Household','2024-06-11',1200),
		(10,104,'Dairy','2024-06-13',310),

		(11,105,'Snacks','2024-06-15',480),

		(12,106,'Beverages','2024-06-17',650),
		(13,106,'Beverages','2024-06-18',720),

		(14,107,'Vegetables','2024-06-20',560),

		(15,108,'Household','2024-06-22',1350),
		(16,108,'Household','2024-06-23',1280),
		(17,108,'Snacks','2024-06-24',430),

		(18,109,'Fruits','2024-06-26',370),
		(19,109,'Vegetables','2024-06-27',520),

		(20,110,'Dairy','2024-06-29',340);
        
SELECT *
FROM Customers;

SELECT *
FROM Orders;

-- Q1
-- Show each customer's total orders,
-- total order amount, and average order amount.
--
-- Use both tables.
--
-- Return:
-- Customer_ID
-- Customer_Name
-- Total_Orders
-- Total_Order_Amount
-- Average_Order_Amount

SELECT C.Customer_ID, C.Customer_Name,
	   COUNT(O.Order_ID) AS Total_Orders,
       SUM(O.Order_Amount) AS Total_Order_Amount,
       ROUND(AVG(O.Order_Amount), 2) AS Average_Order_Amount
FROM Customers C
INNER JOIN Orders O
	ON C.Customer_ID = O.Customer_ID
GROUP BY C.Customer_ID, C.Customer_Name;


-- Q2
-- Show each product category's total orders
-- and total order revenue.
--
-- Return:
-- Product_Category
-- Total_Orders
-- Total_Order_Revenue

SELECT Product_Category,
	   COUNT(Order_ID) AS Total_Orders,
       SUM(Order_Amount) AS Total_Order_Revenue
FROM Orders
GROUP BY Product_Category;


-- Q3
-- Find the top 3 customers by total order amount.
--
-- Use DENSE_RANK().
--
-- Return:
-- Customer_ID
-- Customer_Name
-- Total_Order_Amount

WITH CTE AS (
	SELECT C.Customer_ID, C.Customer_Name,
		   SUM(O.Order_Amount) AS Total_Order_Amount
	FROM Customers C
	INNER JOIN Orders O
		ON C.Customer_ID = O.Customer_ID
	GROUP BY C.Customer_ID, C.Customer_Name
),
CTE2 AS (
	SELECT *,
		   DENSE_RANK() OVER(ORDER BY Total_Order_Amount DESC) AS D_Rank
	FROM CTE
)
SELECT Customer_ID, Customer_Name, Total_Order_Amount
FROM CTE2
WHERE D_Rank <= 3;


-- Q4
-- Find customers who placed an order within 2 days
-- of their previous order.
--
-- Use JOIN + LAG().
--
-- Return:
-- Customer_ID
-- Customer_Name

WITH CTE AS (
	SELECT C.Customer_ID, C.Customer_Name, O.Order_Date,
		   LAG(O.Order_Date) OVER(PARTITION BY C.Customer_ID
           ORDER BY O.Order_Date, Order_ID) AS Previous
	FROM Customers C
	INNER JOIN Orders O
		ON C.Customer_ID = O.Customer_ID
)
SELECT DISTINCT Customer_ID, Customer_Name
FROM CTE
WHERE Previous IS NOT NULL
AND DATEDIFF(Order_Date, Previous) <= 2;


-- Q5 (COHORT ANALYSIS)
-- For each cohort month, find:
-- total customers
-- and total order revenue generated by those customers.
--
-- Definition:
-- Cohort Month = Month in which the customer joined.
--
-- Use both tables.
--
-- Return:
-- Cohort_Month
-- Total_Customers
-- Total_Order_Revenue

WITH CTE AS (
	SELECT Customer_ID,
		   DATE_FORMAT(Join_Date, '%Y-%m') AS Cohort_Month
	FROM Customers
)
SELECT Cohort_Month,
	   COUNT(DISTINCT C.Customer_ID) AS Total_Customers,
       SUM(O.Order_Amount) AS Total_Order_Revenue
FROM CTE C
INNER JOIN Orders O
	ON C.Customer_ID = O.Customer_ID
GROUP BY Cohort_Month;


-- BONUS (GAP & ISLAND)
-- Find the start date and end date of each customer's
-- longest order streak.
--
-- Return:
-- Customer_ID
-- Customer_Name
-- Longest_Streak
-- Start_Date
-- End_Date
--
-- Note:
-- Ignore duplicate order dates if a customer
-- has multiple orders on the same day.
--
-- If multiple streaks have the same length,
-- return the most recent streak.

WITH CTE AS (
	SELECT DISTINCT C.Customer_ID, C.Customer_Name, O.Order_Date
    FROM Customers C
	INNER JOIN Orders O
		ON C.Customer_ID = O.Customer_ID
),
CTE2 AS (
	SELECT *,
		   ROW_NUMBER() OVER(PARTITION BY Customer_ID
           ORDER BY Order_Date) AS RN
	FROM CTE
),
CTE3 AS (
	SELECT *,
		   DATE_SUB(Order_Date, INTERVAL RN DAY) AS GK
	FROM CTE2
),
CTE4 AS (
	SELECT Customer_ID, Customer_Name,
		   COUNT(*) AS Streak,
           MIN(Order_Date) AS Start_Date,
           MAX(Order_Date) AS End_Date
	FROM CTE3
    GROUP BY Customer_ID, Customer_Name, GK
),
CTE5 AS (
	SELECT *,
		   ROW_NUMBER() OVER(PARTITION BY Customer_ID
           ORDER BY Streak DESC, End_Date DESC) AS Row_Num
	FROM CTE4
)
SELECT Customer_ID, Customer_Name, Streak AS Longest_Streak,
	   Start_Date, End_Date
FROM CTE5
WHERE Row_Num = 1;


-- BONUS+
-- Find customers whose total order amount
-- is greater than the average total order amount
-- of customers in the same city.
--
-- Return:
-- Customer_ID
-- Customer_Name
-- City
-- Total_Order_Amount

WITH CTE AS (
	SELECT C.Customer_ID, C.Customer_Name, C.City,
		   SUM(O.Order_Amount) AS Total_Order_Amount
	FROM Customers C
	INNER JOIN Orders O
		ON C.Customer_ID = O.Customer_ID
	GROUP BY C.Customer_ID, C.Customer_Name, C.City
),
CTE2 AS (
	SELECT *,
		   AVG(Total_Order_Amount) OVER(PARTITION BY City) AS Avg_City
	FROM CTE
)
SELECT Customer_ID, Customer_Name, City, Total_Order_Amount
FROM CTE2
WHERE Total_Order_Amount > Avg_City;