USE Daily_SQL;

-- DATASET: Gym Memberships

CREATE TABLE Members (
    Member_ID INT PRIMARY KEY,
    Member_Name VARCHAR(100),
    City VARCHAR(50),
    Join_Date DATE
);

CREATE TABLE Memberships (
    Membership_ID INT PRIMARY KEY,
    Member_ID INT,
    Membership_Type VARCHAR(30),
    Purchase_Date DATE,
    Amount_Paid DECIMAL(10,2),
    FOREIGN KEY (Member_ID) REFERENCES Members(Member_ID)
);

INSERT INTO Members
VALUES	(101,'Alice','Chennai','2024-01-05'),
		(102,'Bob','Bangalore','2024-01-18'),
		(103,'Charlie','Hyderabad','2024-02-10'),
		(104,'David','Mumbai','2024-02-22'),
		(105,'Eva','Delhi','2024-03-04'),
		(106,'Frank','Pune','2024-03-15'),
		(107,'Grace','Chennai','2024-03-28'),
		(108,'Henry','Bangalore','2024-04-06'),
		(109,'Ivy','Hyderabad','2024-04-20'),
		(110,'Jack','Mumbai','2024-05-02');

INSERT INTO Memberships
VALUES	(1,101,'Monthly','2024-06-01',1200),
		(2,101,'Monthly','2024-06-02',1200),
		(3,101,'Quarterly','2024-06-03',3200),

		(4,102,'Monthly','2024-06-05',1200),
		(5,102,'Yearly','2024-06-08',12000),

		(6,103,'Monthly','2024-06-10',1200),
		(7,103,'Monthly','2024-06-11',1200),
		(8,103,'Monthly','2024-06-12',1200),

		(9,104,'Yearly','2024-06-14',12000),
		(10,104,'Monthly','2024-06-16',1200),

		(11,105,'Quarterly','2024-06-18',3200),

		(12,106,'Monthly','2024-06-20',1200),
		(13,106,'Monthly','2024-06-21',1200),

		(14,107,'Quarterly','2024-06-23',3200),

		(15,108,'Yearly','2024-06-25',12000),
		(16,108,'Yearly','2024-06-26',12000),
		(17,108,'Monthly','2024-06-27',1200),

		(18,109,'Monthly','2024-06-29',1200),
		(19,109,'Quarterly','2024-06-30',3200),

		(20,110,'Monthly','2024-07-02',1200);
        
SELECT *
FROM Members;

SELECT *
FROM Memberships;

-- Q1
-- Show each member's total memberships,
-- total amount paid, and average amount paid.
--
-- Use both tables.
--
-- Return:
-- Member_ID
-- Member_Name
-- Total_Memberships
-- Total_Amount_Paid
-- Average_Amount_Paid

SELECT M.Member_ID, M.Member_Name,
	   COUNT(B.Membership_ID) AS Total_Memberships,
       SUM(B.Amount_Paid) AS Total_Amount_Paid,
       ROUND(AVG(B.Amount_Paid), 2) AS Average_Amount_Paid
FROM Members M
INNER JOIN Memberships B
	ON M.Member_ID = B.Member_ID
GROUP BY M.Member_ID, M.Member_Name;


-- Q2
-- Show each membership type's total purchases
-- and total revenue.
--
-- Return:
-- Membership_Type
-- Total_Purchases
-- Total_Revenue

SELECT Membership_Type,
	   COUNT(Membership_ID) AS Total_Purchases,
       SUM(Amount_Paid) AS Total_Revenue
FROM Memberships
GROUP BY Membership_Type;


-- Q3
-- Find the top 3 members by total amount paid.
--
-- Use DENSE_RANK().
--
-- Return:
-- Member_ID
-- Member_Name
-- Total_Amount_Paid

WITH CTE AS (
	SELECT M.Member_ID, M.Member_Name,
		   SUM(B.Amount_Paid) AS Total_Amount_Paid
	FROM Members M
	INNER JOIN Memberships B
		ON M.Member_ID = B.Member_ID
	GROUP BY M.Member_ID, M.Member_Name
),
CTE2 AS (
	SELECT *,
		   DENSE_RANK() OVER(ORDER BY Total_Amount_Paid DESC) AS D_Rank
	FROM CTE
)
SELECT Member_ID, Member_Name, Total_Amount_Paid
FROM CTE2
WHERE D_Rank <= 3;


-- Q4
-- Find members who purchased a membership
-- within 2 days of their previous purchase.
--
-- Use JOIN + LAG().
--
-- Return:
-- Member_ID
-- Member_Name

WITH CTE AS (
	SELECT M.Member_ID, M.Member_Name, B.Purchase_Date,
		   LAG(B.Purchase_Date) OVER(PARTITION BY M.Member_ID
           ORDER BY B.Purchase_Date, B.Membership_ID) AS Previous
	FROM Members M
	INNER JOIN Memberships B
		ON M.Member_ID = B.Member_ID
)
SELECT DISTINCT Member_ID, Member_Name
FROM CTE
WHERE Previous IS NOT NULL
AND DATEDIFF(Purchase_Date, Previous) <= 2;


-- Q5 (COHORT ANALYSIS)
-- For each cohort month, find:
-- total members
-- and total revenue generated by those members.
--
-- Definition:
-- Cohort Month = Month in which the member joined.
--
-- Use both tables.
--
-- Return:
-- Cohort_Month
-- Total_Members
-- Total_Revenue

WITH CTE AS (
	SELECT Member_ID,
		   DATE_FORMAT(Join_Date, '%Y-%m') AS Cohort_Month
	FROM Members
)
SELECT Cohort_Month,
	   COUNT(DISTINCT M.Member_ID) AS Total_Members,
       SUM(B.Amount_Paid) AS Total_Revenue
FROM CTE M
INNER JOIN Memberships B
	ON M.Member_ID = B.Member_ID
GROUP BY Cohort_Month;


-- BONUS (GAP & ISLAND)
-- Find the start date and end date of each member's
-- current membership purchase streak.
--
-- Return:
-- Member_ID
-- Member_Name
-- Current_Streak
-- Start_Date
-- End_Date
--
-- Definition:
-- Current streak = streak containing the member's
-- most recent purchase date.
--
-- Note:
-- Ignore duplicate purchase dates if a member
-- has multiple purchases on the same day.
--
-- Return only members whose Current_Streak >= 3.

WITH CTE AS (
	SELECT DISTINCT M.Member_ID, M.Member_Name, B.Purchase_Date
    FROM Members M
	INNER JOIN Memberships B
		ON M.Member_ID = B.Member_ID
),
CTE2 AS (
	SELECT *,
		   ROW_NUMBER() OVER(PARTITION BY Member_ID
           ORDER BY Purchase_Date) AS RN
	FROM CTE
),
CTE3 AS (
	SELECT *,
		   DATE_SUB(Purchase_Date, INTERVAL RN DAY) AS GK
	FROM CTE2
),
CTE4 AS (
	SELECT Member_ID, Member_Name,
		   COUNT(*) AS Streak,
           MIN(Purchase_Date) AS Start_Date,
           MAX(Purchase_Date) AS End_Date
	FROM CTE3
    GROUP BY Member_ID, Member_Name, GK
),
CTE5 AS (
	SELECT *,
		   ROW_NUMBER() OVER(PARTITION BY Member_ID
           ORDER BY End_Date DESC) AS Row_Num
	FROM CTE4
)
SELECT Member_ID, Member_Name, Streak AS Current_Streak,
	   Start_Date, End_Date
FROM CTE5
WHERE Row_Num = 1
AND Streak >= 3;


-- BONUS+
-- Find members whose total amount paid
-- is greater than the average total amount paid
-- of members in the same city.
--
-- Return:
-- Member_ID
-- Member_Name
-- City
-- Total_Amount_Paid

WITH CTE AS (
	SELECT M.Member_ID, M.Member_Name, M.City,
		   SUM(B.Amount_Paid) AS Total_Amount_Paid
	FROM Members M
	INNER JOIN Memberships B
		ON M.Member_ID = B.Member_ID
	GROUP BY M.Member_ID, M.Member_Name, M.City
),
CTE2 AS (
	SELECT *,
		   AVG(Total_Amount_Paid) OVER(PARTITION BY City) AS Avg_City
	FROM CTE
)
SELECT Member_ID, Member_Name, City, Total_Amount_Paid
FROM CTE2
WHERE Total_Amount_Paid > Avg_City;