USE Daily_SQL;

-- DATASET: Insurance Claims

CREATE TABLE Policyholders (
    Policyholder_ID INT PRIMARY KEY,
    Policyholder_Name VARCHAR(100),
    City VARCHAR(50),
    Policy_Start_Date DATE
);

CREATE TABLE Claims (
    Claim_ID INT PRIMARY KEY,
    Policyholder_ID INT,
    Claim_Type VARCHAR(50),
    Claim_Date DATE,
    Claim_Amount DECIMAL(10,2),
    FOREIGN KEY (Policyholder_ID)
        REFERENCES Policyholders(Policyholder_ID)
);

INSERT INTO Policyholders
VALUES	(101,'Alice','Chennai','2024-01-05'),
		(102,'Bob','Bangalore','2024-01-18'),
		(103,'Charlie','Hyderabad','2024-02-02'),
		(104,'David','Mumbai','2024-02-15'),
		(105,'Eva','Delhi','2024-03-01'),
		(106,'Frank','Pune','2024-03-12'),
		(107,'Grace','Chennai','2024-03-25'),
		(108,'Henry','Bangalore','2024-04-08'),
		(109,'Ivy','Hyderabad','2024-04-20'),
		(110,'Jack','Mumbai','2024-05-05');

INSERT INTO Claims
VALUES	(1,101,'Health','2024-06-01',1200),
		(2,101,'Health','2024-06-02',1800),
		(3,101,'Accident','2024-06-03',2500),

		(4,102,'Vehicle','2024-06-05',4200),
		(5,102,'Health','2024-06-08',1600),

		(6,103,'Property','2024-06-10',5100),
		(7,103,'Property','2024-06-11',3300),
		(8,103,'Health','2024-06-12',1700),

		(9,104,'Vehicle','2024-06-15',4600),
		(10,104,'Health','2024-06-18',1900),

		(11,105,'Accident','2024-06-20',2800),

		(12,106,'Health','2024-06-22',1400),
		(13,106,'Vehicle','2024-06-23',3800),

		(14,107,'Property','2024-06-25',5200),

		(15,108,'Vehicle','2024-06-27',6100),
		(16,108,'Vehicle','2024-06-28',4300),
		(17,108,'Health','2024-06-29',1500),

		(18,109,'Accident','2024-07-01',2600),
		(19,109,'Health','2024-07-02',1700),

		(20,110,'Property','2024-07-04',4900);
        
SELECT *
FROM Policyholders;

SELECT *
FROM Claims;

-- Q1
-- Show each policyholder's total claims,
-- total claim amount, and average claim amount.
--
-- Use both tables.
--
-- Return:
-- Policyholder_ID
-- Policyholder_Name
-- Total_Claims
-- Total_Claim_Amount
-- Average_Claim_Amount

SELECT P.Policyholder_ID, P.Policyholder_Name,
	   COUNT(C.Claim_ID) AS Total_Claims,
	   SUM(C.Claim_Amount) AS Total_Claim_Amount,
       ROUND(AVG(C.Claim_Amount), 2) AS Average_Claim_Amount
FROM Policyholders P
INNER JOIN Claims C
	ON P.Policyholder_ID = C.Policyholder_ID
GROUP BY P.Policyholder_ID, P.Policyholder_Name;


-- Q2
-- Show each claim type's total claims
-- and total claim amount.
--
-- Return:
-- Claim_Type
-- Total_Claims
-- Total_Claim_Amount

SELECT Claim_Type,
	   COUNT(C.Claim_ID) AS Total_Claims,
	   SUM(C.Claim_Amount) AS Total_Claim_Amount
FROM Policyholders P
INNER JOIN Claims C
	ON P.Policyholder_ID = C.Policyholder_ID
GROUP BY Claim_Type;


-- Q3
-- Find the top 3 policyholders by total claim amount.
--
-- Use DENSE_RANK().
--
-- Return:
-- Policyholder_ID
-- Policyholder_Name
-- Total_Claim_Amount

WITH CTE AS (
	SELECT P.Policyholder_ID, P.Policyholder_Name,
		   SUM(C.Claim_Amount) AS Total_Claim_Amount
	FROM Policyholders P
	INNER JOIN Claims C
		ON P.Policyholder_ID = C.Policyholder_ID
	GROUP BY P.Policyholder_ID, P.Policyholder_Name
),
CTE2 AS (
	SELECT *,
		   DENSE_RANK() OVER(ORDER BY Total_Claim_Amount DESC) AS D_Rank
	FROM CTE
)
SELECT Policyholder_ID, Policyholder_Name, Total_Claim_Amount
FROM CTE2
WHERE D_Rank <= 3;


-- Q4
-- Find policyholders who submitted a claim
-- within 2 days of their previous claim.
--
-- Use JOIN + LAG().
--
-- Return:
-- Policyholder_ID
-- Policyholder_Name

WITH CTE AS (
	SELECT P.Policyholder_ID, P.Policyholder_Name, C.Claim_Date,
		   LAG(C.Claim_Date) OVER(PARTITION BY P.Policyholder_ID
           ORDER BY C.Claim_Date, C.Claim_ID) AS Previous
    FROM Policyholders P
	INNER JOIN Claims C
		ON P.Policyholder_ID = C.Policyholder_ID
)
SELECT DISTINCT Policyholder_ID, Policyholder_Name
FROM CTE
WHERE Previous IS NOT NULL
AND DATEDIFF(Claim_Date, Previous) <= 2;


-- Q5 (COHORT ANALYSIS)
-- For each cohort month, find:
-- total policyholders
-- and total claim amount generated by those policyholders.
--
-- Definition:
-- Cohort Month = Month in which the policy started.
--
-- Use both tables.
--
-- Return:
-- Cohort_Month
-- Total_Policyholders
-- Total_Claim_Amount

WITH CTE AS (
	SELECT Policyholder_ID,
		   DATE_FORMAT(Policy_Start_Date, '%Y-%m') AS  Cohort_Month
	FROM Policyholders
)
SELECT Cohort_Month,
	   COUNT(DISTINCT C.Policyholder_ID) AS Total_Policyholders,
       SUM(CL.Claim_Amount) AS Total_Claim_Amount
FROM CTE C
INNER JOIN Claims CL
	ON C.Policyholder_ID = CL.Policyholder_ID
GROUP BY Cohort_Month;


-- BONUS (GAP & ISLAND)
-- Find the start date and end date of each policyholder's
-- longest claim streak.
--
-- Return:
-- Policyholder_ID
-- Policyholder_Name
-- Longest_Streak
-- Start_Date
-- End_Date
--
-- Note:
-- Ignore duplicate claim dates if a policyholder
-- has multiple claims on the same day.
--
-- If multiple streaks have the same length,
-- return the most recent streak.

WITH CTE AS (
	SELECT DISTINCT P.Policyholder_ID, P.Policyholder_Name, C.Claim_Date
    FROM Policyholders P
	INNER JOIN Claims C
		ON P.Policyholder_ID = C.Policyholder_ID
),
CTE2 AS (
	SELECT *,
		   ROW_NUMBER() OVER(PARTITION BY Policyholder_ID
           ORDER BY Claim_Date) AS RN
	FROM CTE
),
CTE3 AS (
	SELECT *,
		   DATE_SUB(Claim_Date, INTERVAL RN DAY) AS GK
	FROM CTE2
),
CTE4 AS (
	SELECT Policyholder_ID, Policyholder_Name,
		   COUNT(*) AS Streak,
           MIN(Claim_Date) AS Start_Date,
           MAX(Claim_Date) AS End_Date
	FROM CTE3
    GROUP BY Policyholder_ID, Policyholder_Name, GK
),
CTE5 AS (
	SELECT *,
		   ROW_NUMBER() OVER(PARTITION BY Policyholder_ID
           ORDER BY Streak DESC, End_Date DESC) AS Row_Num
	FROM CTE4
)
SELECT Policyholder_ID, Policyholder_Name, Streak AS Longest_Streak,
	   Start_Date, End_Date
FROM CTE5
WHERE Row_Num = 1;


-- BONUS+
-- Find policyholders whose total claim amount
-- is greater than the average total claim amount
-- of policyholders in the same city.
--
-- Return:
-- Policyholder_ID
-- Policyholder_Name
-- City
-- Total_Claim_Amount

WITH CTE AS (
	SELECT P.Policyholder_ID, P.Policyholder_Name, P.City,
		   SUM(C.Claim_Amount) AS Total_Claim_Amount
	FROM Policyholders P
	INNER JOIN Claims C
		ON P.Policyholder_ID = C.Policyholder_ID
	GROUP BY P.Policyholder_ID, P.Policyholder_Name, P.City
),
CTE2 AS (
	SELECT *,
		   AVG(Total_Claim_Amount) OVER(PARTITION BY City) AS Avg_City_Claims
	FROM CTE
)
SELECT Policyholder_ID, Policyholder_Name, City, Total_Claim_Amount
FROM CTE2
WHERE Total_Claim_Amount > Avg_City_Claims;