USE Daily_SQL;

-- DATASET: Library Borrowing System

CREATE TABLE Members (
    Member_ID INT PRIMARY KEY,
    Member_Name VARCHAR(100),
    City VARCHAR(50),
    Join_Date DATE
);

CREATE TABLE Borrowings (
    Borrow_ID INT PRIMARY KEY,
    Member_ID INT,
    Book_Category VARCHAR(50),
    Borrow_Date DATE,
    Fine_Amount DECIMAL(10,2),
    FOREIGN KEY (Member_ID) REFERENCES Members(Member_ID)
);

INSERT INTO Members
VALUES	(101,'Alice','Chennai','2024-01-08'),
		(102,'Bob','Bangalore','2024-01-18'),
		(103,'Charlie','Hyderabad','2024-02-04'),
		(104,'David','Mumbai','2024-02-20'),
		(105,'Eva','Delhi','2024-03-06'),
		(106,'Frank','Pune','2024-03-15'),
		(107,'Grace','Chennai','2024-03-28'),
		(108,'Henry','Bangalore','2024-04-10'),
		(109,'Ivy','Hyderabad','2024-04-24'),
		(110,'Jack','Mumbai','2024-05-05');

INSERT INTO Borrowings
VALUES	(1,101,'Science','2024-06-01',20),
		(2,101,'Science','2024-06-02',15),
		(3,101,'History','2024-06-03',25),

		(4,102,'Technology','2024-06-05',30),
		(5,102,'Science','2024-06-08',10),

		(6,103,'History','2024-06-10',40),
		(7,103,'History','2024-06-11',35),
		(8,103,'Science','2024-06-12',15),

		(9,104,'Technology','2024-06-15',50),
		(10,104,'Science','2024-06-18',20),

		(11,105,'Fiction','2024-06-20',25),

		(12,106,'Science','2024-06-22',15),
		(13,106,'Technology','2024-06-23',45),

		(14,107,'History','2024-06-25',30),

		(15,108,'Technology','2024-06-27',60),
		(16,108,'Technology','2024-06-28',40),
		(17,108,'Science','2024-06-29',20),

		(18,109,'Fiction','2024-07-01',35),
		(19,109,'Science','2024-07-02',10),

		(20,110,'History','2024-07-04',55);

SELECT *
FROM Members;

SELECT *
FROM Borrowings;

-- Q1
-- Show each member's total borrowings,
-- total fine amount, and average fine amount.
--
-- Use both tables.
--
-- Return:
-- Member_ID
-- Member_Name
-- Total_Borrowings
-- Total_Fine_Amount
-- Average_Fine_Amount

SELECT M.Member_ID, M.Member_Name,
	   COUNT(B.Borrow_ID) AS Total_Borrowings,
	   SUM(B.Fine_Amount) AS Total_Fine_Amount,
       ROUND(AVG(B.Fine_Amount), 2) AS Average_Fine_Amount
FROM Members M
INNER JOIN Borrowings B
	ON M.Member_ID = B.Member_ID
GROUP BY M.Member_ID, M.Member_Name;


-- Q2
-- Show each book category's total borrowings
-- and total fine amount.
--
-- Return:
-- Book_Category
-- Total_Borrowings
-- Total_Fine_Amount

SELECT Book_Category,
	   COUNT(Borrow_ID) AS Total_Borrowings,
	   SUM(Fine_Amount) AS Total_Fine_Amount
FROM Borrowings
GROUP BY Book_Category;


-- Q3
-- Find the top 3 members by total fine amount.
--
-- Use DENSE_RANK().
--
-- Return:
-- Member_ID
-- Member_Name
-- Total_Fine_Amount

WITH CTE AS (
	SELECT M.Member_ID, M.Member_Name,
		   SUM(B.Fine_Amount) AS Total_Fine_Amount
	FROM Members M
	INNER JOIN Borrowings B
		ON M.Member_ID = B.Member_ID
	GROUP BY M.Member_ID, M.Member_Name
),
CTE2 AS (
	SELECT *,
		   DENSE_RANK() OVER(ORDER BY Total_Fine_Amount DESC) AS D_Rank
	FROM CTE
)
SELECT Member_ID, Member_Name, Total_Fine_Amount
FROM CTE2
WHERE D_Rank <= 3;


-- Q4
-- Find members who borrowed books within 2 days
-- of their previous borrowing.
--
-- Use JOIN + LAG().
--
-- Return:
-- Member_ID
-- Member_Name

WITH CTE AS (
	SELECT M.Member_ID, M.Member_Name, B.Borrow_Date,
		   LAG(B.Borrow_Date) OVER(PARTITION BY M.Member_ID
           ORDER BY B.Borrow_Date, Borrow_ID) AS Previous
	FROM Members M
	INNER JOIN Borrowings B
		ON M.Member_ID = B.Member_ID
),
CTE2 AS (
	SELECT *,
		   DATEDIFF(Borrow_Date, Previous) AS Days_Gap
	FROM CTE
)
SELECT DISTINCT Member_ID, Member_Name
FROM CTE2
WHERE Previous IS NOT NULL
AND Days_Gap <= 2;


-- Q5 (COHORT ANALYSIS)
-- For each cohort month, find:
-- total members
-- and total fine amount generated by those members.
--
-- Definition:
-- Cohort Month = Month in which the member joined.
--
-- Use both tables.
--
-- Return:
-- Cohort_Month
-- Total_Members
-- Total_Fine_Amount

WITH CTE AS (
	SELECT Member_ID,
		   DATE_FORMAT(Join_Date, '%Y-%m') AS Cohort_Month
	FROM Members
)
SELECT Cohort_Month,
	   COUNT(DISTINCT C.Member_ID) AS Total_Members,
       SUM(B.Fine_Amount) AS Total_Fine_Amount
FROM CTE C
INNER JOIN Borrowings B
	ON C.Member_ID = B.Member_ID
GROUP BY Cohort_Month;


-- BONUS (GAP & ISLAND)
-- Find the start date and end date of each member's
-- current borrowing streak.
--
-- Return:
-- Member_ID
-- Member_Name
-- Current_Streak
-- Start_Date
-- End_Date
--
-- Definition:
-- Current streak = streak containing the member's
-- most recent borrowing date.
--
-- Note:
-- Ignore duplicate borrowing dates if a member
-- has multiple borrowings on the same day.
--
-- Return only members whose Current_Streak >= 3.

WITH CTE AS (
	SELECT DISTINCT M.Member_ID, M.Member_Name, B.Borrow_Date
    FROM Members M
	INNER JOIN Borrowings B
		ON M.Member_ID = B.Member_ID
),
CTE2 AS (
	SELECT *,
		   ROW_NUMBER() OVER(PARTITION BY Member_ID
           ORDER BY Borrow_Date) AS RN
	FROM CTE
),
CTE3 AS (
	SELECT *,
		   DATE_SUB(Borrow_Date, INTERVAL RN DAY) AS GK
	FROM CTE2
),
CTE4 AS (
	SELECT Member_ID, Member_Name,
		   COUNT(*) AS Streak,
           MIN(Borrow_Date) AS Start_Date,
           MAX(Borrow_Date) AS End_Date
	FROM CTE3
    GROUP BY Member_ID, Member_Name, GK
),
CTE5 AS (
	SELECT *,
		   ROW_NUMBER() OVER(PARTITION BY Member_ID
           ORDER BY End_Date DESC) AS Row_Num
	FROM CTE4
)
SELECT Member_ID, Member_Name, Streak AS Current_Streak,
	   Start_Date, End_Date
FROM CTE5
WHERE Row_Num = 1
AND Streak >= 3;


-- BONUS+
-- Find members whose total fine amount
-- is greater than the average total fine amount
-- of members in the same city.
--
-- Return:
-- Member_ID
-- Member_Name
-- City
-- Total_Fine_Amount

WITH CTE AS (
	SELECT M.Member_ID, M.Member_Name, M.City,
		   SUM(B.Fine_Amount) AS Total_Fine_Amount
	FROM Members M
	INNER JOIN Borrowings B
		ON M.Member_ID = B.Member_ID
	GROUP BY M.Member_ID, M.Member_Name, M.City
)
SELECT Member_ID, Member_Name, City, Total_Fine_Amount
FROM (
	SELECT *,
		   AVG(Total_Fine_Amount) OVER(PARTITION BY City) AS Avg_City
	FROM CTE
	)A
WHERE Total_Fine_Amount > Avg_City;