USE Daily_SQL;

-- DATASET: Hospital Appointments

CREATE TABLE Patients (
    Patient_ID INT PRIMARY KEY,
    Patient_Name VARCHAR(100),
    City VARCHAR(50),
    Registration_Date DATE
);

CREATE TABLE Appointments (
    Appointment_ID INT PRIMARY KEY,
    Patient_ID INT,
    Doctor_Name VARCHAR(100),
    Department VARCHAR(50),
    Appointment_Date DATE,
    Consultation_Fee DECIMAL(10,2),
    FOREIGN KEY (Patient_ID) REFERENCES Patients(Patient_ID)
);

INSERT INTO Patients
VALUES	(101,'Arun','Chennai','2024-01-05'),
		(102,'Divya','Bengaluru','2024-01-10'),
		(103,'Karthik','Chennai','2024-02-02'),
		(104,'Meena','Hyderabad','2024-02-15'),
		(105,'Rahul','Bengaluru','2024-03-01'),
		(106,'Sneha','Chennai','2024-03-18'),
		(107,'Vikram','Hyderabad','2024-04-06'),
		(108,'Priya','Chennai','2024-04-20'),
		(109,'Anil','Bengaluru','2024-05-04'),
		(110,'Neha','Hyderabad','2024-05-25');

INSERT INTO Appointments
VALUES	(1001,101,'Dr. Kumar','Cardiology','2024-01-06',1200),
		(1002,101,'Dr. Kumar','Cardiology','2024-01-07',1200),
		(1003,101,'Dr. Ravi','General','2024-01-08',800),
		(1004,102,'Dr. Mehta','Dermatology','2024-01-15',900),
		(1005,102,'Dr. Mehta','Dermatology','2024-01-18',900),
		(1006,103,'Dr. Ravi','General','2024-02-03',800),
		(1007,103,'Dr. Ravi','General','2024-02-04',800),
		(1008,103,'Dr. Ravi','General','2024-02-05',800),
		(1009,104,'Dr. Shah','Orthopedics','2024-02-18',1500),
		(1010,105,'Dr. Kumar','Cardiology','2024-03-02',1200),
		(1011,105,'Dr. Kumar','Cardiology','2024-03-03',1200),
		(1012,106,'Dr. Ravi','General','2024-03-20',800),
		(1013,107,'Dr. Shah','Orthopedics','2024-04-08',1500),
		(1014,107,'Dr. Shah','Orthopedics','2024-04-09',1500),
		(1015,107,'Dr. Shah','Orthopedics','2024-04-10',1500),
		(1016,108,'Dr. Mehta','Dermatology','2024-04-22',900),
		(1017,109,'Dr. Kumar','Cardiology','2024-05-06',1200),
		(1018,109,'Dr. Ravi','General','2024-05-07',800),
		(1019,110,'Dr. Shah','Orthopedics','2024-05-27',1500),
		(1020,110,'Dr. Shah','Orthopedics','2024-05-28',1500);
        
SELECT *
FROM Patients;

SELECT *
FROM Appointments;

-- Q1
-- Show each patient's total appointments,
-- total consultation fee, and average consultation fee.
--
-- Use both tables.
--
-- Return:
-- Patient_ID
-- Patient_Name
-- Total_Appointments
-- Total_Consultation_Fee
-- Average_Consultation_Fee

SELECT P.Patient_ID, P.Patient_Name,
	   COUNT(A.Appointment_ID) AS Total_Appointments,
	   SUM(A.Consultation_Fee) AS Total_Consultation_Fee,
       ROUND(AVG(A.Consultation_Fee), 2) AS Average_Consultation_Fee
FROM Patients P
INNER JOIN Appointments A
	ON P.Patient_ID = A.Patient_ID
GROUP BY P.Patient_ID, P.Patient_Name;


-- Q2
-- Show each department's total appointments
-- and total consultation revenue.
--
-- Return:
-- Department
-- Total_Appointments
-- Total_Consultation_Revenue

SELECT Department,
	   COUNT(Appointment_ID) AS Total_Appointments,
	   SUM(Consultation_Fee) AS Total_Consultation_Revenue
FROM Appointments
GROUP BY Department;


-- Q3
-- Find the top 3 patients by total consultation fee.
--
-- Use DENSE_RANK().
--
-- Return:
-- Patient_ID
-- Patient_Name
-- Total_Consultation_Fee

WITH CTE AS (
	SELECT P.Patient_ID, P.Patient_Name,
		   SUM(A.Consultation_Fee) AS Total_Consultation_Fee
	FROM Patients P
	INNER JOIN Appointments A
		ON P.Patient_ID = A.Patient_ID
	GROUP BY P.Patient_ID, P.Patient_Name
),
CTE2 AS (
	SELECT *,
		   DENSE_RANK() OVER(ORDER BY Total_Consultation_Fee DESC) AS D_Rank
	FROM CTE
)
SELECT Patient_ID, Patient_Name, Total_Consultation_Fee
FROM CTE2
WHERE D_Rank <= 3;


-- Q4
-- Find patients who had an appointment within 2 days
-- of their previous appointment.
--
-- Use JOIN + LAG().
--
-- Return:
-- Patient_ID
-- Patient_Name

WITH CTE AS (
	SELECT P.Patient_ID, P.Patient_Name, A.Appointment_Date,
		   LAG(A.Appointment_Date) OVER(PARTITION BY P.Patient_ID
           ORDER BY A.Appointment_Date, A.Appointment_ID) AS Previous
	FROM Patients P
	INNER JOIN Appointments A
		ON P.Patient_ID = A.Patient_ID
),
CTE2 AS (
	SELECT *,
		   DATEDIFF(Appointment_Date, Previous) AS Days_Gap
	FROM CTE
)
SELECT DISTINCT Patient_ID, Patient_Name
FROM CTE2
WHERE Previous IS NOT NULL
AND Days_Gap <= 2;


-- Q5 (COHORT ANALYSIS)
-- For each cohort month, find:
-- total patients
-- and total consultation revenue generated by those patients.
--
-- Definition:
-- Cohort Month = Month in which the patient registered.
--
-- Use both tables.
--
-- Return:
-- Cohort_Month
-- Total_Patients
-- Total_Consultation_Revenue

WITH CTE AS (
	SELECT Patient_ID,
		   DATE_FORMAT(Registration_Date, '%Y-%m') AS Cohort_Month
	FROM Patients
)
SELECT Cohort_Month,
	   COUNT(DISTINCT C.Patient_ID) AS Total_Patients,
       SUM(A.Consultation_Fee) AS Total_Consultation_Revenue
FROM CTE C
INNER JOIN Appointments A
	ON C.Patient_ID = A.Patient_ID
GROUP BY Cohort_Month;


-- BONUS (GAP & ISLAND)
-- Find the start date and end date of each patient's
-- longest appointment streak.
--
-- Return:
-- Patient_ID
-- Patient_Name
-- Longest_Streak
-- Start_Date
-- End_Date
--
-- Note:
-- Ignore duplicate appointment dates if a patient
-- has multiple appointments on the same day.
--
-- If multiple streaks have the same length,
-- return the most recent streak.

WITH CTE AS (
	SELECT DISTINCT P.Patient_ID, P.Patient_Name, A.Appointment_Date
    FROM Patients P
	INNER JOIN Appointments A
		ON P.Patient_ID = A.Patient_ID
),
CTE2 AS (
	SELECT *,
		   ROW_NUMBER() OVER(PARTITION BY Patient_ID
           ORDER BY Appointment_Date) AS RN
	FROM CTE
),
CTE3 AS (
	SELECT *,
		   DATE_SUB(Appointment_Date, INTERVAL RN DAY) AS GK
	FROM CTE2
),
CTE4 AS (
	SELECT Patient_ID, Patient_Name,
		   COUNT(*) AS Streak,
           MIN(Appointment_Date) AS Start_Date,
           MAX(Appointment_Date) AS End_Date
	FROM CTE3
    GROUP BY Patient_ID, Patient_Name, GK
),
CTE5 AS (
	SELECT *,
		   ROW_NUMBER() OVER(PARTITION BY Patient_ID
           ORDER BY Streak DESC, End_Date DESC) AS Row_Num
	FROM CTE4
)
SELECT Patient_ID, Patient_Name, Streak AS Longest_Streak,
	   Start_Date, End_Date
FROM CTE5
WHERE Row_Num = 1;


-- BONUS+
-- Find patients whose total consultation fee
-- is greater than the average total consultation fee
-- of patients in the same city.
--
-- Return:
-- Patient_ID
-- Patient_Name
-- City
-- Total_Consultation_Fee

WITH CTE AS (
	SELECT P.Patient_ID, P.Patient_Name, P.City,
		   SUM(A.Consultation_Fee) AS Total_Consultation_Fee
	FROM Patients P
	INNER JOIN Appointments A
		ON P.Patient_ID = A.Patient_ID
	GROUP BY P.Patient_ID, P.Patient_Name, P.City
)
SELECT Patient_ID, Patient_Name, City, Total_Consultation_Fee
FROM (
	SELECT *,
		   AVG(Total_Consultation_Fee) OVER(PARTITION BY City) AS Avg_City
	FROM CTE
	)A
WHERE Total_Consultation_Fee > Avg_City;