USE Daily_SQL;

-- DATASET: Course Enrollments

CREATE TABLE Students (
    Student_ID INT PRIMARY KEY,
    Student_Name VARCHAR(100),
    City VARCHAR(50),
    Registration_Date DATE
);

CREATE TABLE Enrollments (
    Enrollment_ID INT PRIMARY KEY,
    Student_ID INT,
    Course_Name VARCHAR(100),
    Category VARCHAR(50),
    Enrollment_Date DATE,
    Course_Fee DECIMAL(10,2),
    FOREIGN KEY (Student_ID) REFERENCES Students(Student_ID)
);

INSERT INTO Students
VALUES	(101,'Arun','Chennai','2024-01-05'),
		(102,'Divya','Bengaluru','2024-01-12'),
		(103,'Karthik','Chennai','2024-02-03'),
		(104,'Meena','Hyderabad','2024-02-20'),
		(105,'Rahul','Bengaluru','2024-03-08'),
		(106,'Sneha','Chennai','2024-03-15'),
		(107,'Vikram','Hyderabad','2024-04-02'),
		(108,'Priya','Chennai','2024-04-18'),
		(109,'Anil','Bengaluru','2024-05-10'),
		(110,'Neha','Hyderabad','2024-05-25');

INSERT INTO Enrollments
VALUES	(1001,101,'SQL Basics','Database','2024-01-06',1500),
		(1002,101,'Advanced SQL','Database','2024-01-07',2000),
		(1003,101,'Power BI','Analytics','2024-01-08',2500),
		(1004,102,'Excel','Productivity','2024-01-15',1200),
		(1005,102,'Power BI','Analytics','2024-01-18',2500),
		(1006,103,'SQL Basics','Database','2024-02-04',1500),
		(1007,103,'Advanced SQL','Database','2024-02-05',2000),
		(1008,103,'Python','Programming','2024-02-06',3000),
		(1009,104,'Java','Programming','2024-02-22',3500),
		(1010,105,'SQL Basics','Database','2024-03-09',1500),
		(1011,105,'Advanced SQL','Database','2024-03-10',2000),
		(1012,106,'Excel','Productivity','2024-03-18',1200),
		(1013,107,'Python','Programming','2024-04-03',3000),
		(1014,107,'Java','Programming','2024-04-04',3500),
		(1015,107,'Power BI','Analytics','2024-04-05',2500),
		(1016,108,'Excel','Productivity','2024-04-20',1200),
		(1017,109,'SQL Basics','Database','2024-05-11',1500),
		(1018,109,'Power BI','Analytics','2024-05-12',2500),
		(1019,110,'Python','Programming','2024-05-27',3000),
		(1020,110,'Java','Programming','2024-05-28',3500);
        
SELECT *
FROM Students;

SELECT *
FROM Enrollments;

-- Q1
-- Show each student's total enrollments,
-- total course fee paid, and average course fee paid.
--
-- Use both tables.
--
-- Return:
-- Student_ID
-- Student_Name
-- Total_Enrollments
-- Total_Course_Fee
-- Average_Course_Fee

SELECT S.Student_ID, S.Student_Name,
	   COUNT(E.Enrollment_ID) AS Total_Enrollments,
       SUM(E.Course_Fee) AS Total_Course_Fee,
       ROUND(AVG(E.Course_Fee), 2) Average_Course_Fee
FROM Students S
INNER JOIN Enrollments E
	ON S.Student_ID = E.Student_ID
GROUP BY S.Student_ID, S.Student_Name;


-- Q2
-- Show each course category's total enrollments
-- and total course revenue.
--
-- Return:
-- Category
-- Total_Enrollments
-- Total_Course_Revenue

SELECT Category,
	   COUNT(Enrollment_ID) AS Total_Enrollments,
       SUM(Course_Fee) AS Total_Course_Revenue
FROM Enrollments
GROUP BY Category;

-- Q3
-- Find the top 3 students by total course fee paid.
--
-- Use DENSE_RANK().
--
-- Return:
-- Student_ID
-- Student_Name
-- Total_Course_Fee

WITH CTE AS (
	SELECT S.Student_ID, S.Student_Name,
		   SUM(E.Course_Fee) AS Total_Course_Fee
	FROM Students S
	INNER JOIN Enrollments E
		ON S.Student_ID = E.Student_ID
	GROUP BY S.Student_ID, S.Student_Name
),
CTE2 AS (
	SELECT *,
		   DENSE_RANK() OVER(ORDER BY Total_Course_Fee DESC) AS D_Rank
	FROM CTE
)
SELECT Student_ID, Student_Name, Total_Course_Fee
FROM CTE2
WHERE D_Rank <= 3;


-- Q4
-- Find students who enrolled in a course within 2 days
-- of their previous enrollment.
--
-- Use JOIN + LAG().
--
-- Return:
-- Student_ID
-- Student_Name

WITH CTE AS (
	SELECT S.Student_ID, S.Student_Name, E.Enrollment_Date,
		   LAG(E.Enrollment_Date) OVER(PARTITION BY S.Student_ID
           ORDER BY E.Enrollment_Date, E.Enrollment_ID) AS Previous
	FROM Students S
	INNER JOIN Enrollments E
		ON S.Student_ID = E.Student_ID
)
SELECT DISTINCT Student_ID, Student_Name
FROM CTE
WHERE Previous IS NOT NULL
AND DATEDIFF(Enrollment_Date, Previous) <= 2;


-- Q5 (COHORT ANALYSIS)
-- For each cohort month, find:
-- total students
-- and total course revenue generated by those students.
--
-- Definition:
-- Cohort Month = Month in which the student registered.
--
-- Use both tables.
--
-- Return:
-- Cohort_Month
-- Total_Students
-- Total_Course_Revenue

WITH CTE AS (
	SELECT Student_ID,
		   DATE_FORMAT(Registration_Date, '%Y-%m') AS Cohort_Month
	FROM Students
)
SELECT Cohort_Month,
	   COUNT(DISTINCT E.Student_ID) AS Total_Students,
	   SUM(E.Course_Fee) AS Total_Course_Revenue
FROM CTE C
INNER JOIN Enrollments E
	ON C.Student_ID = E.Student_ID
GROUP BY Cohort_Month;


-- BONUS (GAP & ISLAND)
-- Find the start date and end date of each student's
-- current enrollment streak.
--
-- Return:
-- Student_ID
-- Student_Name
-- Current_Streak
-- Start_Date
-- End_Date
--
-- Definition:
-- Current streak = streak containing the student's
-- most recent enrollment date.
--
-- Note:
-- Ignore duplicate enrollment dates if a student
-- has multiple enrollments on the same day.
--
-- Return only students whose Current_Streak >= 3.

WITH CTE AS (
	SELECT DISTINCT S.Student_ID, S.Student_Name, E.Enrollment_Date
    FROM Students S
	INNER JOIN Enrollments E
		ON S.Student_ID = E.Student_ID
),
CTE2 AS (
	SELECT *,
		   ROW_NUMBER() OVER(PARTITION BY Student_ID
           ORDER BY Enrollment_Date) AS RN
	FROM CTE
),
CTE3 AS (
	SELECT *,
		   DATE_SUB(Enrollment_Date, INTERVAL RN DAY) AS GK
	FROM CTE2
),
CTE4 AS (
	SELECT Student_ID, Student_Name,
		   COUNT(*) AS Streak,
           MIN(Enrollment_Date) AS Start_Date,
           MAX(Enrollment_Date) AS End_Date
	FROM CTE3
    GROUP BY Student_ID, Student_Name, GK
),
CTE5 AS (
	SELECT *,
		   ROW_NUMBER() OVER(PARTITION BY Student_ID
           ORDER BY End_Date DESC) AS Row_Num
	FROM CTE4
)
SELECT Student_ID, Student_Name, Streak AS Current_Streak,
	   Start_Date, End_Date
FROM CTE5
WHERE Row_Num = 1
AND Streak >= 3;


-- BONUS+
-- Find students whose total course fee paid
-- is greater than the average total course fee paid
-- of students in the same city.
--
-- Return:
-- Student_ID
-- Student_Name
-- City
-- Total_Course_Fee

WITH CTE AS (
	SELECT S.Student_ID, S.Student_Name, S.City,
		   SUM(E.Course_Fee) AS Total_Course_Fee
	FROM Students S
	INNER JOIN Enrollments E
		ON S.Student_ID = E.Student_ID
	GROUP BY S.Student_ID, S.Student_Name, S.City
),
CTE2 AS (
	SELECT *,
		   AVG(Total_Course_Fee) OVER(PARTITION BY City) AS Avg_City
	FROM CTE
)
SELECT Student_ID, Student_Name, City, Total_Course_Fee
FROM CTE2
WHERE Total_Course_Fee > Avg_City;

-- Find the top-paying student in each city.

-- Expected output:
-- Student_ID
-- Student_Name
-- City
-- Total_Course_Fee

WITH CTE AS (
	SELECT S.Student_ID, S.Student_Name, S.City,
		   SUM(E.Course_Fee) AS Total_Course_Fee
	FROM Students S
	INNER JOIN Enrollments E
		ON S.Student_ID = E.Student_ID
	GROUP BY S.Student_ID, S.Student_Name, S.City
)
SELECT Student_ID, Student_Name, City, Total_Course_Fee
FROM (
	SELECT *,
		   DENSE_RANK() OVER(PARTITION BY City
           ORDER BY Total_Course_Fee DESC) AS D_Rank
	FROM CTE
)D
WHERE D_Rank = 1;