USE Daily_SQL;

-- DATASET: Food Delivery Orders

CREATE TABLE Customers (
    Customer_ID INT PRIMARY KEY,
    Customer_Name VARCHAR(100),
    City VARCHAR(50),
    Join_Date DATE
);

CREATE TABLE Delivery_Orders (
    Order_ID INT PRIMARY KEY,
    Customer_ID INT,
    Restaurant_Name VARCHAR(100),
    Cuisine_Type VARCHAR(50),
    Order_Date DATE,
    Order_Amount DECIMAL(10,2),
    FOREIGN KEY (Customer_ID) REFERENCES Customers(Customer_ID)
);

INSERT INTO Customers
VALUES	(101,'Arun','Chennai','2024-01-05'),
		(102,'Divya','Bengaluru','2024-01-12'),
		(103,'Karthik','Chennai','2024-02-08'),
		(104,'Meena','Hyderabad','2024-02-20'),
		(105,'Rahul','Bengaluru','2024-03-01'),
		(106,'Sneha','Chennai','2024-03-15'),
		(107,'Vikram','Hyderabad','2024-04-04'),
		(108,'Priya','Chennai','2024-04-18'),
		(109,'Anil','Bengaluru','2024-05-06'),
		(110,'Neha','Hyderabad','2024-05-25');

INSERT INTO Delivery_Orders
VALUES	(1001,101,'A2B','South Indian','2024-01-06',450),
		(1002,101,'A2B','South Indian','2024-01-07',380),
		(1003,101,'Dominos','Pizza','2024-01-08',650),
		(1004,102,'KFC','Fast Food','2024-01-14',720),
		(1005,102,'Pizza Hut','Pizza','2024-01-16',810),
		(1006,103,'A2B','South Indian','2024-02-09',500),
		(1007,103,'Subway','Fast Food','2024-02-10',420),
		(1008,103,'Dominos','Pizza','2024-02-11',690),
		(1009,104,'Paradise','Biryani','2024-02-22',950),
		(1010,105,'A2B','South Indian','2024-03-02',470),
		(1011,105,'Dominos','Pizza','2024-03-03',640),
		(1012,106,'Subway','Fast Food','2024-03-17',390),
		(1013,107,'Paradise','Biryani','2024-04-05',980),
		(1014,107,'KFC','Fast Food','2024-04-06',760),
		(1015,107,'Pizza Hut','Pizza','2024-04-07',830),
		(1016,108,'A2B','South Indian','2024-04-20',520),
		(1017,109,'Dominos','Pizza','2024-05-08',710),
		(1018,109,'Subway','Fast Food','2024-05-09',430),
		(1019,110,'Paradise','Biryani','2024-05-27',990),
		(1020,110,'KFC','Fast Food','2024-05-28',780);
        
SELECT *
FROM Customers;

SELECT *
FROM Delivery_Orders;

-- Q1
-- Show each customer's total orders,
-- total order amount, and average order amount.
--
-- Use both tables.
--
-- Return:
-- Customer_ID
-- Customer_Name
-- Total_Orders
-- Total_Order_Amount
-- Average_Order_Amount

SELECT C.Customer_ID, C.Customer_Name,
	   COUNT(D.Order_ID) AS Total_Orders,
       SUM(D.Order_Amount) AS Total_Order_Amount,
       ROUND(AVG(D.Order_Amount), 2) AS Average_Order_Amount
FROM Customers C
INNER JOIN Delivery_Orders D
	ON C.Customer_ID = D.Customer_ID
GROUP BY Customer_ID, Customer_Name;


-- Q2
-- Show each cuisine type's total orders
-- and total order revenue.
--
-- Return:
-- Cuisine_Type
-- Total_Orders
-- Total_Order_Revenue

SELECT Cuisine_Type,
	   COUNT(Order_ID) AS Total_Orders,
       SUM(Order_Amount) AS Total_Order_Revenue
FROM Delivery_Orders
GROUP BY Cuisine_Type;


-- Q3
-- Find the top 3 customers by total order amount.
--
-- Use DENSE_RANK().
--
-- Return:
-- Customer_ID
-- Customer_Name
-- Total_Order_Amount

WITH CTE AS (
	SELECT C.Customer_ID, C.Customer_Name,
		   SUM(D.Order_Amount) AS Total_Order_Amount
	FROM Customers C
	INNER JOIN Delivery_Orders D
		ON C.Customer_ID = D.Customer_ID
	GROUP BY Customer_ID, Customer_Name
),
CTE2 AS (
	SELECT *,
		   DENSE_RANK() OVER(ORDER BY Total_Order_Amount DESC) AS D_Rank
	FROM CTE
)
SELECT Customer_ID, Customer_Name, Total_Order_Amount
FROM CTE2
WHERE D_Rank <= 3;


-- Q4
-- Find customers who placed an order within 2 days
-- of their previous order.
--
-- Use JOIN + LAG().
--
-- Return:
-- Customer_ID
-- Customer_Name

WITH CTE AS (
	SELECT C.Customer_ID, C.Customer_Name, D.Order_Date,
		   LAG(D.Order_Date) OVER(PARTITION BY C.Customer_ID
           ORDER BY D.Order_Date, D.Order_ID) AS Previous
	FROM Customers C
	INNER JOIN Delivery_Orders D
		ON C.Customer_ID = D.Customer_ID
)
SELECT DISTINCT Customer_ID, Customer_Name
FROM CTE
WHERE Previous IS NOT NULL
AND DATEDIFF(Order_Date, Previous) <= 2;


-- Q5 (COHORT ANALYSIS)
-- For each cohort month, find:
-- total customers
-- and total order revenue generated by those customers.
--
-- Definition:
-- Cohort Month = Month in which the customer joined.
--
-- Use both tables.
--
-- Return:
-- Cohort_Month
-- Total_Customers
-- Total_Order_Revenue

WITH CTE AS (
	SELECT Customer_ID,
		   DATE_FORMAT(Join_Date, '%Y-%m') AS Cohort_Month
	FROM Customers
)
SELECT Cohort_Month,
	   COUNT(DISTINCT C.Customer_ID) AS Total_Customers,
       SUM(D.Order_Amount) AS Total_Order_Revenue
FROM CTE C
INNER JOIN Delivery_Orders D
	ON C.Customer_ID = D.Customer_ID
GROUP BY Cohort_Month;


-- BONUS (GAP & ISLAND)
-- Find the start date and end date of each customer's
-- current order streak.
--
-- Return:
-- Customer_ID
-- Customer_Name
-- Current_Streak
-- Start_Date
-- End_Date
--
-- Definition:
-- Current streak = streak containing the customer's
-- most recent order date.
--
-- Note:
-- Ignore duplicate order dates if a customer
-- has multiple orders on the same day.
--
-- Return only customers whose Current_Streak >= 3.

WITH CTE AS (
	SELECT DISTINCT C.Customer_ID, C.Customer_Name, D.Order_Date
	FROM Customers C
	INNER JOIN Delivery_Orders D
		ON C.Customer_ID = D.Customer_ID
),
CTE2 AS (
	SELECT *,
		   ROW_NUMBER() OVER(PARTITION BY Customer_ID
           ORDER BY Order_Date) AS RN
	FROM CTE
),
CTE3 AS (
	SELECT *,
		   DATE_SUB(Order_Date, INTERVAL RN DAY) AS GK
	FROM CTE2
),
CTE4 AS (
	SELECT Customer_ID, Customer_Name,
		   COUNT(*) AS Streak,
           MIN(Order_Date) AS Start_Date,
           MAX(Order_Date) AS End_Date
	FROM CTE3
    GROUP BY Customer_ID, Customer_Name, GK
),
CTE5 AS (
	SELECT *,
		   ROW_NUMBER() OVER(PARTITION BY Customer_ID
           ORDER BY End_Date DESC) AS Row_Num
	FROM CTE4
)		   
SELECT Customer_ID, Customer_Name, Streak AS Current_Streak,
	   Start_Date, End_Date
FROM CTE5
WHERE Row_Num = 1
AND Streak >= 3;


-- BONUS+
-- Find customers whose total order amount
-- is greater than the average total order amount
-- of customers in the same city.
--
-- Return:
-- Customer_ID
-- Customer_Name
-- City
-- Total_Order_Amount

WITH CTE AS (
	SELECT C.Customer_ID, C.Customer_Name, C.City,
		   SUM(D.Order_Amount) AS Total_Order_Amount
	FROM Customers C
	INNER JOIN Delivery_Orders D
		ON C.Customer_ID = D.Customer_ID
	GROUP BY Customer_ID, Customer_Name, C.City
)
SELECT Customer_ID, Customer_Name, City, Total_Order_Amount
FROM (
	SELECT *,
		   AVG(Total_Order_Amount) OVER(PARTITION BY City) AS Avg_City
	FROM CTE
)A
WHERE Total_Order_Amount > Avg_City;