USE Daily_SQL;

-- DATASET: Grocery Orders

CREATE TABLE Customers (
    Customer_ID INT PRIMARY KEY,
    Customer_Name VARCHAR(100),
    City VARCHAR(50),
    Join_Date DATE
);

CREATE TABLE Grocery_Orders (
    Order_ID INT PRIMARY KEY,
    Customer_ID INT,
    Product_Category VARCHAR(50),
    Order_Date DATE,
    Order_Amount DECIMAL(10,2),
    FOREIGN KEY (Customer_ID) REFERENCES Customers(Customer_ID)
);

INSERT INTO Customers
VALUES	(101,'Arun','Chennai','2024-01-05'),
		(102,'Divya','Bengaluru','2024-01-18'),
		(103,'Karthik','Chennai','2024-02-02'),
		(104,'Meena','Hyderabad','2024-02-15'),
		(105,'Rahul','Bengaluru','2024-03-01'),
		(106,'Sneha','Chennai','2024-03-20'),
		(107,'Vikram','Hyderabad','2024-04-08'),
		(108,'Priya','Chennai','2024-04-21'),
		(109,'Anil','Bengaluru','2024-05-06'),
		(110,'Neha','Hyderabad','2024-05-19');

INSERT INTO Grocery_Orders
VALUES	(1001,101,'Fruits','2024-01-06',450),
		(1002,101,'Vegetables','2024-01-07',320),
		(1003,101,'Dairy','2024-01-08',280),
		(1004,102,'Snacks','2024-01-20',510),
		(1005,102,'Beverages','2024-01-22',390),
		(1006,103,'Fruits','2024-02-03',460),
		(1007,103,'Vegetables','2024-02-04',350),
		(1008,103,'Bakery','2024-02-05',420),
		(1009,104,'Dairy','2024-02-17',610),
		(1010,105,'Snacks','2024-03-02',540),
		(1011,105,'Fruits','2024-03-03',370),
		(1012,106,'Bakery','2024-03-22',290),
		(1013,107,'Beverages','2024-04-09',480),
		(1014,107,'Snacks','2024-04-10',520),
		(1015,107,'Dairy','2024-04-11',430),
		(1016,108,'Vegetables','2024-04-23',310),
		(1017,109,'Fruits','2024-05-08',440),
		(1018,109,'Bakery','2024-05-09',360),
		(1019,110,'Beverages','2024-05-21',500),
		(1020,110,'Snacks','2024-05-22',550);

SELECT *
FROM Customers;

SELECT *
FROM Grocery_Orders;

-- Q1
-- Show each customer's total orders,
-- total order amount, and average order amount.
--
-- Use both tables.
--
-- Return:
-- Customer_ID
-- Customer_Name
-- Total_Orders
-- Total_Order_Amount
-- Average_Order_Amount

SELECT C.Customer_ID, C.Customer_Name,
	   COUNT(G.Order_ID) AS Total_Orders,
       SUM(G.Order_Amount) AS Total_Order_Amount,
       ROUND(AVG(G.Order_Amount), 2) AS Average_Order_Amount
FROM Customers C
INNER JOIN Grocery_Orders G
	ON C.Customer_ID = G.Customer_ID
GROUP BY C.Customer_ID, C.Customer_Name;


-- Q2
-- Show each product category's total orders
-- and total order revenue.
--
-- Return:
-- Product_Category
-- Total_Orders
-- Total_Order_Revenue

SELECT Product_Category,
	   COUNT(Order_ID) AS Total_Orders,
       SUM(Order_Amount) AS Total_Order_Revenue
FROM Grocery_Orders
GROUP BY Product_Category;


-- Q3
-- Find the top 3 customers by total order amount.
--
-- Use DENSE_RANK().
--
-- Return:
-- Customer_ID
-- Customer_Name
-- Total_Order_Amount

WITH CTE AS (
	SELECT C.Customer_ID, C.Customer_Name,
		   SUM(G.Order_Amount) AS Total_Order_Amount
	FROM Customers C
	INNER JOIN Grocery_Orders G
		ON C.Customer_ID = G.Customer_ID
	GROUP BY C.Customer_ID, C.Customer_Name
),
CTE2 AS (
	SELECT *,
		   DENSE_RANK() OVER(ORDER BY Total_Order_Amount DESC) AS D_Rank
	FROM CTE
)
SELECT Customer_ID, Customer_Name, Total_Order_Amount
FROM CTE2
WHERE D_Rank <= 3;


-- Q4
-- Find customers who placed an order within 2 days
-- of their previous order.
--
-- Use JOIN + LAG().
--
-- Return:
-- Customer_ID
-- Customer_Name

WITH CTE AS (
	SELECT C.Customer_ID, C.Customer_Name, G.Order_Date,
		   LAG(G.Order_Date) OVER(PARTITION BY C.Customer_ID
           ORDER BY G.Order_Date, G.Order_ID) AS Previous
	FROM Customers C
	INNER JOIN Grocery_Orders G
		ON C.Customer_ID = G.Customer_ID
)
SELECT DISTINCT Customer_ID, Customer_Name
FROM CTE
WHERE Previous IS NOT NULL
AND DATEDIFF(Order_Date, Previous) <= 2;


-- Q5 (COHORT ANALYSIS)
-- For each cohort month, find:
-- total customers
-- and total order revenue generated by those customers.
--
-- Definition:
-- Cohort Month = Month in which the customer joined.
--
-- Use both tables.
--
-- Return:
-- Cohort_Month
-- Total_Customers
-- Total_Order_Revenue

WITH CTE AS (
	SELECT Customer_ID,
		   DATE_FORMAT(Join_Date, '%Y-%m') AS Cohort_Month
	FROM Customers
)
SELECT Cohort_Month,
	   COUNT(DISTINCT C.Customer_ID) AS Total_Customers,
       SUM(G.Order_Amount) AS Total_Order_Revenue
FROM CTE C
INNER JOIN Grocery_Orders G
	ON C.Customer_ID = G.Customer_ID
GROUP BY Cohort_Month;


-- BONUS (GAP & ISLAND)
-- Find the start date and end date of each customer's
-- longest order streak.
--
-- Return:
-- Customer_ID
-- Customer_Name
-- Longest_Streak
-- Start_Date
-- End_Date
--
-- Note:
-- Ignore duplicate order dates if a customer
-- has multiple orders on the same day.
--
-- If multiple streaks have the same length,
-- return the most recent streak.

WITH CTE AS (
	SELECT DISTINCT C.Customer_ID, C.Customer_Name, G.Order_Date
    FROM Customers C
	INNER JOIN Grocery_Orders G
		ON C.Customer_ID = G.Customer_ID
),
CTE2 AS (
	SELECT *,
		   ROW_NUMBER() OVER(PARTITION BY Customer_ID
           ORDER BY Order_Date) AS RN
	FROM CTE
),
CTE3 AS (
	SELECT *,
		   DATE_SUB(Order_Date, INTERVAL RN DAY) AS GK
	FROM CTE2
),
CTE4 AS (
	SELECT Customer_ID, Customer_Name,
		   COUNT(*) AS Streak,
           MIN(Order_Date) AS Start_Date,
           MAX(Order_Date) AS End_Date
	FROM CTE3
    GROUP BY Customer_ID, Customer_Name, GK
),
CTE5 AS (
	SELECT *,
		   ROW_NUMBER() OVER(PARTITION BY Customer_ID
           ORDER BY Streak DESC, End_Date DESC) AS Row_Num
	FROM CTE4
)
SELECT Customer_ID, Customer_Name, Streak AS Longest_Streak,
	   Start_Date, End_Date
FROM CTE5
WHERE Row_Num = 1;


-- BONUS+
-- Find customers whose total order amount
-- is greater than the average total order amount
-- of customers in the same city.
--
-- Return:
-- Customer_ID
-- Customer_Name
-- City
-- Total_Order_Amount

SELECT Customer_ID, Customer_Name, City, Total_Order_Amount
FROM (
	SELECT *,
		   AVG(Total_Order_Amount) OVER(PARTITION BY City) AS Avg_City
	FROM (
		SELECT C.Customer_ID, C.Customer_Name, C.City,
			   SUM(G.Order_Amount) AS Total_Order_Amount
		FROM Customers C
		INNER JOIN Grocery_Orders G
			ON C.Customer_ID = G.Customer_ID
		GROUP BY C.Customer_ID, C.Customer_Name, C.City
	)A
)C
WHERE Total_Order_Amount > Avg_City;

-- Find the customer(s) who spent the highest amount in each product category.

-- Expected output:
-- Product_Category
-- Customer_ID
-- Customer_Name
-- Total_Order_Amount

SELECT Product_Category, Customer_ID, Customer_Name, Total_Order_Amount
FROM (
	SELECT *,
		   DENSE_RANK() OVER(PARTITION BY Product_Category
           ORDER BY Total_Order_Amount DESC) AS D_Rank
	FROM (
		SELECT G.Product_Category, C.Customer_ID, C.Customer_Name,
			   SUM(G.Order_Amount) AS Total_Order_Amount
		FROM Customers C
		INNER JOIN Grocery_Orders G
			ON C.Customer_ID = G.Customer_ID
		GROUP BY G.Product_Category, C.Customer_ID, C.Customer_Name
	)D
)T
WHERE D_Rank = 1;