USE Daily_SQL;

-- DATASET: Hotel Reservations

CREATE TABLE Guests (
    Guest_ID INT PRIMARY KEY,
    Guest_Name VARCHAR(100),
    City VARCHAR(50),
    Registration_Date DATE
);

CREATE TABLE Reservations (
    Reservation_ID INT PRIMARY KEY,
    Guest_ID INT,
    Room_Type VARCHAR(50),
    Checkin_Date DATE,
    Bill_Amount DECIMAL(10,2),
    FOREIGN KEY (Guest_ID) REFERENCES Guests(Guest_ID)
);

INSERT INTO Guests 
VALUES	(101,'Arun','Chennai','2024-01-05'),
		(102,'Divya','Bengaluru','2024-01-12'),
		(103,'Karthik','Chennai','2024-02-03'),
		(104,'Meena','Hyderabad','2024-02-18'),
		(105,'Rahul','Bengaluru','2024-03-01'),
		(106,'Sneha','Chennai','2024-03-20'),
		(107,'Vikram','Hyderabad','2024-04-10'),
		(108,'Priya','Chennai','2024-04-22'),
		(109,'Anil','Bengaluru','2024-05-08'),
		(110,'Neha','Hyderabad','2024-05-25');

INSERT INTO Reservations 
VALUES	(1001,101,'Deluxe','2024-01-06',3200),
		(1002,101,'Suite','2024-01-07',4800),
		(1003,101,'Deluxe','2024-01-08',3500),
		(1004,102,'Standard','2024-01-15',2200),
		(1005,102,'Suite','2024-01-18',5100),
		(1006,103,'Deluxe','2024-02-04',3600),
		(1007,103,'Suite','2024-02-05',5000),
		(1008,103,'Standard','2024-02-06',2400),
		(1009,104,'Suite','2024-02-20',5500),
		(1010,105,'Standard','2024-03-03',2100),
		(1011,105,'Deluxe','2024-03-04',3300),
		(1012,106,'Suite','2024-03-22',4700),
		(1013,107,'Standard','2024-04-12',2300),
		(1014,107,'Deluxe','2024-04-13',3400),
		(1015,107,'Suite','2024-04-14',5200),
		(1016,108,'Deluxe','2024-04-24',3100),
		(1017,109,'Standard','2024-05-10',2500),
		(1018,109,'Suite','2024-05-11',4900),
		(1019,110,'Deluxe','2024-05-27',3700),
		(1020,110,'Suite','2024-05-28',5300);
        
SELECT *
FROM Guests;

SELECT *
FROM Reservations;

-- Q1
-- Show each guest's total reservations,
-- total bill amount, and average bill amount.
--
-- Use both tables.
--
-- Return:
-- Guest_ID
-- Guest_Name
-- Total_Reservations
-- Total_Bill_Amount
-- Average_Bill_Amount

SELECT G.Guest_ID, G.Guest_Name,
	   COUNT(R.Reservation_ID) AS Total_Reservations,
       SUM(R.Bill_Amount) AS Total_Bill_Amount,
       ROUND(AVG(R.Bill_Amount), 2) AS Average_Bill_Amount
FROM Guests G
INNER JOIN Reservations R
	ON G.Guest_ID = R.Guest_ID
GROUP BY G.Guest_ID, G.Guest_Name;


-- Q2
-- Show each room type's total reservations
-- and total bill revenue.
--
-- Return:
-- Room_Type
-- Total_Reservations
-- Total_Bill_Revenue

SELECT Room_Type,
	   COUNT(Reservation_ID) AS Total_Reservations,
       SUM(Bill_Amount) AS Total_Bill_Revenue
FROM Reservations
GROUP BY Room_Type;


-- Q3
-- Find the top 3 guests by total bill amount.
--
-- Use DENSE_RANK().
--
-- Return:
-- Guest_ID
-- Guest_Name
-- Total_Bill_Amount

WITH CTE AS (
	SELECT G.Guest_ID, G.Guest_Name,
		   SUM(R.Bill_Amount) AS Total_Bill_Amount
	FROM Guests G
	INNER JOIN Reservations R
		ON G.Guest_ID = R.Guest_ID
	GROUP BY G.Guest_ID, G.Guest_Name
),
CTE2 AS (
	SELECT *,
		   DENSE_RANK() OVER(ORDER BY Total_Bill_Amount DESC) AS D_Rank
	FROM CTE
)
SELECT Guest_ID, Guest_Name, Total_Bill_Amount
FROM CTE2
WHERE D_Rank <= 3;


-- Q4
-- Find guests who checked in within 2 days
-- of their previous check-in.
--
-- Use JOIN + LAG().
--
-- Return:
-- Guest_ID
-- Guest_Name

WITH CTE AS (
	SELECT G.Guest_ID, G.Guest_Name, R.Checkin_Date,
		   LAG(R.Checkin_Date) OVER(PARTITION BY G.Guest_ID
           ORDER BY R.Checkin_Date, R.Reservation_ID) AS Previous
	FROM Guests G
	INNER JOIN Reservations R
		ON G.Guest_ID = R.Guest_ID
)
SELECT DISTINCT Guest_ID, Guest_Name
FROM CTE
WHERE Previous IS NOT NULL
AND DATEDIFF(Checkin_Date, Previous) <= 2;


-- Q5 (COHORT ANALYSIS)
-- For each cohort month, find:
-- total guests
-- and total bill revenue generated by those guests.
--
-- Definition:
-- Cohort Month = Month in which the guest registered.
--
-- Use both tables.
--
-- Return:
-- Cohort_Month
-- Total_Guests
-- Total_Bill_Revenue

WITH CTE AS (
	SELECT Guest_ID,
		   DATE_FORMAT(Registration_Date, '%Y-%m') AS Cohort_Month
	FROM Guests
)
SELECT Cohort_Month,
	   COUNT(DISTINCT C.Guest_ID) AS Total_Guests,
       SUM(R.Bill_Amount) AS Total_Bill_Revenue
FROM CTE C
INNER JOIN Reservations R
	ON C.Guest_ID = R.Guest_ID
GROUP BY Cohort_Month;


-- BONUS (GAP & ISLAND)
-- Find the start date and end date of each guest's
-- current reservation streak.
--
-- Return:
-- Guest_ID
-- Guest_Name
-- Current_Streak
-- Start_Date
-- End_Date
--
-- Definition:
-- Current streak = streak containing the guest's
-- most recent check-in date.
--
-- Note:
-- Ignore duplicate check-in dates if a guest
-- has multiple reservations on the same day.
--
-- Return only guests whose Current_Streak >= 3.

WITH CTE AS (
	SELECT DISTINCT G.Guest_ID, G.Guest_Name, R.Checkin_Date
    FROM Guests G
	INNER JOIN Reservations R
		ON G.Guest_ID = R.Guest_ID
),
CTE2 AS (
	SELECT *,
		   ROW_NUMBER() OVER(PARTITION BY Guest_ID
           ORDER BY Checkin_Date) AS RN
	FROM CTE
),
CTE3 AS (
	SELECT *,
		   DATE_SUB(Checkin_Date, INTERVAL RN DAY) AS GK
	FROM CTE2
),
CTE4 AS (
	SELECT Guest_ID, Guest_Name,
		   COUNT(*) AS Streak,
           MIN(Checkin_Date) AS Start_Date,
           MAX(Checkin_Date) AS End_Date
	FROM CTE3
    GROUP BY Guest_ID, Guest_Name, GK
),
CTE5 AS (
	SELECT *,
		   ROW_NUMBER() OVER(PARTITION BY Guest_ID
           ORDER BY End_Date DESC) AS Row_Num
	FROM CTE4
)
SELECT Guest_ID, Guest_Name, Streak AS Current_Streak,
	   Start_Date, End_Date
FROM CTE5
WHERE Row_Num = 1
AND Streak >= 3;


-- BONUS+
-- Find guests whose total bill amount
-- is greater than the average total bill amount
-- of guests in the same city.
--
-- Return:
-- Guest_ID
-- Guest_Name
-- City
-- Total_Bill_Amount

SELECT Guest_ID, Guest_Name, City, Total_Bill_Amount
FROM (
	SELECT *,
		   AVG(Total_Bill_Amount) OVER(PARTITION BY City) AS Avg_City
	FROM (
		SELECT G.Guest_ID, G.Guest_Name, G.City,
			   SUM(R.Bill_Amount) AS Total_Bill_Amount
		FROM Guests G
		INNER JOIN Reservations R
			ON G.Guest_ID = R.Guest_ID
		GROUP BY G.Guest_ID, G.Guest_Name, G.City
	)A
)C
WHERE Total_Bill_Amount > Avg_City;


-- For each city, find the guest who made the highest single reservation bill (not total spending).

-- Return:

-- City
-- Guest_ID
-- Guest_Name
-- Reservation_ID
-- Bill_Amount

SELECT *
FROM (
	SELECT *,
		   ROW_NUMBER() OVER(PARTITION BY City
           ORDER BY Bill_Amount DESC) AS Row_Num
	FROM (
		SELECT G.City, G.Guest_ID, G.Guest_Name, R.Reservation_ID, R.Bill_Amount
        FROM Guests G
		INNER JOIN Reservations R
			ON G.Guest_ID = R.Guest_ID
	)C
)H
WHERE Row_Num = 1;
		   