USE Daily_SQL;

-- DATASET: Shopping Analytics

CREATE TABLE Customers (
    Customer_ID INT PRIMARY KEY,
    Customer_Name VARCHAR(100),
    City VARCHAR(50),
    Join_Date DATE
);

CREATE TABLE Purchases (
    Purchase_ID INT PRIMARY KEY,
    Customer_ID INT,
    Product_Category VARCHAR(50),
    Purchase_Date DATE,
    Purchase_Amount DECIMAL(10,2),
    FOREIGN KEY (Customer_ID) REFERENCES Customers(Customer_ID)
);

INSERT INTO Customers
VALUES	(101,'Arun','Chennai','2024-01-05'),
		(102,'Divya','Bengaluru','2024-01-18'),
		(103,'Karthik','Chennai','2024-02-10'),
		(104,'Meena','Hyderabad','2024-02-25'),
		(105,'Rahul','Bengaluru','2024-03-08'),
		(106,'Sneha','Chennai','2024-03-20'),
		(107,'Vikram','Hyderabad','2024-04-02'),
		(108,'Priya','Chennai','2024-04-15'),
		(109,'Anil','Bengaluru','2024-05-01'),
		(110,'Neha','Hyderabad','2024-05-18');

INSERT INTO Purchases
VALUES	(1001,101,'Electronics','2024-01-06',25000),
		(1002,101,'Accessories','2024-01-07',1800),
		(1003,101,'Electronics','2024-01-08',32000),
		(1004,102,'Fashion','2024-01-20',4200),
		(1005,102,'Electronics','2024-01-23',27000),
		(1006,103,'Groceries','2024-02-11',2100),
		(1007,103,'Electronics','2024-02-12',30000),
		(1008,103,'Fashion','2024-02-13',5100),
		(1009,104,'Furniture','2024-02-27',45000),
		(1010,105,'Groceries','2024-03-09',1800),
		(1011,105,'Electronics','2024-03-10',28000),
		(1012,106,'Fashion','2024-03-22',4700),
		(1013,107,'Groceries','2024-04-03',2400),
		(1014,107,'Accessories','2024-04-04',2200),
		(1015,107,'Furniture','2024-04-05',38000),
		(1016,108,'Electronics','2024-04-17',26000),
		(1017,109,'Fashion','2024-05-02',5300),
		(1018,109,'Furniture','2024-05-03',41000),
		(1019,110,'Electronics','2024-05-19',29500),
		(1020,110,'Accessories','2024-05-20',1900);
        
SELECT *
FROM Customers;

SELECT *
FROM Purchases;

-- Q1
-- Show each customer's total purchases,
-- total purchase amount, and average purchase amount.
--
-- Use both tables.
--
-- Return:
-- Customer_ID
-- Customer_Name
-- Total_Purchases
-- Total_Purchase_Amount
-- Average_Purchase_Amount

SELECT C.Customer_ID, C.Customer_Name,
	   COUNT(P.Purchase_ID) AS  Total_Purchases,
       SUM(P.Purchase_Amount) AS Total_Purchase_Amount,
       ROUND(AVG(P.Purchase_Amount), 2) AS Average_Purchase_Amount
FROM Customers C
INNER JOIN Purchases P
	ON C.Customer_ID = P.Customer_ID
GROUP BY C.Customer_ID, C.Customer_Name;


-- Q2
-- Show each product category's total purchases
-- and total purchase revenue.
--
-- Return:
-- Product_Category
-- Total_Purchases
-- Total_Purchase_Revenue

SELECT Product_Category,
	   COUNT(Purchase_ID) AS Total_Purchases,
       SUM(Purchase_Amount) AS Total_Purchase_Revenue
FROM Purchases
GROUP BY Product_Category;


-- Q3
-- Find the top 3 customers by total purchase amount.
--
-- Use DENSE_RANK().
--
-- Return:
-- Customer_ID
-- Customer_Name
-- Total_Purchase_Amount

SELECT Customer_ID, Customer_Name, Total_Purchase_Amount
FROM (
	SELECT *,
		   DENSE_RANK() OVER(ORDER BY Total_Purchase_Amount DESC) AS D_Rank
	FROM (
		SELECT C.Customer_ID, C.Customer_Name,
			   SUM(P.Purchase_Amount) AS Total_Purchase_Amount
		FROM Customers C
		INNER JOIN Purchases P
			ON C.Customer_ID = P.Customer_ID
		GROUP BY C.Customer_ID, C.Customer_Name
	) T
) C
WHERE D_Rank <= 3;


-- Q4
-- Find customers who made a purchase within 2 days
-- of their previous purchase.
--
-- Use JOIN + LAG().
--
-- Return:
-- Customer_ID
-- Customer_Name

WITH CTE AS (
	SELECT C.Customer_ID, C.Customer_Name, P.Purchase_Date,
		   LAG(P.Purchase_Date) OVER(PARTITION BY C.Customer_ID
           ORDER BY P.Purchase_Date, Purchase_ID) AS Previous
	FROM Customers C
	INNER JOIN Purchases P
		ON C.Customer_ID = P.Customer_ID
),
CTE2 AS (
	SELECT *,
		   DATEDIFF(Purchase_Date, Previous) AS Days_Gap
	FROM CTE
)
SELECT DISTINCT Customer_ID, Customer_Name
FROM CTE2
WHERE Days_Gap <= 2;


-- Q5 (COHORT ANALYSIS)
-- For each cohort month, find:
-- total customers
-- and total purchase revenue generated by those customers.
--
-- Definition:
-- Cohort Month = Month in which the customer joined.
--
-- Use both tables.
--
-- Return:
-- Cohort_Month
-- Total_Customers
-- Total_Purchase_Revenue

WITH CTE AS (
	SELECT Customer_ID,
		   DATE_FORMAT(Join_Date, '%Y-%m') AS Cohort_Month
	FROM Customers
)
SELECT Cohort_Month,
	   COUNT(DISTINCT C.Customer_ID) AS Total_Customers,
       SUM(P.Purchase_Amount) AS Total_Purchase_Revenue
FROM CTE C
INNER JOIN Purchases P
	ON C.Customer_ID = P.Customer_ID
GROUP BY Cohort_Month;


-- BONUS (GAP & ISLAND)
-- Find the start date and end date of each customer's
-- longest purchase streak.
--
-- Return:
-- Customer_ID
-- Customer_Name
-- Longest_Streak
-- Start_Date
-- End_Date
--
-- Note:
-- Ignore duplicate purchase dates if a customer
-- has multiple purchases on the same day.
--
-- If multiple streaks have the same length,
-- return the most recent streak.

WITH CTE AS (
	SELECT DISTINCT C.Customer_ID, C.Customer_Name, P.Purchase_Date
	FROM Customers C
	INNER JOIN Purchases P
		ON C.Customer_ID = P.Customer_ID
),
CTE2 AS (
	SELECT *,
		   ROW_NUMBER() OVER(PARTITION BY Customer_ID
           ORDER BY Purchase_Date) AS RN
	FROM CTE
),
CTE3 AS (
	SELECT *,
		   DATE_SUB(Purchase_Date, INTERVAL RN DAY) AS GK
	FROM CTE2
),
CTE4 AS (
	SELECT Customer_ID, Customer_Name,
		   COUNT(*) AS Streak,
		   MIN(Purchase_Date) AS Start_Date,
		   MAX(Purchase_Date) AS End_Date
	FROM CTE3
	GROUP BY Customer_ID, Customer_Name, GK
),
CTE5 AS (
	SELECT *,
		   ROW_NUMBER() OVER(PARTITION BY Customer_ID
           ORDER BY Streak DESC, End_Date DESC) AS Row_Num
	FROM CTE4
)
SELECT Customer_ID, Customer_Name, Streak AS Longest_Streak,
	   Start_Date, End_Date
FROM CTE5
WHERE Row_Num = 1;


-- BONUS+
-- Find customers whose total purchase amount
-- is greater than the average total purchase amount
-- of customers in the same city.
--
-- Return:
-- Customer_ID
-- Customer_Name
-- City
-- Total_Purchase_Amount

SELECT Customer_ID, Customer_Name, City, Total_Purchase_Amount
FROM (
	SELECT *,
		   AVG(Total_Purchase_Amount) OVER(PARTITION BY City) AS Avg_City
	FROM (
		SELECT C.Customer_ID, C.Customer_Name, C.City,
			   SUM(P.Purchase_Amount) AS Total_Purchase_Amount
		FROM Customers C
		INNER JOIN Purchases P
			ON C.Customer_ID = P.Customer_ID
		GROUP BY C.Customer_ID, C.Customer_Name, C.City
	)C
)A
WHERE Total_Purchase_Amount > Avg_City;


-- For each product category, find the customer who made the highest single purchase.

-- Return:
-- Product_Category
-- Customer_ID
-- Customer_Name
-- Purchase_ID
-- Purchase_Amount

SELECT Product_Category, Customer_ID, Customer_Name, Purchase_ID, Purchase_Amount
FROM (
	SELECT *,
		   ROW_NUMBER() OVER(PARTITION BY Product_Category
           ORDER BY Purchase_Amount DESC) AS Row_Num
	FROM (
		SELECT C.Customer_ID, C.Customer_Name, P.Purchase_ID, P.Product_Category, P.Purchase_Amount
		FROM Customers C
		INNER JOIN Purchases P
			ON C.Customer_ID = P.Customer_ID
	)H
)S
WHERE Row_Num = 1;

-- Find the customer(s) whose total purchase amount is the highest overall.

-- Try using only:
-- GROUP BY
-- HAVING
-- Subqueries

SELECT C.Customer_ID, C.Customer_Name,
       SUM(P.Purchase_Amount) AS Total_Purchase_Amount
FROM Customers C
INNER JOIN Purchases P
	ON C.Customer_ID = P.Customer_ID
GROUP BY C.Customer_ID, C.Customer_Name
HAVING SUM(P.Purchase_Amount) = (
	SELECT MAX(Total_Purchase_Amount)
    FROM (
		SELECT C.Customer_ID, C.Customer_Name,
			   SUM(P.Purchase_Amount) AS Total_Purchase_Amount
		FROM Customers C
		INNER JOIN Purchases P
			ON C.Customer_ID = P.Customer_ID
		GROUP BY C.Customer_ID, C.Customer_Name
	)M
);