USE Daily_SQL;

-- DATASET: Ticket Booking System

CREATE TABLE Customers (
    Customer_ID INT PRIMARY KEY,
    Customer_Name VARCHAR(100),
    City VARCHAR(50),
    Join_Date DATE
);

CREATE TABLE Bookings (
    Booking_ID INT PRIMARY KEY,
    Customer_ID INT,
    Movie_Genre VARCHAR(50),
    Booking_Date DATE,
    Ticket_Amount DECIMAL(10,2),
    FOREIGN KEY (Customer_ID) REFERENCES Customers(Customer_ID)
);

INSERT INTO Customers
VALUES	(101,'Arun','Chennai','2024-01-05'),
		(102,'Divya','Bengaluru','2024-01-18'),
		(103,'Karthik','Hyderabad','2024-02-08'),
		(104,'Meena','Chennai','2024-02-20'),
		(105,'Rahul','Bengaluru','2024-03-04'),
		(106,'Sneha','Hyderabad','2024-03-18'),
		(107,'Vikram','Chennai','2024-04-02'),
		(108,'Priya','Bengaluru','2024-04-14'),
		(109,'Anil','Hyderabad','2024-05-01'),
		(110,'Neha','Chennai','2024-05-16');

INSERT INTO Bookings
VALUES	(1001,101,'Action','2024-01-06',450),
		(1002,101,'Comedy','2024-01-07',300),
		(1003,101,'Action','2024-01-08',500),
		(1004,102,'Drama','2024-01-20',350),
		(1005,102,'Action','2024-01-23',600),
		(1006,103,'Comedy','2024-02-09',250),
		(1007,103,'Thriller','2024-02-10',700),
		(1008,103,'Drama','2024-02-11',400),
		(1009,104,'Action','2024-02-22',550),
		(1010,105,'Comedy','2024-03-05',300),
		(1011,105,'Action','2024-03-06',650),
		(1012,106,'Drama','2024-03-19',450),
		(1013,107,'Thriller','2024-04-03',800),
		(1014,107,'Comedy','2024-04-04',350),
		(1015,107,'Action','2024-04-05',750),
		(1016,108,'Drama','2024-04-16',500),
		(1017,109,'Comedy','2024-05-02',280),
		(1018,109,'Thriller','2024-05-03',900),
		(1019,110,'Action','2024-05-17',650),
		(1020,110,'Comedy','2024-05-18',320);
        
SELECT *
FROM Customers;

SELECT *
FROM Bookings;

-- Q1
-- Show each customer's total bookings,
-- total ticket amount, and average ticket amount.
--
-- Use both tables.
--
-- Return:
-- Customer_ID
-- Customer_Name
-- Total_Bookings
-- Total_Ticket_Amount
-- Average_Ticket_Amount

SELECT C.Customer_ID, C.Customer_Name,
	   COUNT(B.Booking_ID) AS Total_Bookings,
       SUM(B.Ticket_Amount) AS Total_Ticket_Amount,
       ROUND(AVG(B.Ticket_Amount), 2) AS Average_Ticket_Amount
FROM Customers C
INNER JOIN Bookings B
	ON C.Customer_ID = B.Customer_ID
GROUP BY C.Customer_ID, C.Customer_Name;


-- Q2
-- Show each movie genre's total bookings
-- and total ticket revenue.
--
-- Return:
-- Movie_Genre
-- Total_Bookings
-- Total_Ticket_Revenue

SELECT Movie_Genre,
	   COUNT(Booking_ID) AS Total_Bookings,
       SUM(Ticket_Amount) AS Total_Ticket_Revenue
FROM Bookings
GROUP BY Movie_Genre;


-- Q3
-- Find the top 3 customers by total ticket amount.
--
-- Use DENSE_RANK().
--
-- Return:
-- Customer_ID
-- Customer_Name
-- Total_Ticket_Amount

WITH CTE AS (
	SELECT C.Customer_ID, C.Customer_Name,
		   SUM(B.Ticket_Amount) AS Total_Ticket_Amount
	FROM Customers C
	INNER JOIN Bookings B
		ON C.Customer_ID = B.Customer_ID
	GROUP BY C.Customer_ID, C.Customer_Name
),
CTE2 AS (
	SELECT *,
		   DENSE_RANK() OVER(ORDER BY Total_Ticket_Amount DESC) AS D_Rank
	FROM CTE
)
SELECT Customer_ID, Customer_Name, Total_Ticket_Amount
FROM CTE2
WHERE D_Rank <= 3;


-- Q4
-- Find customers who booked tickets within 2 days
-- of their previous booking.
--
-- Use JOIN + LAG().
--
-- Return:
-- Customer_ID
-- Customer_Name

WITH CTE AS (
	SELECT C.Customer_ID, C.Customer_Name, B.Booking_Date,
		   LAG(B.Booking_Date) OVER(PARTITION BY C.Customer_ID
           ORDER BY B.Booking_Date, B.Booking_ID) AS Previous
	FROM Customers C
	INNER JOIN Bookings B
		ON C.Customer_ID = B.Customer_ID
)
SELECT DISTINCT Customer_ID, Customer_Name
FROM CTE
WHERE Previous IS NOT NULL
AND DATEDIFF(Booking_Date, Previous) <= 2;


-- Q5 (COHORT ANALYSIS)
-- For each cohort month, find:
-- total customers
-- and total ticket revenue generated by those customers.
--
-- Definition:
-- Cohort Month = Month in which the customer joined.
--
-- Use both tables.
--
-- Return:
-- Cohort_Month
-- Total_Customers
-- Total_Ticket_Revenue

WITH CTE AS (
	SELECT Customer_ID,
		   DATE_FORMAT(Join_Date, '%Y-%m') AS Cohort_Month
	FROM Customers
)
SELECT Cohort_Month,
	   COUNT(DISTINCT C.Customer_ID) AS Total_Customers,
       SUM(B.Ticket_Amount) AS Total_Ticket_Revenue
FROM CTE C
INNER JOIN Bookings B
	ON C.Customer_ID = B.Customer_ID
GROUP BY Cohort_Month;


-- BONUS (GAP & ISLAND)
-- Find the start date and end date of each customer's
-- current booking streak.
--
-- Return:
-- Customer_ID
-- Customer_Name
-- Current_Streak
-- Start_Date
-- End_Date
--
-- Definition:
-- Current streak = streak containing the customer's
-- most recent booking date.
--
-- Note:
-- Ignore duplicate booking dates if a customer
-- has multiple bookings on the same day.
--
-- Return only customers whose Current_Streak >= 3.

WITH CTE AS (
	SELECT DISTINCT C.Customer_ID, C.Customer_Name, B.Booking_Date
    FROM Customers C
	INNER JOIN Bookings B
		ON C.Customer_ID = B.Customer_ID
),
CTE2 AS (
	SELECT *,
		   ROW_NUMBER() OVER(PARTITION BY Customer_ID
           ORDER BY Booking_Date) AS RN
	FROM CTE
),
CTE3 AS (
	SELECT *,
		   DATE_SUB(Booking_Date, INTERVAL RN DAY) AS GK
	FROM CTE2
),
CTE4 AS (
	SELECT Customer_ID, Customer_Name,
		   COUNT(*) AS Streak,
		   MIN(Booking_Date) AS Start_Date,
           MAX(Booking_Date) AS End_Date
	FROM CTE3
    GROUP BY Customer_ID, Customer_Name, GK
),
CTE5 AS (
	SELECT *,
		   ROW_NUMBER() OVER(PARTITION BY Customer_ID
           ORDER BY End_Date DESC) AS Row_Num
	FROM CTE4
)
SELECT Customer_ID, Customer_Name, Streak AS Current_Streak,
	   Start_Date, End_Date
FROM CTE5
WHERE Row_Num = 1
AND Streak >= 3;


-- BONUS+
-- Find customers whose total ticket amount
-- is greater than the average total ticket amount
-- of customers in the same city.
--
-- Return:
-- Customer_ID
-- Customer_Name
-- City
-- Total_Ticket_Amount

SELECT Customer_ID, Customer_Name, City, Total_Ticket_Amount
FROM (
	SELECT *,
		   AVG(Total_Ticket_Amount) OVER(PARTITION BY City) AS Avg_City
	FROM (
		SELECT C.Customer_ID, C.Customer_Name, C.City,
			   SUM(B.Ticket_Amount) AS Total_Ticket_Amount
		FROM Customers C
		INNER JOIN Bookings B
			ON C.Customer_ID = B.Customer_ID
		GROUP BY C.Customer_ID, C.Customer_Name, C.City
	)C
)A
WHERE Total_Ticket_Amount > Avg_City;

-- For each movie genre, find the customer who spent the highest total ticket amount in that genre.

WITH CTE AS (
	SELECT C.Customer_ID, C.Customer_Name, B.Movie_Genre,
		   SUM(B.Ticket_Amount) AS Total_Ticket_Amount
	FROM Customers C
	INNER JOIN Bookings B
		ON C.Customer_ID = B.Customer_ID
	GROUP BY C.Customer_ID, C.Customer_Name, B.Movie_Genre
),
CTE2 AS (
	SELECT *,
		   ROW_NUMBER() OVER(PARTITION BY Movie_Genre
           ORDER BY Total_Ticket_Amount DESC) AS Row_Num
	FROM CTE
)
SELECT Customer_ID, Customer_Name, Movie_Genre, Total_Ticket_Amount
FROM CTE2
WHERE Row_Num = 1;