USE Daily_SQL;

-- DATASET: Online Food Delivery

CREATE TABLE Customers (
    Customer_ID INT PRIMARY KEY,
    Customer_Name VARCHAR(100),
    City VARCHAR(50),
    Join_Date DATE
);

CREATE TABLE Orders (
    Order_ID INT PRIMARY KEY,
    Customer_ID INT,
    Restaurant_Name VARCHAR(100),
    Order_Date DATE,
    Order_Amount DECIMAL(10,2),
    FOREIGN KEY (Customer_ID) REFERENCES Customers(Customer_ID)
);

INSERT INTO Customers
VALUES	(101,'Arun','Chennai','2024-01-05'),
		(102,'Divya','Bengaluru','2024-01-18'),
		(103,'Karthik','Hyderabad','2024-02-08'),
		(104,'Meena','Chennai','2024-02-20'),
		(105,'Rahul','Bengaluru','2024-03-04'),
		(106,'Sneha','Hyderabad','2024-03-18'),
		(107,'Vikram','Chennai','2024-04-02'),
		(108,'Priya','Bengaluru','2024-04-14'),
		(109,'Anil','Hyderabad','2024-05-01'),
		(110,'Neha','Chennai','2024-05-16');

INSERT INTO Orders
VALUES	(1001,101,'Burger Hub','2024-01-06',450),
		(1002,101,'Pizza Point','2024-01-07',300),
		(1003,101,'Burger Hub','2024-01-08',500),
		(1004,102,'Biryani House','2024-01-20',350),
		(1005,102,'Burger Hub','2024-01-23',600),
		(1006,103,'Pizza Point','2024-02-09',250),
		(1007,103,'Taco Town','2024-02-10',700),
		(1008,103,'Biryani House','2024-02-11',400),
		(1009,104,'Burger Hub','2024-02-22',550),
		(1010,105,'Pizza Point','2024-03-05',300),
		(1011,105,'Burger Hub','2024-03-06',650),
		(1012,106,'Biryani House','2024-03-19',450),
		(1013,107,'Taco Town','2024-04-03',800),
		(1014,107,'Pizza Point','2024-04-04',350),
		(1015,107,'Burger Hub','2024-04-05',750),
		(1016,108,'Biryani House','2024-04-16',500),
		(1017,109,'Pizza Point','2024-05-02',280),
		(1018,109,'Taco Town','2024-05-03',900),
		(1019,110,'Burger Hub','2024-05-17',650),
		(1020,110,'Pizza Point','2024-05-18',320);
        

SELECT *
FROM Customers;

SELECT *
FROM Orders;

-- Q1
-- Show each customer's total orders,
-- total order amount, and average order amount.
--
-- Use both tables.
--
-- Return:
-- Customer_ID
-- Customer_Name
-- Total_Orders
-- Total_Order_Amount
-- Average_Order_Amount

SELECT C.Customer_ID, C.Customer_Name,
	   COUNT(O.Order_ID) AS Total_Orders,
       SUM(O.Order_Amount) AS Total_Order_Amount,
       ROUND(AVG(O.Order_Amount), 2) AS Average_Order_Amount
FROM Customers C
INNER JOIN Orders O
	ON C.Customer_ID = O.Customer_ID
GROUP BY C.Customer_ID, C.Customer_Name;


-- Q2
-- Show each restaurant's total orders
-- and total order revenue.
--
-- Return:
-- Restaurant_Name
-- Total_Orders
-- Total_Order_Revenue

SELECT Restaurant_Name,
	   COUNT(Order_ID) AS Total_Orders,
       SUM(Order_Amount) AS Total_Order_Revenue
FROM Orders
GROUP BY Restaurant_Name;


-- Q3
-- Find the top 3 customers by total order amount.
--
-- Use DENSE_RANK().
--
-- Return:
-- Customer_ID
-- Customer_Name
-- Total_Order_Amount

SELECT Customer_ID, Customer_Name, Total_Order_Amount
FROM (
	SELECT *,
		   DENSE_RANK() OVER(ORDER BY Total_Order_Amount DESC) AS D_Rank
	FROM (
		SELECT C.Customer_ID, C.Customer_Name,
			   COUNT(O.Order_ID) AS Total_Orders,
			   SUM(O.Order_Amount) AS Total_Order_Amount,
			   ROUND(AVG(O.Order_Amount), 2) AS Average_Order_Amount
		FROM Customers C
		INNER JOIN Orders O
			ON C.Customer_ID = O.Customer_ID
		GROUP BY C.Customer_ID, C.Customer_Name
	)T
)D
WHERE D_Rank <= 3;


-- Q4
-- Find customers who placed an order within 2 days
-- of their previous order.
--
-- Use JOIN + LAG().
--
-- Return:
-- Customer_ID
-- Customer_Name

WITH CTE AS (
	SELECT C.Customer_ID, C.Customer_Name, O.Order_Date,
		   LAG(O.Order_Date) OVER(PARTITION BY C.Customer_ID
           ORDER BY O.Order_Date, O.Order_ID) AS Previous
	FROM Customers C
	INNER JOIN Orders O
		ON C.Customer_ID = O.Customer_ID
)
SELECT DISTINCT Customer_ID, Customer_Name
FROM CTE
WHERE Previous IS NOT NULL
AND DATEDIFF(Order_Date, Previous) <= 2;


-- Q5 (COHORT ANALYSIS)
-- For each cohort month, find:
-- total customers
-- and total order revenue generated by those customers.
--
-- Definition:
-- Cohort Month = Month in which the customer joined.
--
-- Use both tables.
--
-- Return:
-- Cohort_Month
-- Total_Customers
-- Total_Order_Revenue

WITH CTE AS (
	SELECT Customer_ID,
		   DATE_FORMAT(Join_Date, '%Y-%m') AS Cohort_Month
	FROM Customers
)
SELECT Cohort_Month,
	   COUNT(DISTINCT C.Customer_ID) AS Total_Customers,
       SUM(O.Order_Amount) AS Total_Order_Revenue
FROM CTE C
INNER JOIN Orders O
	ON C.Customer_ID = O.Customer_ID
GROUP BY Cohort_Month;


-- BONUS (GAP & ISLAND)
-- Find the start date and end date of each customer's
-- longest order streak.
--
-- Return:
-- Customer_ID
-- Customer_Name
-- Longest_Streak
-- Start_Date
-- End_Date
--
-- Note:
-- Ignore duplicate order dates if a customer
-- has multiple orders on the same day.
--
-- If multiple streaks have the same length,
-- return the most recent streak.

WITH CTE AS (
	SELECT DISTINCT C.Customer_ID, C.Customer_Name, O.Order_Date
	FROM Customers C
	INNER JOIN Orders O
		ON C.Customer_ID = O.Customer_ID
),
CTE2 AS (
	SELECT *,
		   ROW_NUMBER() OVER(PARTITION BY Customer_ID
           ORDER BY Order_Date) AS RN
	FROM CTE
),
CTE3 AS (
	SELECT *,
		   DATE_SUB(Order_Date, INTERVAL RN DAY) AS GK
	FROM CTE2
),
CTE4 AS (
	SELECT Customer_ID, Customer_Name,
		   COUNT(*) AS Streak,
           MIN(Order_Date) AS Start_Date,
           MAX(Order_Date) AS End_Date
	FROM CTE3
    GROUP BY Customer_ID, Customer_Name, GK
),
CTE5 AS (
	SELECT *,
		   ROW_NUMBER() OVER(PARTITION BY Customer_ID
           ORDER BY Streak DESC, End_Date DESC) AS Row_Num
	FROM CTE4
)		   
SELECT Customer_ID, Customer_Name, Streak AS Longest_Streak,
	   Start_Date, End_Date
FROM CTE5
WHERE Row_Num = 1;


-- BONUS+
-- Find customers whose total order amount
-- is greater than the average total order amount
-- of customers in the same city.
--
-- Return:
-- Customer_ID
-- Customer_Name
-- City
-- Total_Order_Amount

WITH CTE AS (
	SELECT C.Customer_ID, C.Customer_Name, C.City,
		   SUM(O.Order_Amount) AS Total_Order_Amount
	FROM Customers C
	INNER JOIN Orders O
		ON C.Customer_ID = O.Customer_ID
	GROUP BY C.Customer_ID, C.Customer_Name, C.City
)
SELECT Customer_ID, Customer_Name, City, Total_Order_Amount
FROM (
	SELECT *,
		   AVG(Total_Order_Amount) OVER(PARTITION BY City) AS Avg_City
	FROM CTE
)A1
WHERE Total_Order_Amount > Avg_City;


-- For each restaurant, find the customer who placed the highest number of orders.

-- Return:

-- Restaurant_Name
-- Customer_ID
-- Customer_Name
-- Total_Orders

SELECT Restaurant_Name, Customer_ID, Customer_Name, Total_Orders
FROM (
	SELECT *,
		   DENSE_RANK() OVER(PARTITION BY Restaurant_Name
           ORDER BY Total_Orders DESC) AS D_Rank
    FROM (
		SELECT O.Restaurant_Name, C.Customer_ID, C.Customer_Name,
			   COUNT(O.Order_ID) AS Total_Orders
		FROM Customers C
		INNER JOIN Orders O
			ON C.Customer_ID = O.Customer_ID
		GROUP BY O.Restaurant_Name, C.Customer_ID, C.Customer_Name
	)H
)R
WHERE D_Rank = 1;


-- For each city, find the restaurant that generated the highest total revenue.

-- Return:
-- City
-- Restaurant_Name
-- Total_Revenue

SELECT City, Restaurant_Name, Total_Revenue
FROM (
	SELECT *,
		   DENSE_RANK() OVER(PARTITION BY City
           ORDER BY Total_Revenue DESC) AS D_Rank
    FROM (
		SELECT O.Restaurant_Name, C.City,
			   SUM(O.Order_Amount) AS Total_Revenue
		FROM Customers C
		INNER JOIN Orders O
			ON C.Customer_ID = O.Customer_ID
		GROUP BY O.Restaurant_Name, C.City
	)H
)R
WHERE D_Rank = 1;