USE Daily_SQL;

-- DATASET: Pharmacy Orders Analytics

CREATE TABLE Customers (
    Customer_ID INT PRIMARY KEY,
    Customer_Name VARCHAR(100),
    City VARCHAR(50),
    Join_Date DATE
);

CREATE TABLE Pharmacy_Orders (
    Order_ID INT PRIMARY KEY,
    Customer_ID INT,
    Medicine_Category VARCHAR(50),
    Order_Date DATE,
    Order_Amount DECIMAL(10,2),
    FOREIGN KEY (Customer_ID) REFERENCES Customers(Customer_ID)
);

INSERT INTO Customers
VALUES	(101,'Arun','Chennai','2024-01-05'),
		(102,'Divya','Bengaluru','2024-01-18'),
		(103,'Karthik','Hyderabad','2024-02-08'),
		(104,'Meena','Chennai','2024-02-20'),
		(105,'Rahul','Bengaluru','2024-03-04'),
		(106,'Sneha','Hyderabad','2024-03-18'),
		(107,'Vikram','Chennai','2024-04-02'),
		(108,'Priya','Bengaluru','2024-04-14'),
		(109,'Anil','Hyderabad','2024-05-01'),
		(110,'Neha','Chennai','2024-05-16');

INSERT INTO Pharmacy_Orders
VALUES	(1001,101,'Pain Relief','2024-01-06',450),
		(1002,101,'Vitamins','2024-01-07',300),
		(1003,101,'Pain Relief','2024-01-08',500),
		(1004,102,'Diabetes','2024-01-20',350),
		(1005,102,'Pain Relief','2024-01-23',600),
		(1006,103,'Vitamins','2024-02-09',250),
		(1007,103,'Skin Care','2024-02-10',700),
		(1008,103,'Diabetes','2024-02-11',400),
		(1009,104,'Pain Relief','2024-02-22',550),
		(1010,105,'Vitamins','2024-03-05',300),
		(1011,105,'Pain Relief','2024-03-06',650),
		(1012,106,'Diabetes','2024-03-19',450),
		(1013,107,'Skin Care','2024-04-03',800),
		(1014,107,'Vitamins','2024-04-04',350),
		(1015,107,'Pain Relief','2024-04-05',750),
		(1016,108,'Diabetes','2024-04-16',500),
		(1017,109,'Vitamins','2024-05-02',280),
		(1018,109,'Skin Care','2024-05-03',900),
		(1019,110,'Pain Relief','2024-05-17',650),
		(1020,110,'Vitamins','2024-05-18',320);
        
SELECT *
FROM Customers;

SELECT *
FROM Pharmacy_Orders;


-- Q1
-- Show each customer's total pharmacy orders,
-- total order amount, and average order amount.
--
-- Use both tables.
--
-- Return:
-- Customer_ID
-- Customer_Name
-- Total_Orders
-- Total_Order_Amount
-- Average_Order_Amount

SELECT C.Customer_ID, C.Customer_Name,
	   COUNT(P.Order_ID) AS Total_Orders,
       SUM(P.Order_Amount) AS Total_Order_Amount,
       ROUND(AVG(P.Order_Amount), 2) AS Average_Order_Amount
FROM Customers C
INNER JOIN Pharmacy_Orders P
	ON C.Customer_ID = P.Customer_ID
GROUP BY C.Customer_ID, C.Customer_Name;


-- Q2
-- Show each medicine category's total orders
-- and total revenue.
--
-- Return:
-- Medicine_Category
-- Total_Orders
-- Total_Revenue

SELECT Medicine_Category,
	   COUNT(Order_ID) AS Total_Orders,
       SUM(Order_Amount) AS Total_Revenue
FROM Pharmacy_Orders
GROUP BY Medicine_Category;


-- Q3
-- Find the top 3 customers by total order amount.
--
-- Use DENSE_RANK().
--
-- Return:
-- Customer_ID
-- Customer_Name
-- Total_Order_Amount

WITH CTE AS (
	SELECT C.Customer_ID, C.Customer_Name,
		   SUM(P.Order_Amount) AS Total_Order_Amount
	FROM Customers C
	INNER JOIN Pharmacy_Orders P
		ON C.Customer_ID = P.Customer_ID
	GROUP BY C.Customer_ID, C.Customer_Name
),
CTE2 AS (
	SELECT *,
		   DENSE_RANK() OVER(ORDER BY Total_Order_Amount DESC) AS D_Rank
	FROM CTE
)
SELECT Customer_ID, Customer_Name, Total_Order_Amount
FROM CTE2
WHERE D_Rank <= 3;


-- Q4
-- Find customers who placed an order within 2 days
-- of their previous order.
--
-- Use JOIN + LAG().
--
-- Return:
-- Customer_ID
-- Customer_Name

WITH CTE AS (
	SELECT C.Customer_ID, C.Customer_Name, P.Order_Date,
		   LAG(P.Order_Date) OVER(PARTITION BY C.Customer_ID
           ORDER BY P.Order_Date, P.Order_ID) AS Previous
	FROM Customers C
	INNER JOIN Pharmacy_Orders P
		ON C.Customer_ID = P.Customer_ID
)
SELECT DISTINCT Customer_ID, Customer_Name
FROM CTE
WHERE Previous IS NOT NULL
AND DATEDIFF(Order_Date, Previous) <= 2;


-- Q5 (COHORT ANALYSIS)
-- For each cohort month, find:
-- total customers
-- and total order revenue generated by those customers.
--
-- Definition:
-- Cohort Month = Month in which the customer joined.
--
-- Use both tables.
--
-- Return:
-- Cohort_Month
-- Total_Customers
-- Total_Order_Revenue

WITH CTE AS (
	SELECT Customer_ID,
		   DATE_FORMAT(Join_Date, '%Y-%m') AS Cohort_Month
	FROM Customers
)
SELECT Cohort_Month,
	   COUNT(DISTINCT C.Customer_ID) AS Total_Customers,
       SUM(P.Order_Amount) AS Total_Order_Revenue
FROM CTE C
INNER JOIN Pharmacy_Orders P
	ON C.Customer_ID = P.Customer_ID
GROUP BY Cohort_Month;


-- BONUS (GAP & ISLAND)
-- Find the start date and end date of each customer's
-- current order streak.
--
-- Return:
-- Customer_ID
-- Customer_Name
-- Current_Streak
-- Start_Date
-- End_Date
--
-- Definition:
-- Current streak = streak containing the customer's
-- most recent order date.
--
-- Note:
-- Ignore duplicate order dates if a customer
-- has multiple orders on the same day.
--
-- Return only customers whose Current_Streak >= 3.

WITH CTE AS (
	SELECT DISTINCT C.Customer_ID, C.Customer_Name, P.Order_Date
    FROM Customers C
	INNER JOIN Pharmacy_Orders P
		ON C.Customer_ID = P.Customer_ID
),
CTE2 AS (
	SELECT *,
		   ROW_NUMBER() OVER(PARTITION BY Customer_ID
           ORDER BY Order_Date) AS RN
	FROM CTE
),
CTE3 AS (
	SELECT *,
		   DATE_SUB(Order_Date, INTERVAL RN DAY) AS GK
	FROM CTE2
),
CTE4 AS (
	SELECT Customer_ID, Customer_Name,
		   COUNT(*) AS Streak,
           MIN(Order_Date) AS Start_Date,
           MAX(Order_Date) AS End_Date
	FROM CTE3
    GROUP BY Customer_ID, Customer_Name, GK
),
CTE5 AS (
	SELECT *,
		   ROW_NUMBER() OVER(PARTITION BY Customer_ID
           ORDER BY End_Date DESC) AS Row_Num
	FROM  CTE4
)
SELECT Customer_ID, Customer_Name, Streak AS Current_Streak,
	   Start_Date, End_Date
FROM CTE5
WHERE Row_Num = 1
AND Streak >= 3;


-- BONUS+
-- Find customers whose total order amount
-- is greater than the average total order amount
-- of customers in the same city.
--
-- Return:
-- Customer_ID
-- Customer_Name
-- City
-- Total_Order_Amount

SELECT Customer_ID, Customer_Name, City, Total_Order_Amount
FROM (
	SELECT *,
		   AVG(Total_Order_Amount) OVER(PARTITION BY City) AS Avg_City
	FROM (
		SELECT C.Customer_ID, C.Customer_Name, C.City,
			   SUM(P.Order_Amount) AS Total_Order_Amount
		FROM Customers C
		INNER JOIN Pharmacy_Orders P
			ON C.Customer_ID = P.Customer_ID
		GROUP BY C.Customer_ID, C.Customer_Name,C.City
	)A
)C
WHERE Total_Order_Amount > Avg_City;


-- For each medicine category, find the customer who spent the highest total amount in that category.

-- Return:
-- Medicine_Category
-- Customer_ID
-- Customer_Name
-- Total_Order_Amount

SELECT Medicine_Category, Customer_ID, Customer_Name, Total_Order_Amount
FROM (
	SELECT *,
		   DENSE_RANK() OVER(PARTITION BY Medicine_Category
           ORDER BY Total_Order_Amount DESC) AS D_Rank
	FROM (
		SELECT C.Customer_ID, C.Customer_Name, P.Medicine_Category,
			   SUM(P.Order_Amount) AS Total_Order_Amount
		FROM Customers C
		INNER JOIN Pharmacy_Orders P
			ON C.Customer_ID = P.Customer_ID
		GROUP BY C.Customer_ID, C.Customer_Name, P.Medicine_Category
	)M
)T
WHERE D_Rank = 1;


-- For each city, find the customer who ordered from the highest number of different medicine categories.

-- Return:
-- City
-- Customer_ID
-- Customer_Name
-- Total_Categories

SELECT City, Customer_ID, Customer_Name, Total_Categories
FROM (
	SELECT *,
		   DENSE_RANK() OVER(PARTITION BY City
           ORDER BY Total_Categories DESC) AS D_Rank
	FROM (
		SELECT C.Customer_ID, C.Customer_Name, C.City,
			   COUNT(DISTINCT P.Medicine_Category) AS Total_Categories
		FROM Customers C
		INNER JOIN Pharmacy_Orders P
			ON C.Customer_ID = P.Customer_ID
		GROUP BY C.Customer_ID, C.Customer_Name, C.City
	)M
)T
WHERE D_Rank = 1;


-- For each city, find the customer who has the highest average order amount (minimum 2 orders).

-- Return:
-- City
-- Customer_ID
-- Customer_Name
-- Average_Order_Amount

SELECT City, Customer_ID, Customer_Name, Average_Order_Amount
FROM (
	SELECT *,
		   DENSE_RANK() OVER(PARTITION BY City
           ORDER BY Average_Order_Amount DESC) AS D_Rank
	FROM (
		SELECT C.Customer_ID, C.Customer_Name, C.City,
			   ROUND(AVG(P.Order_Amount), 2) AS Average_Order_Amount,
               COUNT(P.Order_ID)
		FROM Customers C
		INNER JOIN Pharmacy_Orders P
			ON C.Customer_ID = P.Customer_ID
		GROUP BY C.Customer_ID, C.Customer_Name, C.City
        HAVING COUNT(P.Order_ID) >= 2
	)M
)T
WHERE D_Rank = 1;