USE Daily_SQL;

-- DATASET: Rental Analytics

CREATE TABLE Customers (
    Customer_ID INT PRIMARY KEY,
    Customer_Name VARCHAR(100),
    City VARCHAR(50),
    Join_Date DATE
);

INSERT INTO Customers
VALUES	(1,'Arun','Chennai','2024-01-10'),
		(2,'Divya','Bangalore','2024-02-15'),
		(3,'Karthik','Chennai','2024-03-20'),
		(4,'Sneha','Hyderabad','2024-01-25'),
		(5,'Rahul','Bangalore','2024-04-12'),
		(6,'Priya','Hyderabad','2024-02-28'),
		(7,'Vijay','Chennai','2024-05-05'),
		(8,'Anitha','Bangalore','2024-03-18');

CREATE TABLE Rentals (
    Rental_ID INT PRIMARY KEY,
    Customer_ID INT,
    Car_Type VARCHAR(50),
    Rental_Date DATE,
    Rental_Amount DECIMAL(10,2),
    FOREIGN KEY (Customer_ID) REFERENCES Customers(Customer_ID)
);

INSERT INTO Rentals
VALUES	(101,1,'SUV','2024-05-01',3500),
		(102,1,'SUV','2024-05-02',3200),
		(103,1,'Sedan','2024-05-03',2800),
		(104,1,'SUV','2024-05-07',3600),

		(105,2,'Hatchback','2024-05-02',1800),
		(106,2,'Sedan','2024-05-10',2500),

		(107,3,'SUV','2024-05-05',4100),
		(108,3,'SUV','2024-05-06',4200),
		(109,3,'SUV','2024-05-07',4300),
		(110,3,'Sedan','2024-05-15',2600),

		(111,4,'Luxury','2024-05-08',6500),
		(112,4,'Luxury','2024-05-09',6700),

		(113,5,'Sedan','2024-05-12',2400),
		(114,5,'SUV','2024-05-18',3900),

		(115,6,'Hatchback','2024-05-01',1700),
		(116,6,'Hatchback','2024-05-02',1800),
		(117,6,'Hatchback','2024-05-03',1750),

		(118,7,'SUV','2024-05-20',4400),

		(119,8,'Luxury','2024-05-11',7000),
		(120,8,'Luxury','2024-05-12',7100);
        
SELECT *
FROM Customers;

SELECT *
FROM Rentals;


-- Q1
-- Show each customer's total rentals,
-- total rental amount, and average rental amount.
--
-- Return:
-- Customer_ID
-- Customer_Name
-- Total_Rentals
-- Total_Rental_Amount
-- Average_Rental_Amount

SELECT C.Customer_ID, C.Customer_Name,
	   COUNT(R.Rental_ID) AS Total_Rentals,
       SUM(R.Rental_Amount) AS Total_Rental_Amount,
       ROUND(AVG(R.Rental_Amount), 2) AS Average_Rental_Amount
FROM Customers C
INNER JOIN Rentals R
	ON C.Customer_ID = R.Customer_ID
GROUP BY C.Customer_ID, C.Customer_Name;


-- Q2
-- Show each car type's total rentals
-- and total rental revenue.
--
-- Return:
-- Car_Type
-- Total_Rentals
-- Total_Rental_Revenue

SELECT Car_Type,
	   COUNT(Rental_ID) AS Total_Rentals,
       SUM(Rental_Amount) AS Total_Rental_Revenue
FROM Rentals
GROUP BY Car_Type;


-- Q3
-- Find the top 3 customers by total rental amount.
--
-- Use DENSE_RANK().
--
-- Return:
-- Customer_ID
-- Customer_Name
-- Total_Rental_Amount

WITH CTE AS (
	SELECT C.Customer_ID, C.Customer_Name,
		   SUM(R.Rental_Amount) AS Total_Rental_Amount
	FROM Customers C
	INNER JOIN Rentals R
		ON C.Customer_ID = R.Customer_ID
	GROUP BY C.Customer_ID, C.Customer_Name
),
CTE2 AS (
	SELECT *,
		   DENSE_RANK() OVER(ORDER BY Total_Rental_Amount DESC) AS D_Rank
	FROM CTE
)
SELECT Customer_ID, Customer_Name, Total_Rental_Amount
FROM CTE2
WHERE D_Rank <= 3;


-- Q4
-- Find customers who rented a car within 2 days
-- of their previous rental.
--
-- Use JOIN + LAG().
--
-- Return:
-- Customer_ID
-- Customer_Name

WITH CTE AS (
	SELECT C.Customer_ID, C.Customer_Name, R.Rental_Date,
		   LAG(R.Rental_Date) OVER(PARTITION BY C.Customer_ID
           ORDER BY R.Rental_Date, R.Rental_ID) AS Previous
	FROM Customers C
	INNER JOIN Rentals R
		ON C.Customer_ID = R.Customer_ID
)
SELECT DISTINCT Customer_ID, Customer_Name
FROM CTE
WHERE Previous IS NOT NULL
AND DATEDIFF(Rental_Date, Previous) <= 2;


-- Q5 (COHORT ANALYSIS)
-- For each cohort month, find:
-- total customers
-- and total rental revenue generated by those customers.
--
-- Definition:
-- Cohort Month = Month in which the customer joined.
--
-- Return:
-- Cohort_Month
-- Total_Customers
-- Total_Rental_Revenue

WITH CTE AS (
	SELECT Customer_ID,
		   DATE_FORMAT(Join_Date, '%Y-%m') AS Cohort_Month
	FROM Customers
)
SELECT Cohort_Month,
	   COUNT(DISTINCT C.Customer_ID) AS Total_Customers,
       SUM(R.Rental_Amount) AS Total_Rental_Revenue
FROM CTE C
INNER JOIN Rentals R
	ON C.Customer_ID = R.Customer_ID
GROUP BY Cohort_Month;


-- BONUS (GAP & ISLAND)
-- Find the start date and end date of each customer's
-- longest rental streak.
--
-- Return:
-- Customer_ID
-- Customer_Name
-- Longest_Streak
-- Start_Date
-- End_Date
--
-- Note:
-- Ignore duplicate rental dates if a customer
-- has multiple rentals on the same day.
--
-- If multiple streaks have the same length,
-- return the most recent streak.

WITH CTE AS (
	SELECT DISTINCT C.Customer_ID, C.Customer_Name, R.Rental_Date
	FROM Customers C
	INNER JOIN Rentals R
		ON C.Customer_ID = R.Customer_ID
),
CTE2 AS (
	SELECT *,
		   ROW_NUMBER() OVER(PARTITION BY Customer_ID
           ORDER BY Rental_Date) AS RN
	FROM CTE
),
CTE3 AS (
	SELECT *,
		   DATE_SUB(Rental_Date, INTERVAL RN DAY) AS GK
	FROM CTE2
),
CTE4 AS (
	SELECT Customer_ID, Customer_Name,
		   COUNT(*) AS Streak,
           MIN(Rental_Date) AS Start_Date,
		   MAX(Rental_Date) AS End_Date
	FROM CTE3
    GROUP BY Customer_ID, Customer_Name, GK
),
CTE5 AS (
	SELECT *,
		   ROW_NUMBER() OVER(PARTITION BY Customer_ID
           ORDER BY Streak DESC, End_Date DESC) AS Row_Num
	FROM CTE4
)
SELECT Customer_ID, Customer_Name, Streak AS Longest_Streak,
	   Start_Date, End_Date
FROM CTE5
WHERE Row_Num = 1;


-- BONUS+
-- Find customers whose total rental amount
-- is greater than the average total rental amount
-- of customers in the same city.
--
-- Return:
-- Customer_ID
-- Customer_Name
-- City
-- Total_Rental_Amount

SELECT Customer_ID, Customer_Name, City, Total_Rental_Amount
FROM (
	SELECT *,
		   AVG(Total_Rental_Amount) OVER(PARTITION BY City) AS Avg_City
	FROM (
		SELECT C.Customer_ID, C.Customer_Name, C.City,
			   SUM(R.Rental_Amount) AS Total_Rental_Amount
		FROM Customers C
		INNER JOIN Rentals R
			ON C.Customer_ID = R.Customer_ID
		GROUP BY C.Customer_ID, C.Customer_Name, C.City
	)A
)C
WHERE Total_Rental_Amount > Avg_City;


-- Interview Challenge
--
-- For each car type, find the customer who rented
-- that car type the greatest number of times.
--
-- Return:
-- Car_Type
-- Customer_ID
-- Customer_Name
-- Total_Rentals

SELECT Car_Type, Customer_ID, Customer_Name, Total_Rentals
FROM (
	SELECT *,
		   DENSE_RANK() OVER(PARTITION BY Car_Type
           ORDER BY Total_Rentals DESC) AS D_Rank
	FROM (
		SELECT R.Car_Type, C.Customer_ID, C.Customer_Name,
			   COUNT(R.Rental_ID) AS Total_Rentals
		FROM Customers C
		INNER JOIN Rentals R
			ON C.Customer_ID = R.Customer_ID
		GROUP BY R.Car_Type, C.Customer_ID, C.Customer_Name
	)C
)T
WHERE D_Rank = 1;


-- For each city, find the customer who generated the highest total rental revenue from SUV rentals only.

-- Return
-- City
-- Customer_ID
-- Customer_Name
-- Total_SUV_Revenue

SELECT City, Customer_ID, Customer_Name, Total_SUV_Revenue
FROM (
	SELECT *,
		   DENSE_RANK() OVER(PARTITION BY City
           ORDER BY Total_SUV_Revenue DESC) AS D_Rank
	FROM (
		SELECT C.Customer_ID, C.Customer_Name, C.City,
			   SUM(R.Rental_Amount) AS Total_SUV_Revenue
		FROM Customers C
		INNER JOIN Rentals R
			ON C.Customer_ID = R.Customer_ID
		WHERE R.Car_Type = "SUV"
		GROUP BY C.Customer_ID, C.Customer_Name, C.City
	)S
)R
WHERE D_Rank = 1;