USE Daily_SQL;

-- DATASET: Food Delivery Analytics

CREATE TABLE Customers (
    Customer_ID INT PRIMARY KEY,
    Customer_Name VARCHAR(100),
    City VARCHAR(50),
    Join_Date DATE
);

INSERT INTO Customers
VALUES	(1,'Arun','Chennai','2024-01-10'),
		(2,'Divya','Bangalore','2024-02-15'),
		(3,'Karthik','Chennai','2024-03-20'),
		(4,'Sneha','Hyderabad','2024-01-25'),
		(5,'Rahul','Bangalore','2024-04-12'),
		(6,'Priya','Hyderabad','2024-02-28'),
		(7,'Vijay','Chennai','2024-05-05'),
		(8,'Anitha','Bangalore','2024-03-18');

CREATE TABLE Orders (
    Order_ID INT PRIMARY KEY,
    Customer_ID INT,
    Restaurant_Type VARCHAR(50),
    Order_Date DATE,
    Order_Amount DECIMAL(10,2),
    FOREIGN KEY (Customer_ID) REFERENCES Customers(Customer_ID)
);

INSERT INTO Orders
VALUES	(101,1,'Indian','2024-06-01',650),
		(102,1,'Indian','2024-06-02',700),
		(103,1,'Chinese','2024-06-03',550),
		(104,1,'Indian','2024-06-08',900),

		(105,2,'Italian','2024-06-02',850),
		(106,2,'Chinese','2024-06-10',600),

		(107,3,'Indian','2024-06-05',750),
		(108,3,'Indian','2024-06-06',820),
		(109,3,'Indian','2024-06-07',790),
		(110,3,'Italian','2024-06-15',950),

		(111,4,'Desserts','2024-06-08',450),
		(112,4,'Desserts','2024-06-09',500),

		(113,5,'Chinese','2024-06-12',670),
		(114,5,'Indian','2024-06-18',980),

		(115,6,'Italian','2024-06-01',720),
		(116,6,'Italian','2024-06-02',760),
		(117,6,'Italian','2024-06-03',810),

		(118,7,'Indian','2024-06-20',1100),

		(119,8,'Desserts','2024-06-11',540),
		(120,8,'Desserts','2024-06-12',620);
        
SELECT *
FROM Customers;

SELECT *
FROM Orders;

-- Q1
-- Show each customer's total orders,
-- total order amount, and average order amount.
--
-- Return:
-- Customer_ID
-- Customer_Name
-- Total_Orders
-- Total_Order_Amount
-- Average_Order_Amount

SELECT C.Customer_ID, C.Customer_Name,
	   COUNT(O.Order_ID) AS Total_Orders,
       SUM(O.Order_Amount) AS Total_Order_Amount,
       ROUND(AVG(O.Order_Amount), 2) AS Average_Order_Amount
FROM Customers C
INNER JOIN Orders O
	ON C.Customer_ID = O.Customer_ID
GROUP BY C.Customer_ID, C.Customer_Name;


-- Q2
-- Show each restaurant type's total orders
-- and total order revenue.
--
-- Return:
-- Restaurant_Type
-- Total_Orders
-- Total_Order_Revenue

SELECT Restaurant_Type,
	   COUNT(Order_ID) AS Total_Orders,
       SUM(Order_Amount) AS Total_Order_Revenue
FROM Orders
GROUP BY Restaurant_Type;


-- Q3
-- Find the top 3 customers by total order amount.
--
-- Use DENSE_RANK().
--
-- Return:
-- Customer_ID
-- Customer_Name
-- Total_Order_Amount

WITH CTE AS (
	SELECT C.Customer_ID, C.Customer_Name,
		   SUM(O.Order_Amount) AS Total_Order_Amount
	FROM Customers C
	INNER JOIN Orders O
		ON C.Customer_ID = O.Customer_ID
	GROUP BY C.Customer_ID, C.Customer_Name
),
CTE2 AS (
	SELECT *,
		   DENSE_RANK() OVER(ORDER BY Total_Order_Amount DESC) AS D_Rank
	FROM CTE
)
SELECT Customer_ID, Customer_Name, Total_Order_Amount
FROM CTE2
WHERE D_Rank <= 3;


-- Q4
-- Find customers who placed an order within 2 days
-- of their previous order.
--
-- Use JOIN + LAG().
--
-- Return:
-- Customer_ID
-- Customer_Name

WITH CTE AS (
	SELECT C.Customer_ID, C.Customer_Name, O.Order_Date,
		   LAG(O.Order_Date) OVER(PARTITION BY C.Customer_ID
           ORDER BY O.Order_Date, O.Order_ID) AS Previous
	FROM Customers C
	INNER JOIN Orders O
		ON C.Customer_ID = O.Customer_ID
)
SELECT DISTINCT Customer_ID, Customer_Name
FROM CTE
WHERE Previous IS NOT NULL
AND DATEDIFF(Order_Date, Previous) <= 2;


-- Q5 (COHORT ANALYSIS)
-- For each cohort month, find:
-- total customers
-- and total order revenue generated by those customers.
--
-- Definition:
-- Cohort Month = Month in which the customer joined.
--
-- Return:
-- Cohort_Month
-- Total_Customers
-- Total_Order_Revenue

WITH CTE AS (
	SELECT Customer_ID,
		   DATE_FORMAT(Join_Date, '%Y-%m') AS Cohort_Month
	FROM Customers
)
SELECT Cohort_Month,
	   COUNT(DISTINCT C.Customer_ID) AS Total_Customers,
       SUM(O.Order_Amount) AS Total_Order_Revenue
FROM CTE C
INNER JOIN Orders O
	ON C.Customer_ID = O.Customer_ID
GROUP BY Cohort_Month;


-- BONUS (GAP & ISLAND)
-- Find the start date and end date of each customer's
-- current order streak.
--
-- Return:
-- Customer_ID
-- Customer_Name
-- Current_Streak
-- Start_Date
-- End_Date
--
-- Definition:
-- Current streak = streak containing the customer's
-- most recent order date.
--
-- Note:
-- Ignore duplicate order dates if a customer
-- has multiple orders on the same day.
--
-- Return only customers whose Current_Streak >= 3.

WITH CTE AS (
	SELECT DISTINCT C.Customer_ID, C.Customer_Name, O.Order_Date
	FROM Customers C
	INNER JOIN Orders O
		ON C.Customer_ID = O.Customer_ID
),
CTE2 AS (
	SELECT *,
		   ROW_NUMBER() OVER(PARTITION BY Customer_ID
           ORDER BY Order_Date) AS RN
	FROM CTE
),
CTE3 AS (
	SELECT *,
		   DATE_SUB(Order_Date, INTERVAL RN DAY) AS GK
	FROM CTE2
),
CTE4 AS (
	SELECT Customer_ID, Customer_Name,
		   COUNT(*) AS Streak,
           MIN(Order_Date) AS Start_Date,
           MAX(Order_Date) AS End_Date
	FROM CTE3
    GROUP BY Customer_ID, Customer_Name, GK
),
CTE5 AS (
	SELECT *,
		   ROW_NUMBER() OVER(PARTITION BY Customer_ID
           ORDER BY End_Date DESC) AS Row_Num
	FROM CTE4
)		   
SELECT Customer_ID, Customer_Name, Streak AS Current_Streak,
	   Start_Date, End_Date
FROM CTE5
WHERE Row_Num = 1
AND Streak >= 3;


-- BONUS+
-- Find customers whose total order amount
-- is greater than the average total order amount
-- of customers in the same city.
--
-- Return:
-- Customer_ID
-- Customer_Name
-- City
-- Total_Order_Amount

SELECT Customer_ID, Customer_Name, City, Total_Order_Amount
FROM (
	SELECT *,
		   AVG(Total_Order_Amount) OVER(PARTITION BY City) AS Avg_City
	FROM (
		SELECT C.Customer_ID, C.Customer_Name, C.City,
			   SUM(O.Order_Amount) AS Total_Order_Amount
		FROM Customers C
		INNER JOIN Orders O
			ON C.Customer_ID = O.Customer_ID
		GROUP BY C.Customer_ID, C.Customer_Name, C.City
	)A
)C
WHERE Total_Order_Amount > Avg_City;

-- Interview Challenge
--
-- For each restaurant type, find the customer
-- who spent the highest total amount.
--
-- Return:
-- Restaurant_Type
-- Customer_ID
-- Customer_Name
-- Total_Order_Amount

SELECT Restaurant_Type, Customer_ID, Customer_Name, Total_Order_Amount
FROM (
	SELECT *,
		   DENSE_RANK() OVER(PARTITION BY Restaurant_Type
           ORDER BY Total_Order_Amount DESC) AS D_Rank
	FROM (
		SELECT C.Customer_ID, C.Customer_Name, O.Restaurant_Type,
			   SUM(O.Order_Amount) AS Total_Order_Amount
		FROM Customers C
		INNER JOIN Orders O
			ON C.Customer_ID = O.Customer_ID
		GROUP BY C.Customer_ID, C.Customer_Name, O.Restaurant_Type
	)A
)C
WHERE D_Rank = 1;

-- Extra Interview Challenge
-- For each city, find the restaurant type that generated the highest total revenue.

-- Return
-- City
-- Restaurant_Type
-- Total_Revenue

SELECT City, Restaurant_Type, Total_Revenue
FROM (
	SELECT *,
		   DENSE_RANK() OVER(PARTITION BY City
           ORDER BY Total_Revenue DESC) AS D_Rank
	FROM (
		SELECT C.City, O.Restaurant_Type,
			   SUM(O.Order_Amount) AS Total_Revenue
		FROM Customers C
		INNER JOIN Orders O
			ON C.Customer_ID = O.Customer_ID
		GROUP BY C.City, O.Restaurant_Type
	)A
)C
WHERE D_Rank = 1;